### ISSUE TITLE
Unexpected mongo exit code 3221225595. Restarting.

### ISSUE THREAD

**Issue by Bomel** [meteor/meteor#10036]
Hi there,

I googeled a little bit around and couldn't find anything connected to that error. I only ran `meteor`.

Some console output: 
```
=> Started proxy.
=> A patch (Meteor 1.7.0.3) for your current release is available!
   Update this project now with 'meteor update --patch'.
Unexpected mongo exit code 3221225595. Restarting.
Unexpected mongo exit code 3221225595. Restarting.
Unexpected mongo exit code 3221225595. Restarting.
Can't start Mongo server.
```

I have really no clue what to do. I allready reinstallend Meteor. 

Additional information:
I'm using Windows 10,
I have already done `meteor update --patch` without any success 
Also tried diffrent meteor projects

**Comment by pacifio** [comment]
Yup having the same problem here , after a fresh install of meter via "choco install meteor" . Is it happening only in Windows os ? Because I tried it on ubuntu and it was perfectly fine . 

My meteor verison : 1.7.0.3

**Comment by thor-n** [comment]
I have the same problem. 

=> Started proxy.
Unexpected mongo exit code 3221225781. Restarting.
Unexpected mongo exit code 3221225781. Restarting.
Unexpected mongo exit code 3221225781. Restarting.
Can't start Mongo server.

On a new Windows 10 and new meteor install choco install

**Comment by sseun43** [comment]
Same problem here, gives really bad reputation for those of us that want to start using meteor

**Comment by thor-n** [comment]
I also just installed vc_redist.x64.exe from here and it worked perfect again

https://www.microsoft.com/en-us/download/confirmation.aspx?id=48145

**Comment by alangustavo** [comment]
Thank You thor-n!!

It worked for me!

> I also just installed vc_redist.x64.exe from here and it worked perfect again
> 
> https://www.microsoft.com/en-us/download/confirmation.aspx?id=48145

**Comment by abhay76** [comment]
> I also just installed vc_redist.x64.exe from here and it worked perfect again
> 
> https://www.microsoft.com/en-us/download/confirmation.aspx?id=48145

Thanks thor-n. Meteor guys should fix this somehow to help folks new to meteor.

**Comment by anjan55** [comment]
Thanks..Its help me to get rid of these issue.

**Comment by brankcar** [comment]
thanks, 

> I also just installed vc_redist.x64.exe from here and it worked perfect again
> 
> https://www.microsoft.com/en-us/download/confirmation.aspx?id=48145

Thank You thor-n!!

It worked for me!

**Comment by filipenevola** [comment]
I added this to the docs https://docs.meteor.com/windows.html#cant-start-mongo-server so people can find it easily later, I also added this to the error message https://github.com/meteor/meteor/commit/d2e1d694253f92ce66fbe333997059aa0773ea20

**Comment by juzer-z** [comment]
I went through https://docs.meteor.com/windows.html#cant-start-mongo-server , downloaded https://www.microsoft.com/en-us/download/confirmation.aspx?id=48145 and repaired. But still facing this issue:

Unexpected mongo exit code 3221225781. Restarting.
Unexpected mongo exit code 3221225781. Restarting.
Unexpected mongo exit code 3221225781. Restarting.
Unexpected mongo exit code 3221225781. Restarting.
Unexpected mongo exit code 3221225781. Restarting.
Unexpected mongo exit code 3221225781. Restarting.
Unexpected mongo exit code 3221225781. Restarting.
Can't start Mongo server.

**Comment by hmassareli** [comment]
> I went through https://docs.meteor.com/windows.html#cant-start-mongo-server , downloaded https://www.microsoft.com/en-us/download/confirmation.aspx?id=48145 and repaired. But still facing this issue:
> 
> Unexpected mongo exit code 3221225781. Restarting.
> Unexpected mongo exit code 3221225781. Restarting.
> Unexpected mongo exit code 3221225781. Restarting.
> Unexpected mongo exit code 3221225781. Restarting.
> Unexpected mongo exit code 3221225781. Restarting.
> Unexpected mongo exit code 3221225781. Restarting.
> Unexpected mongo exit code 3221225781. Restarting.
> Can't start Mongo server.

I am facing the same problem after all

**Comment by StorytellerCZ** [comment]
@hmassareli what version of Meteor are you on?

**Comment by hmassareli** [comment]
> @hmassareli what version of Meteor are you on?

I've just installed it, let me check...

**Comment by StorytellerCZ** [comment]
And I'm guessing that you are on Windows (just to confirm).

**Comment by hmassareli** [comment]
2.3.2

**Comment by hmassareli** [comment]
> And I'm guessing that you are on Windows (just to confirm).

Yes, I am!!

**Comment by hmassareli** [comment]
I've done that recommendation of reinstalling the vsc++ and stuff but nothing happened

**Comment by StorytellerCZ** [comment]
A wild guess, try installing this:
https://aka.ms/vs/16/release/vc_redist.x64.exe

Since we are using newer MongoDB then what the docs say there this one might be the correct one.

**Comment by hmassareli** [comment]
> A wild guess, try installing this:
> https://aka.ms/vs/16/release/vc_redist.x64.exe
> 
> Since we are using newer MongoDB then what the docs say there this one might be the correct one.

Yes I did this yesterday a bunch of times, I don't know why it still showing an error..
Just a question.. Am I supposed to set up something of mongodb before running meteor? Cause I just created a folder and installed everything and then created a test app, then I tried to run that in the folder with "meteor run".. Is that right? Do you think the folder that I installed the app could be a problem? It's in the C:\Users\henrique\www\teste

**Comment by StorytellerCZ** [comment]
No, you are doing it correctly. Meteor runs its own Mongo instance, so unless you want to get fancy it should just run.

I would suggest giving a standalone MongoDB server a try (get the 4.4.7 version):
https://www.mongodb.com/try/download/community

See if you can start that one up. If there is something specific to Windows that we are missing here it might be possible that MongoDB installer will take care of that. If you get it running, try starting Meteor again.

**Comment by hmassareli** [comment]
> No, you are doing it correctly. Meteor runs its own Mongo instance, so unless you want to get fancy it should just run.
> 
> I would suggest giving a standalone MongoDB server a try (get the 4.4.7 version):
> https://www.mongodb.com/try/download/community
> 
> See if you can start that one up. If there is something specific to Windows that we are missing here it might be possible that MongoDB installer will take care of that. If you get it running, try starting Meteor again.

Ok!! I will try that out, thanks

**Comment by hmassareli** [comment]
> No, you are doing it correctly. Meteor runs its own Mongo instance, so unless you want to get fancy it should just run.
> 
> I would suggest giving a standalone MongoDB server a try (get the 4.4.7 version):
> https://www.mongodb.com/try/download/community
> 
> See if you can start that one up. If there is something specific to Windows that we are missing here it might be possible that MongoDB installer will take care of that. If you get it running, try starting Meteor again.

Thaaanks, I downloaded that, installed a new meteor in a new folder, and then created a project, now everything works fine!!
