### ISSUE TITLE
Accounts-twitter login Fails internal server error

### ISSUE THREAD

**Issue by x5engine** [meteor/meteor#10041]
Hello all,
this is new and we're getting an internal server error when trying to login today.
We're using this
https://github.com/meteor/meteor/tree/devel/packages/accounts-twitter

we never changed anything, but maybe twitter changed their API?

thank you

**Comment by benjamn** [comment]
If you're not seeing any kind of explanation for the error (and it's coming from Twitter's servers?) then it sounds like it might just be a temporary outage? Let us know if you can get any more details!

**Comment by meteorplus** [comment]
@benjamn thanks Ben, I will do my best to try it out in the next hours, sadly no errors just a 505 error.

**Comment by meteorplus** [comment]
The issue is still happening I don't know why
you can try it out here
http://briefstory.tv

Thanks

**Comment by axelvaindal** [comment]
@meteorplus I have the same issue, did you find a way to fix this ?

**Comment by xmoroccan** [comment]
@meteorplus @axelvaindal When you toggle the console log you see this message:

> std_accounts-ui.js:2228 Implementations of Accounts.ui.Field must render message in v1.2.11.
          https://github.com/studiointeract/accounts-ui/#deprecations

Maybe there is something deperecated in your code!

**Comment by axelvaindal** [comment]
@xmoroccan I'm not using Accounts.ui. I try to logging on a custom button with `Meteor.loginWithTwitter` as I always did and it just doesn't work anymore. Was working previously though, same as @meteorplus.

**Comment by meteorplus** [comment]
@axelvaindal yes thank you for noticing this because it is not related to the UI something is failing in teh backend in the callback function but seems Twitter did some changes to their Oauth login!!!

@benjamn can you confirm if this twitter login is working for you?

@SachaG please what do you think of this?

**Comment by axelvaindal** [comment]
@meteorplus Here is the stack trace I'm experiencing when trying to log into Twitter with `Meteor.loginWithTwitter` function.

```
W20180711-16:17:29.728(2) (oauth.js:424) Error in OAuth Server: Failed to send OAuth1 request to https://api.twitter.com/oauth/request_token. failed [403] <?xml version="1.0" encoding="UTF-8"?><errors><error code="415">Callback URL not approved for this client application. Approved callback URLs can be adjusted in your application settings</error></errors>
```

The weird thing being that we didn't change our callback URL and it just stopped working.

**Comment by idmadj** [comment]
The callback URL is built with `Meteor.absoluteUrl('_oauth/' + serviceName, absoluteUrlOptions)`, and gets the URL's root (http://domain.com) from `__meteor_runtime_config__.ROOT_URL`.

The way `__meteor_runtime_config__.ROOT_URL` gets its value seems to have changed recently, which may explain why some people are having this issue.

A quick way to see what value is used is to run `Meteor.absoluteUrl()` in a client's console. If it's returning `http://localhost:3000/`, then the callback that twitter is receiving is `http://localhost:3000/_oauth/twitter`, which may not be great.

If the generated callback URL is good, you can verify that it is in the list of allowed callback URLs in your Twitter's application settings.

Otherwise, make sure that the `ROOT_URL` environment variable is set correctly, so that `Meteor.absoluteUrl()` returns the right callback URL (see [absoluteUrl](https://docs.meteor.com/api/core.html#Meteor-absoluteUrl) docs).

**Comment by axelvaindal** [comment]
@idmaj Thanks for you insight.
In my case, the `ROOT_URL` was correct, but the `callbackUrl` pointed to another path in my application.
Previously, this worked without any trouble, which is weird, but still a fact.
Now, it seems the callback url must be passed in the query and match the authorized one in the settings of the Twitter app.
Putting `https://mydomainname.com/_oauth/twitter` as the callback url solved the problem on my side and the Twitter login is back again.

One question though, is it possible to customize this callback url ? 
I would be able to use another callback url than the one imposed by the package, if possible.
I was looking in the docs about the configuration of callback url for `accounts-*` related package, but couldn't find anything.

**Comment by idmadj** [comment]
@axelvaindal AFAIK there's no way to customize the callback URL.

It is concatenated [here](https://github.com/meteor/meteor/blob/1818150ad6385ff64b1e3fb6f436c67b455f8dc7/packages/oauth/oauth_common.js#L56) and used directly, and the callback's route is hardcoded [here](https://github.com/meteor/meteor/blob/ee32e1328e669fb8ae53c1f0de9e2fa0d9a9cbff/packages/oauth/oauth_server.js#L6).

**Comment by axelvaindal** [comment]
@idmadj Okay, thank you for your help. As far as I am concerned, the issue is solved by double checking callback url. This must certainly be an issue for you too @meteorplus .

I'm going to normalize all my oauth callback url to reflect the hardcoding done in the `oauth` package of Meteor. If this is following some guidelines, it should stay as it is, otherwise, anyone interested can still open a FR in order to ask for customizing callback url and submit a PR.

**Comment by meteorplus** [comment]
Merci Axel @axelvaindal 
Je vais voir le probléme si sa marche :)
 
et thank you @idmadj for your help ;)

**Comment by axelvaindal** [comment]
@meteorplus Were you able to fix your issue with Twitter based on my comment and @idmadj solution ?
If so, perhaps we can close this issue as fixed ?

**Comment by meteorplus** [comment]
@axelvaindal No I didn't my client stil l has the issue there.

You can try it live here http://briefstory.tv

and see the error still happening, the callback is correct tho.

thanks

**Comment by meteorplus** [comment]
Still no solution for this please try it out and see it it live! we never changed anything.

**Comment by axelvaindal** [comment]
Just tried on my app right now, and everything is working fine 😟
In yours everything is broken, but this is unlikely coming from the package and more likely from your configuration.
Can you provide a reproduction repository with only accounts-ui twitter login not working so I could take a look ?
