### ISSUE TITLE
Updating a lot of documents causes 100% CPU

### ISSUE THREAD

**Issue by dovydaskukalis** [meteor/meteor#10324]
So there are a few pull requests like #9885 and #9862 which could potentially fix this issue or at least improve it but there has been no progress since May.

Problem is when updating let's say 10k or more documents (usually done running migrations), all servers basically stop responding for 5-15 mins as CPU goes to 100%  while it processes all oplogs (I assume), depending on updated documents count. We don't even use subscriptions a lot, only a few subs per user and it's limited to only 1 document returned so server usually has only ~300 subs 1 document each.

It affects all Meteor versions, including Node 8.12.0.

**Comment by KoenLav** [comment]
Yeah, I've been waiting for feedback on my PRs but it doesn't seem to be a priority...

**Comment by menelike** [comment]
For the time being, we reduced the impact of such operations with decreasing `METEOR_OPLOG_TOO_FAR_BEHIND` to `500`. Though we're eagerly waiting for a fix as well...

**Comment by StorytellerCZ** [comment]
@KoenLav There are comments on your PRs and they are being merged into the wrong branch, before those things are addressed, it is going to be hard to get @benjamn or @abernix moving unless they want to fix those things themselves.

**Comment by KoenLav** [comment]
@StorytellerCZ the PRs, which are targeting some pretty core parts of Meteor/DDP, haven't received any attention from the maintainers as far as I can tell.

Without a single comment from the maintainers, indicating whether this is the right direction, I really don't feel like spending any more time on this.

There's a lot of discussion in the topics which needs to be addressed/provided with some context.

Happy to spend more time on these issues after we can agree on a direction.

**Comment by dovydaskukalis** [comment]
@menelike Thanks, I will try it...

I am moving from Galaxy to AWS which has CPU burst ability so it might help a bit as well but hopefully a proper solution will come soon though as right now I wouldn't say Meteor is production ready if all servers go down after simple DB updates.

**Comment by menelike** [comment]
Please correct me if I'm wrong, but scaling instances doesn't solve the problem as all instance are flooded by oplog updates.

**Comment by veered** [comment]
Are you using simple schema or collection hooks? Those packages prevent bulk updates by forcing each updated document to be retrieved from the database and processed locally, and then updates that document individually.

**Comment by lamhieu-vk** [comment]
I have same problem for `livequery` when we have a lot of documents add/change/remove in same time!
and maybe have a lot of people have same this problem. I think it's in `livequery` way of working, we need to find ways to improve it!

**Comment by lamhieu-vk** [comment]
with subscriptions in client-side, I have a solution to use `lamhieu:hypersubs` to reduce subscriptions tracking to the server!
read more: https://github.com/lamhieu-vk/hypersubs
