### ISSUE TITLE
Creating or updating file issue isopacket `combined`

### ISSUE THREAD

**Issue by iBeACoder** [meteor/meteor#10930]
When I write the command

`meteor create Test` or `meteor update`

I get the following error message. The last working version of meteor is 1.8.3, from meteor 1.9 onwards I get the following error.

```
Errors prevented isopacket load:

While loading isopacket `combined`:
C:\Users\USER\AppData\Local\.meteor\packages\meteor-tool\1.9.2\mt-os.windows.x86_64\tools\fs\tools\fs\files.ts:1170:25: sourcemapConsumer.destroy is not a function
at C:\Users\USER\AppData\Local\.meteor\packages\meteor-tool\1.9.2\mt-os.windows.x86_64\tools\fs\tools\fs\files.ts:1170:25
at Function.time (C:\Users\USER\AppData\Local\.meteor\packages\meteor-tool\1.9.2\mt-os.windows.x86_64\tools\tool-env\tools\tool-env\profile.ts:284:12)
at Object.runJavaScript (C:\Users\USER\AppData\Local\.meteor\packages\meteor-tool\1.9.2\mt-os.windows.x86_64\tools\fs\tools\fs\files.ts:1147:18)
at C:\tools\isobuild\bundler.js:2188:15
at Function._.each._.forEach (C:\Users\USER\AppData\Local\.meteor\packages\meteor-tool\1.9.2\mt-os.windows.x86_64\dev_bundle\lib\node_modules\underscore\underscore.js:186:9)
at JsImage.load (C:\tools\isobuild\bundler.js:2048:7)
at C:\tools\tool-env\isopackets.js:313:17
at Object.capture (C:\tools\utils\buildmessage.js:283:5)
at loadIsopacketFromDisk (C:\tools\tool-env\isopackets.js:310:31)
at C:\tools\tool-env\isopackets.js:114:9
at loadIsopackage (C:\tools\tool-env\isopackets.js:105:21)
at new ServiceConnection (C:\tools\meteor-services\service-connection.js:28:21)
at Object.exports.openServiceConnection (C:\tools\meteor-services\auth-client.js:12:10)
at openPackageServerConnection (C:\tools\packaging\package-client.js:23:21)
at _updateServerPackageData (C:\tools\packaging\package-client.js:151:14)
at C:\tools\packaging\package-client.js:129:12
at Object.enterJob (C:\tools\utils\buildmessage.js:356:14)
at Object.exports.updateServerPackageData (C:\tools\packaging\package-client.js:128:23)
at C:\tools\packaging\catalog\catalog-remote.js:789:36
at Object.enterJob (C:\tools\utils\buildmessage.js:356:14)
at RemoteCatalog.refresh (C:\tools\packaging\catalog\catalog-remote.js:788:18)
at Object.catalog.refreshOrWarn (C:\tools\packaging\catalog\catalog.js:48:22)
at catalog.Refresh.OnceAtStart.beforeCommand (C:\tools\packaging\catalog\catalog.js:21:16)
at C:\tools\cli\main.js:1523:32
at Object.enterJob (C:\tools\utils\buildmessage.js:356:14)
at C:\tools\cli\main.js:1522:20


C:\Users\USER\AppData\Local\.meteor\packages\meteor-tool\1.9.2\mt-os.windows.x86_64\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:218
      throw error;
      ^

Error: isopacket load failed?
    at loadIsopacketFromDisk (C:\tools\tool-env\isopackets.js:321:11)
    at C:\tools\tool-env\isopackets.js:114:9
    at loadIsopackage (C:\tools\tool-env\isopackets.js:105:21)
    at new ServiceConnection (C:\tools\meteor-services\service-connection.js:28:21)
    at Object.exports.openServiceConnection (C:\tools\meteor-services\auth-client.js:12:10)
    at openPackageServerConnection (C:\tools\packaging\package-client.js:23:21)
    at _updateServerPackageData (C:\tools\packaging\package-client.js:151:14)
    at C:\tools\packaging\package-client.js:129:12
    at Object.enterJob (C:\tools\utils\buildmessage.js:356:14)
    at Object.exports.updateServerPackageData (C:\tools\packaging\package-client.js:128:23)
    at C:\tools\packaging\catalog\catalog-remote.js:789:36
    at Object.enterJob (C:\tools\utils\buildmessage.js:356:14)
    at RemoteCatalog.refresh (C:\tools\packaging\catalog\catalog-remote.js:788:18)
    at Object.catalog.refreshOrWarn (C:\tools\packaging\catalog\catalog.js:48:22)
    at catalog.Refresh.OnceAtStart.beforeCommand (C:\tools\packaging\catalog\catalog.js:21:16)
    at C:\tools\cli\main.js:1523:32
    at Object.enterJob (C:\tools\utils\buildmessage.js:356:14)
    at C:\tools\cli\main.js:1522:20
```

I have been searching for a reason since. I have uninstalled and reinstalled meteor since and nothing seems to work.

On occasion `meteor create` will give the error however the folder is create and when I run the command `meteor run` I get the same error.

**Comment by benjamn** [comment]
The relevant part of that stack trace is this:
```
sourcemapConsumer.destroy is not a function
```
That should be fixed by #10874, which is available in the Meteor 1.10 betas:
```
meteor update --release 1.10-beta.7
```
At this point, Meteor 1.10 is not much different from 1.9.2, so you might want to give the betas a try? Remember to commit your app to version control first, so that you can easily roll back if you encounter any instability.

**Comment by iBeACoder** [comment]
Thanks for the reply @benjamn 

I did as you recommended. I used the following command to create a new project:

`meteor create --release 1.10-beta.7 --full Unique`

I still got the following issue:

`sourcemapConsumer.destroy is not a function`

**Comment by santiagopuentep** [comment]
Getting the same error here. I can't update or create any Meteor project in Windows. Only one already created project in Meteor 1.8.1 works.

**Comment by santiagopuentep** [comment]
Tried doing a full uninstall and removing temporary files and even many registry entries and still the same issue, can't create of update to higher that 1.8.1.

**Comment by iBeACoder** [comment]
> The relevant part of that stack trace is this:
> 
> ```
> sourcemapConsumer.destroy is not a function
> ```
> 
> That should be fixed by #10874, which is available in the Meteor 1.10 betas:
> 
> ```
> meteor update --release 1.10-beta.7
> ```
> 
> At this point, Meteor 1.10 is not much different from 1.9.2 (unless you're using Cordova, which was upgraded from 7 to 9), so you might want to give the betas a try? Remember to commit your app to version control first, so that you can easily roll back if you encounter any instability.

I investigated this issue further and I discovered that while the error output is similar to #10874 it is not the same file. The error that I am facing (and probably @santiagopuentep) is in a different file. The error is in:

`tools/fs/files.ts` **on line 1170**

while the error on #10874 was related to as it provided the same error message, this error is in a different file, and 

`sourcemapConsumer.destroy is not a function`

is the error.

I consoled the value of **sourcemapConsumer** value and this is what I got:

**SourceMapConsumer {     -
  _names: ArraySet {
    _array: [
      'ECMAScript',        'compileForShell',
      'command',           'cacheOptions',
      'babelOptions',      'Babel',
      'getDefaultOptions', 'nodeMajorVersion',
      'parseInt',          'process',
      'versions',          'node',
      'sourceMap',         'sourceMaps',
      'ast',               'compile',
      'code'
    ],
    _set: Map {
      'ECMAScript' => 0,
      'compileForShell' => 1,
      'command' => 2,
      'cacheOptions' => 3,
      'babelOptions' => 4,
      'Babel' => 5,
      'getDefaultOptions' => 6,
      'nodeMajorVersion' => 7,
      'parseInt' => 8,
      'process' => 9,
      'versions' => 10,
      'node' => 11,
      'sourceMap' => 12,
      'sourceMaps' => 13,
      'ast' => 14,
      'compile' => 15,
      'code' => 16
    }
  },
  _sources: ArraySet {
    _array: [ 'meteor://💻app/packages/ecmascript/ecmascript.js' ],
    _set: Map { 'meteor://💻app/packages/ecmascript/ecmascript.js' => 0 }
  },
  _absoluteSources: [ 'meteor://💻app/packages/ecmascript/ecmascript.js' ],
  sourceRoot: null,
  sourcesContent: [
    'ECMAScript = {\n' +
      '  compileForShell(command, cacheOptions) {\n' +
      '    const babelOptions = Babel.getDefaultOptions({\n' +
      '      nodeMajorVersion: parseInt(process.versions.node, 10),\n' +
      '      compileForShell: true\n' +
      '    });\n' +
      '    delete babelOptions.sourceMap;\n' +
      '    delete babelOptions.sourceMaps;\n' +
      '    babelOptions.ast = false;\n' +
      '    return Babel.compile(command, babelOptions, cacheOptions).code;\n' +
      '  }\n' +
      '};\n'
  ],
  _mappings: ';;;;;;;;;;;;;;;;;;;;AAAAA,UAAU,GAAG;AACXC,iBAAe,CAACC,OAAD,EAAUC,YAAV,EAAwB;AACrC,UAAMC,YAAY,GAAGC,KAAK,CAACC,iBAAN,CAAwB;AAC3CC,sBAAgB,EAAEC,QAAQ,CAACC,OAAO,CAACC,QAAR,CAAiBC,IAAlB,EAAwB,EAAxB,CADiB;AAE3CV,qBAAe,EAAE;AAF0B,KAAxB,CAArB;AAIA,WAAOG,YAAY,CAACQ,SAApB;AACA,WAAOR,YAAY,CAACS,UAApB;AACAT,gBAAY,CAACU,GAAb,GAAmB,KAAnB;AACA,WAAOT,KAAK,CAACU,OAAN,CAAcb,OAAd,EAAuBE,YAAvB,EAAqCD,YAArC,EAAmDa,IAA1D;AACD;;AAVU,CAAb,C',
  _sourceMapURL: undefined,
  file: '/packages/ecmascript.js'
}**

as you can see there is no destroy function available in sourcemapConsumer object. Can anyone provide a solution to this problem?

**Comment by santiagopuentep** [comment]
@iBeACoder that's correct, my error is in `tools/fs/files.ts on line 1170`. Still can't update to any version.

**Comment by RailgunWinjoy** [comment]
Any solution yet? I want to update my project from 1.8.3 to 1.10.2

**Comment by santiagopuentep** [comment]
Same here.

**Comment by iBeACoder** [comment]
Hi @santiagopuentep & @RailgunWinjoy,  there is no solution to this as of yet. There was a solution mentioned #10874 but I don't know why the issue does not seem to be fixed.

**Comment by iBeACoder** [comment]
Hi @santiagopuentep & @RailgunWinjoy,
I have found a hacky way to resolve the issue. As there is no destroy function passed into the sourcemapConsumer object it makes sense to comment it out of/remove it from the code. On meteor repo, I believe the file is in 

`meteor/tools/fs/files.ts` **on line 1170**.

On my windows 10, I just went to:

`C:\Users\USER\AppData\Local\.meteor\packages\meteor-tool\1.10.2\mt-os.windows.x86_64\tools\fs\file.js`

and deleted:

`sourcemapConsumer.destroy();` **on line number 1188**.

This solved the problems for me. There is also a **linker.js** file that was causing some issues so I also did the same there:

`C:\Users\USER\AppData\Local\.meteor\packages\meteor-tool\1.10.2\mt-os.windows.x86_64\tools\isobuild\linker.js`

delete:

`sourcemapConsumer.destroy();` **on line number 780**.

That should solve it. I can now create and update apps without any more issues. 

But the meteor repo should be fixed to not have this for Windows, I would like to mention that this issues is only for Windows and not for Mac as it works perfectly on my Mac.

I hope this helps everyone struggling with this.

**Comment by delki8** [comment]
Hello @iBeACoder could you check something for me? Open `C:\Users\USER\AppData\Local\.meteor\packages\meteor-tool\1.10.2\mt-os.windows.x86_64\dev_bundle\lib\node_modules\source-map\package.json` and send me whatever is after `"_from":`[...]
From what I can tell the destroy was added "recently" to source-map and there was not so long ago that Meteor changed to a version of source-map that has (and enforces the use of) the `destroy()` function. So I just want to make sure that your Meteor installation is referring to a version of source map that really has this function.

**Comment by santiagopuentep** [comment]
@delki8 Here's the code `"_from": "source-map@0.7.3",`

@iBeACoder I tried deleting those lines and it worked. Thanks! This doesn't break anything in the app right? Great to finally be able to update meteor, I was stuck in 1.8.1.

**Comment by iBeACoder** [comment]
Hi @delki8,

@santiagopuentep as far as I have tested in my apps there has been nothing breaking.

As @santiagopuentep said I get the following:

`"_from": "source-map@0.7.3",`

Here is the whole file: (without the integrity)

```
{
"_from": "source-map@0.7.3",
"_id": "source-map@0.7.3",
"_inBundle": false,
"_integrity": "*****************************************************************",
"_location": "/source-map",
"_phantomChildren": {},
"_requested": {
"type": "version",
"registry": true,
"raw": "source-map@0.7.3",
"name": "source-map",
"escapedName": "source-map",
"rawSpec": "0.7.3",
"saveSpec": null,
"fetchSpec": "0.7.3"
},
  "_requiredBy": [
    "/"
  ],
  "_resolved": "https://registry.npmjs.org/source-map/-/source-map-0.7.3.tgz",
  "_shasum": "5302f8169031735226544092e64981f751750383",
  "_spec": "source-map@0.7.3",
  "_where": "C:\\jenkins\\workspace\\meteor-dev-bundle-windows\\platform\\windows_x64\\gdbXXX\\lib",
  "author": {
    "name": "Nick Fitzgerald",
    "email": "nfitzgerald@mozilla.com"
  },
  "bugs": {
    "url": "https://github.com/mozilla/source-map/issues"
  },
  "bundleDependencies": false,
  "contributors": [
    {
      "name": "Tobias Koppers",
      "email": "tobias.koppers@googlemail.com"
    },
    {
      "name": "Duncan Beevers",
      "email": "duncan@dweebd.com"
    },
    {
      "name": "Stephen Crane",
      "email": "scrane@mozilla.com"
    },
    {
      "name": "Ryan Seddon",
      "email": "seddon.ryan@gmail.com"
    },
    {
      "name": "Miles Elam",
      "email": "miles.elam@deem.com"
    },
    {
      "name": "Mihai Bazon",
      "email": "mihai.bazon@gmail.com"
    },
    {
      "name": "Michael Ficarra",
      "email": "github.public.email@michael.ficarra.me"
    },
    {
      "name": "Todd Wolfson",
      "email": "todd@twolfson.com"
    },
    {
      "name": "Alexander Solovyov",
      "email": "alexander@solovyov.net"
    },
    {
      "name": "Felix Gnass",
      "email": "fgnass@gmail.com"
    },
    {
      "name": "Conrad Irwin",
      "email": "conrad.irwin@gmail.com"
    },
    {
      "name": "usrbincc",
      "email": "usrbincc@yahoo.com"
    },
    {
      "name": "David Glasser",
      "email": "glasser@davidglasser.net"
    },
    {
      "name": "Chase Douglas",
      "email": "chase@newrelic.com"
    },
    {
      "name": "Evan Wallace",
      "email": "evan.exe@gmail.com"
    },
    {
      "name": "Heather Arthur",
      "email": "fayearthur@gmail.com"
    },
    {
      "name": "Hugh Kennedy",
      "email": "hughskennedy@gmail.com"
    },
    {
      "name": "David Glasser",
      "email": "glasser@davidglasser.net"
    },
    {
      "name": "Simon Lydell",
      "email": "simon.lydell@gmail.com"
    },
    {
      "name": "Jmeas Smith",
      "email": "jellyes2@gmail.com"
    },
    {
      "name": "Michael Z Goddard",
      "email": "mzgoddard@gmail.com"
    },
    {
      "name": "azu",
      "email": "azu@users.noreply.github.com"
    },
    {
      "name": "John Gozde",
      "email": "john@gozde.ca"
    },
    {
      "name": "Adam Kirkton",
      "email": "akirkton@truefitinnovation.com"
    },
    {
      "name": "Chris Montgomery",
      "email": "christopher.montgomery@dowjones.com"
    },
    {
      "name": "J. Ryan Stinnett",
      "email": "jryans@gmail.com"
    },
    {
      "name": "Jack Herrington",
      "email": "jherrington@walmartlabs.com"
    },
    {
      "name": "Chris Truter",
      "email": "jeffpalentine@gmail.com"
    },
    {
      "name": "Daniel Espeset",
      "email": "daniel@danielespeset.com"
    },
    {
      "name": "Jamie Wong",
      "email": "jamie.lf.wong@gmail.com"
    },
    {
      "name": "Eddy Bruël",
      "email": "ejpbruel@mozilla.com"
    },
    {
      "name": "Hawken Rives",
      "email": "hawkrives@gmail.com"
    },
    {
      "name": "Gilad Peleg",
      "email": "giladp007@gmail.com"
    },
    {
      "name": "djchie",
      "email": "djchie.dev@gmail.com"
    },
    {
      "name": "Gary Ye",
      "email": "garysye@gmail.com"
    },
    {
      "name": "Nicolas Lalevée",
      "email": "nicolas.lalevee@hibnet.org"
    }
  ],
  "deprecated": false,
  "description": "Generates and consumes source maps",
  "devDependencies": {
    "doctoc": "^0.15.0",
    "eslint": "^4.19.1",
    "live-server": "^1.2.0",
    "npm-run-all": "^4.1.2",
    "nyc": "^11.7.1",
    "watch": "^1.0.2",
    "webpack": "^3.10"
  },
  "engines": {
    "node": ">= 8"
  },
  "files": [
    "source-map.js",
    "source-map.d.ts",
    "lib/",
    "dist/source-map.js"
  ],
  "homepage": "https://github.com/mozilla/source-map",
  "license": "BSD-3-Clause",
  "main": "./source-map.js",
  "name": "source-map",
  "nyc": {
    "reporter": "html"
  },
  "repository": {
    "type": "git",
    "url": "git+ssh://git@github.com/mozilla/source-map.git"
  },
  "scripts": {
    "build": "webpack --color",
    "clean": "rm -rf coverage .nyc_output",
    "coverage": "nyc node test/run-tests.js",
    "dev": "npm-run-all -p --silent dev:*",
    "dev:live": "live-server --port=4103 --ignorePattern='(js|css|png)$' coverage",
    "dev:watch": "watch 'npm run coverage' lib/ test/",
    "lint": "eslint *.js lib/ test/",
    "prebuild": "npm run lint",
    "precoverage": "npm run build",
    "predev": "npm run setup",
    "pretest": "npm run build",
    "setup": "mkdir -p coverage && cp -n .waiting.html coverage/index.html || true",
    "test": "node test/run-tests.js",
    "toc": "doctoc --title '## Table of Contents' README.md && doctoc --title '## Table of Contents' CONTRIBUTING.md"
  },
  "types": "./source-map.d.ts",
  "typings": "source-map",
  "version": "0.7.3"
}
```

**Comment by delki8** [comment]
Thx @santiagopuentep and @iBeACoder. You're running the right version so the problem is probably somewhere else. I might dig into this a little deeper.

**Comment by afifalfiano** [comment]
> Hi @santiagopuentep & @RailgunWinjoy,
> I have found a hacky way to resolve the issue. As there is no destroy function passed into the sourcemapConsumer object it makes sense to comment it out of/remove it from the code. On meteor repo, I believe the file is in
> 
> `meteor/tools/fs/files.ts` **on line number 1170**.
> 
> and
> 
> `meteor/tools/isobuild/linker.js` **on line number 788**.
> 
> On my windows 10, I just went to:
> 
> `C:\Users\USER\AppData\Local\.meteor\packages\meteor-tool\1.10.2\mt-os.windows.x86_64\tools\fs\file.js`
> 
> and deleted:
> 
> `sourcemapConsumer.destroy();` **on line number 1188**.
> 
> This solved the problems for me. There is also a **linker.js** file that was causing some issues so I also did the same there:
> 
> `C:\Users\USER\AppData\Local\.meteor\packages\meteor-tool\1.10.2\mt-os.windows.x86_64\tools\isobuild\linker.js`
> 
> delete:
> 
> `sourcemapConsumer.destroy();` **on line number 780**.
> 
> That should solve it. I can now create and update apps without any more issues.
> 
> But the meteor repo should be fixed to not have this for Windows, I would like to mention that this issues is only for Windows and not for Mac as it works perfectly on my Mac.
> 
> I hope this helps everyone struggling with this.

Thanks, it's work on my project

**Comment by russpadgett** [comment]
Looks like there is a missing dependency.  
Do a "npm install source-map" before trying "meteor create Test" or "meteor update"

**Comment by kukupopo** [comment]
@iBeACoder, you are right on the point, commenting out 2 files solved the issue. Thank you.
This is my first time installing meteor and this ugly error immediately showed up and I had no clue how to solve it. Thank you once again.

**Comment by filipenevola** [comment]
Hi @santiagopuentep, @RailgunWinjoy, @kukupopo, can you install Meteor from scratch removing first all the old files? 

I can't reproduce this issue on new installations, as I'm not a Windows user I don't have previous installations on my Windows, maybe you have some old binaries.

I don't know why this function is not present when you have these issues https://github.com/mozilla/source-map/blob/7a263408de1b60e60b6220ca3e36d9b3e4aa047d/lib/source-map-consumer.js#L426-L431

We are using already the latest version of `source-map` and I don't see other issues like this so I don't think this is an issue in the current version of Meteor.

If you have a reproduction please provide here and I will be happy to investigate and fix the issue.

If you can reproduce in a fresh install we can also create a defensive code to avoid calling `destroy` when it is not defined but I would prefer to avoid this approach.

**Comment by santiagopuentep** [comment]
@filipenevola I did a reinstall many times removing everything, even searching in the registry to see if there was something there. The problem persisted. kukupopo also got the problem on a fresh reinstall.
We were able to solve the problem by commenting out those parts on the code but we don't know if that can create other issues. We are also still using Meteor 1.8.2 because 10.0.2 has a high CPU usage that makes it impossible to work with Meteor on Windows.

**Comment by iBeACoder** [comment]
> Hi @santiagopuentep, @RailgunWinjoy, @kukupopo, can you install Meteor from scratch removing first all the old files?
> 
> Could you share the content of `~/AppData\Local\.meteor\meteor.bat`?
> 
> I can't reproduce this issue on new installations, as I'm not a Windows user I don't have previous installations on my Windows, maybe you have some old binaries.
> 
> I don't know why this function is not present when you have these issues https://github.com/mozilla/source-map/blob/7a263408de1b60e60b6220ca3e36d9b3e4aa047d/lib/source-map-consumer.js#L426-L431
> 
> We are using already the latest version of `source-map` and I don't see other issues like this so I don't think this is an issue in the current version of Meteor.
> 
> If you have a reproduction please provide here and I will be happy to investigate and fix the issue.
> 
> If you can reproduce in a fresh install we can also create a defensive code to avoid calling `destroy` when it is not defined but I would prefer to avoid this approach.

Hi @filipenevola,

I am not sure why we get these issues. I have a mac and on it there are not issues of this sort.

However, on my windows, these issues are there. I have uninstalled Meteor, removed all the files, uninstalled Node and reinstalled all of it to get the same issue. I agree that writing defensive code would probably not be a great idea. If you refer to https://github.com/meteor/meteor/issues/10930#issuecomment-613324152 you will see the output of that I get when I print out **sourcemapConsumer Object**. There is no destroy function present.

**Comment by santiagopuentep** [comment]
@filipenevola here's the content of the meteor.bat file.

```
@echo off
SETLOCAL
SET METEOR_INSTALLATION=%~dp0%
"%~dp0\packages\meteor-tool\1.10.1\mt-os.windows.x86_64\meteor.bat" %*
ENDLOCAL
EXIT /b %ERRORLEVEL%
rem %~dp0\packages\meteor-tool\1.10.1\mt-os.windows.x86_64\meteor.bat
```

**Comment by kukupopo** [comment]
Hi @filipenevola,
As @santiagopuentep mentioned, mine was a clean install. 
I uninstalled and deleted all the relative meteor files and 
did an installation again and encountered same issue.

I'm using Meteor 1.10.2.

Here's the content of my meteor.bat, hope this helps : 

`@echo off
SETLOCAL
SET METEOR_INSTALLATION=%~dp0%
"%~dp0\packages\meteor-tool\1.10.2\mt-os.windows.x86_64\meteor.bat" %*
ENDLOCAL
EXIT /b %ERRORLEVEL%
rem %~dp0\packages\meteor-tool\1.10.2\mt-os.windows.x86_64\meteor.bat`

**Comment by santiagopuentep** [comment]
This is still happening here, whe can't update unless we do a hack.

**Comment by JEl2EMY** [comment]
Yup this still happens to me.

**Comment by dsten32** [comment]
I had a very similar problem and this solved it:
https://forums.meteor.com/t/solved-upgrade-1-10-2-problem-or-i-am-not-sure/52990/2

**Comment by iBeACoder** [comment]
> I had a very similar problem and this solved it:
> https://forums.meteor.com/t/solved-upgrade-1-10-2-problem-or-i-am-not-sure/52990/2

Thanks, @dsten32, this solved my problem as well.

**Comment by PatriciaHeimfarth** [comment]
I had the same issue and solved with the solution of @iBeACoder. But maybe this problem shouln't happen at all, so it is still an issue for this package

**Comment by StorytellerCZ** [comment]
@zodern is this something that you are working on?

**Comment by filipenevola** [comment]
This should be fixed in Meteor 2.5.2.

**Comment by zhe1ka** [comment]
> The relevant part of that stack trace is this:
> 
> ```
> sourcemapConsumer.destroy is not a function
> ```
> 
> That should be fixed by #10874, which is available in the Meteor 1.10 betas:
> 
> ```
> meteor update --release 1.10-beta.7
> ```
> 
> At this point, Meteor 1.10 is not much different from 1.9.2 (unless you're using Cordova, which was upgraded from 7 to 9), so you might want to give the betas a try? Remember to commit your app to version control first, so that you can easily roll back if you encounter any instability.

helped me, thanks!
