### ISSUE TITLE
Woes with Firefox Android and Svelte

### ISSUE THREAD

**Issue by arggh** [meteor/meteor#11059]
We received complaints from our users that our app wasn't loading on Firefox Android.

_And it wasn't._

Quickly (not...) launched the Firefox debugging console for Android and I was greeted with

```
TypeError: class constructors must be invoked with 'new' on
```

The same app works on Chrome on the same phone. I also tested it on the latest stable Firefox and the nightly, both failed with the same error message.

It doesn't matter which Svelte components I try to mount, they all fail.

`Meteor version 1.10.1`
`Svelte version 3.21.0`

Possibly relevant Meteor package versions:

`ecmascript@0.14.2`
`standard-minifier-js@2.6.0`
`dynamic-import@0.5.1`
`modern-browsers@0.1.5`

**Any ideas what might be the cause?**

**Comment by arggh** [comment]
This was resolved by forking `svelte:compiler` and updating the dependencies. It was using old versions of `babel-compiler`, `caching-compiler` and `ecmascript`. I also removed the `@babel/runtime` dependency: if I'm not mistaken, it should be  included in Meteor apps and there is no point in including another, lagging-behind version of the runtime.

Ping @klaussner and reference to https://github.com/meteor-svelte/meteor-svelte/pull/30

**Comment by arggh** [comment]
I take my previous statement back.

**_TL;DR_: I believe there is a bug in `modern-browsers` package.**

Not sure if I was mistaken about the browser I was on when I thought it worked, but it actually didn't work.

On Android Firefox, the browser gets the transpiled legacy bundle where the Svelte component is no longer a class, but a transpiled function:

```js
var App = /*#__PURE__*/function (_SvelteComponentDev) {
  _inheritsLoose(App, _SvelteComponentDev);

  var _super = _createSuper(App);

  function App(options) {
    var _this;

    _this = _SvelteComponentDev.call(this, options) || this; // <-- this will throw
```

...It tries however, to "extend" some of the Svelte internals in `modules.js` and those are still actual classes:

```
class SvelteComponentDev extends SvelteComponent {
    constructor(options) {
        if (!options || (!options.target && !options.$$inline)) {
            throw new Error(`'target' is a required option`);
        }
        super();
    }
    $destroy() {
        super.$destroy();
        this.$destroy = () => {
            console.warn(`Component was already destroyed`); // eslint-disable-line no-console
        };
    }
    $capture_state() { }
    $inject_state() { }
}
```
...which causes the error to be thrown.

Affected by this are at least Safari iOS 10 and Firefox Android (latest stable + nightly).

The solution, which at least seems to work, was pretty simple.

Include a symlink in `/app/imports` that points to `node_modules/svelte`. Or use the new config `meteor.nodeModules.recompile`I guess?

This way, the Svelte internals get transpiled as needed. @klaussner maybe it's a good idea to mention this in `svelte:compiler` docs?

**I'm re-opening this just to raise a question whether or not there is a bug in `modern-browsers` package**, since I believe the latest Firefox on Android could handle the modern bundle, but it gets shipped the legacy bundle. Why?

**Comment by xet7** [comment]
It is a bug in browser detection code. To get Meteor-based Wekan working on iOS Safari, Firefox Mobile, Chromium, Vivaldi, Opera, I did previously delete legacy bundle from Wekan, but now that has caused Wekan not working in legacy Microsoft Edge browser:
https://github.com/wekan/wekan/issues/3125#issuecomment-634022433

(Wekan does work also [as PWA](https://github.com/wekan/wekan/blob/master/CHANGELOG.md#v402-2020-05-15-wekan-release) but does not save anything to localstorage, it does not have offline support).

Would it be possible to update browser detection code?

**Comment by xet7** [comment]
It seems that stalebot did close previous issue about this #10692

@benjamn has there been progress since your comment at  https://github.com/meteor/meteor/issues/10692#issuecomment-533344603 ?

**Comment by xet7** [comment]
This issue still exists. Does @benjamn or someone other know has there been any progress? Or where I could find related code?

**Comment by CaptainN** [comment]
I'm not sure if this is precisely the issue, but it's worth noting that Svelte components from npm MUST be recompiled (and SHOULD be distributed as source), because Svelte is a compiler! It needs source, and it needs to compile.

For Meteor there are at least 3 build targets:
- server (Svelte compiles these differently - there is no interop between compiled SSR and client components)
- client modern
- client legacy

And there are differences in the compiled output between Svelte compiler versions, which means all Svelte components should be distributed as source, not as precompiled modules. I've had issues with some packages because of differences in the version of Svelte used to compile them before publishing to npm, and the versions I was using (and it's not a Meteor thing, it's a Svelte thing), and it has taken convincing to get the package author to ship source instead of compiled modules.

For Meteor, this means that Svelte component packages should be added to `meteor.nodeModules.recompile` as a matter of course.

**Comment by arggh** [comment]
> I'm not sure if this is precisely the issue

The original problem in my case was omitting Svelte from the recompiled modules, as you wrote, but it revealed another issue regarding `modern-browsers` that I stated above:

> I'm re-opening this just to raise a question whether or not there is a bug in modern-browsers package, since I believe the latest Firefox on Android could handle the modern bundle, but it gets shipped the legacy bundle. Why?

That no longer has anything to do with Svelte. I'm just curious why the latest Firefox on Android gets shipped a legacy bundle.

**Comment by hexsprite** [comment]
it seems like iOS Cordova also gets the legacy bundle as well. maybe it's just a cordova thing.

**Comment by xet7** [comment]
Problem is, mobile browsers should get modern bundle, and legacy edgehtml should get legacy bundle. Now it's vice versa, and that causes meteor apps to not work.

How to fix?

**Comment by CaptainN** [comment]
I'm sure it has something to do with the modern bundle white list. It uses browser sniffing to determine which to send, and Firefox's mobile user agent string is quite a bit different form its desktop counter part.

https://github.com/meteor/meteor/blob/devel/packages/modern-browsers/modern.js

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent/Firefox

**Comment by arggh** [comment]
No improvements have been made that I'm aware of, so please don't mark it as stale mr stale bot.

**Comment by antislash21** [comment]
Hello, has there been any advance regarding this ? We have a Meteor/Svelte application that's also not working on firefox android (with the same message about class contructors). Is there a workaround regarding this problem ?

We're using "geoffreybooth/meteor-base" docker image to compile/run the app.

**Comment by antislash21** [comment]
> Just wondering, have this PR helped a bit: #11671

Hi, I guess it does.

Our application is now working on firefox mobile (android). Previously I had to start meteor with --exclude-archs 'web.browser.legacy'

**Comment by xet7** [comment]
@StorytellerCZ

I think that this issue can be closed, because it works for @antislash21
