### ISSUE TITLE
Cordova iOS - Not working with Vue3

### ISSUE THREAD

**Issue by vbgm** [meteor/meteor#12958]
The default starting vue app `meteor create --vue simple-todos-vue` with `meteor-vite`, as well as custom one, using customised `vuejs:vue` (https://github.com/vbgm/meteor-vue3-less) in Cordova iOS as well as in Electron `meteor-desktop@3.1.1` have the same error related to `TypeError: effect2 of dep.keys is not a function`.

### Steps to reproduce
1. `meteor create --vue simple-todos-vue`
2. `cd simple-todos-vue`
3. `meteor add-platform ios` - assuming Xcode and prerequisites installed
4. `meteor add cordova:cordova-plugin-meteor-webapp@2.0.0` - because of meteor 2.14 cordova bug
5. `meteor run ios`
6. Observe that in browser the app starts and renders normally, whereas in Cordova and Electron there is a blank screen. When looking to Web Inspector console on either Cordova or Electron - there is the same / very similar error message.

### Actual behaviour
White screen of death

### Expected behavior
Rendering app

### Details
The full error log is below, I am still investigating the exact circumstances, so far I have understood that it is not because of `vue-router`(I've tried all the major versions) but rather ability of rendering dynamic variables inside templates, because static text is rendered without issues. The same I have seen before on Meteor 2.13.3 on my custom vue build and thought maybe it was my specific issue, yet it is the same elsewhere.

### System
* MacOS Ventura 13.5.2
* Meteor 2.13.3 and also 2.14 - the default `meteor create --vue simple-todos-vue` app

### Latest working
The latest working version of `vue` with Cordova iOS was 2.6.14 (not higher), tested both on Cordova iOS and Electron.

### Full log
```
[Log] HMR: connected (hot-module-replacement.js, line 343)
[Warning] [Vue warn]: Unhandled error during execution of setup function (11) (cordova.js, line 1413)
"
"
" at <RouterLink"
"to="
{name: "home"}
">"
"
"
" at <Header>"
"
"
" at <Index>"
"
"
" at <App>"
[Warning] [Vue Router warn]: Unexpected error when starting the router: – TypeError: effect2 of dep.keys is not a function. (In 'effect2 of dep.keys()', 'effect2 of dep.keys' is undefined) — modules.js:36357 (cordova.js, line 1413)
TypeError: effect2 of dep.keys is not a function. (In 'effect2 of dep.keys()', 'effect2 of dep.keys' is undefined) — modules.js:36357
[Log] Uncaught Error: TypeError: effect2 of dep.keys is not a function. (In 'effect2 of dep.keys()', 'effect2 of dep.keys' is undefined):26881:http://localhost:12296/__cordova/packages/modules.js?hash=11599c4652c72ee6b3afc396fa029552a6c4a1e4 (cordova.js, line 1413)
[Error] TypeError: effect2 of dep.keys is not a function. (In 'effect2 of dep.keys()', 'effect2 of dep.keys' is undefined)
	logError (modules.js:26881)
	handleError (modules.js:26868)
	callWithErrorHandling (modules.js:26820)
	setupStatefulComponent (modules.js:34206)
	setupComponent (modules.js:34167)
	mountComponent (modules.js:32496)
	processComponent (modules.js:32462)
	patch (modules.js:31941)
	mountChildren (modules.js:32189)
	mountElement (modules.js:32096)
	processElement (modules.js:32061)
	patch (modules.js:31929)
	componentUpdateFn (modules.js:32606)
	run (modules.js:36245)
	(anonymous function) (modules.js:32730)
	setupRenderEffect (modules.js:32740)
	mountComponent (modules.js:32508)
	processComponent (modules.js:32462)
	patch (modules.js:31941)
	mountChildren (modules.js:32189)
	mountElement (modules.js:32096)
	processElement (modules.js:32061)
	patch (modules.js:31929)
	componentUpdateFn (modules.js:32606)
	run (modules.js:36245)
	(anonymous function) (modules.js:32730)
	setupRenderEffect (modules.js:32740)
	mountComponent (modules.js:32508)
	processComponent (modules.js:32462)
	patch (modules.js:31941)
	mountChildren (modules.js:32189)
	processFragment (modules.js:32405)
	patch (modules.js:31915)
	componentUpdateFn (modules.js:32606)
	run (modules.js:36245)
	(anonymous function) (modules.js:32730)
	setupRenderEffect (modules.js:32740)
	mountComponent (modules.js:32508)
	processComponent (modules.js:32462)
	patch (modules.js:31941)
	render (modules.js:33251)
	mount (modules.js:30590)
	(anonymous function) (modules.js:20022)
	(anonymous function) (app.js:610)
	maybeReady (meteor.js:1033)
	releaseReadyHold (meteor.js:1022)
	(anonymous function) (cordova.js:827)
	(anonymous function) (cordova.js:232)
```

**Comment by vbgm** [comment]
I have double checked if that could be the problem of using Vue's Composition API (<script setup>) but no, it is the same on isolated Options API as well.

**Comment by vbgm** [comment]
Tested by downgrading npm `vue` package gradually from the latest back to 3.0.
On 3.2.47 starting to get different error (and the page is partially rendered except of router-related elements):

```
[Vue warn]: Unhandled error during execution of scheduler flush. This is likely a Vue internals bug. Please open an issue at https://new-issue.vuejs.org/?repo=vuejs/core 
"
"
" at <RouterView>"
"
"
" at <App>"

[Error] Unhandled Promise Rejection: TypeError: null is not an object (evaluating 'vnode.component.subTree')
	raise (promise.js:775)
	(anonymous function) (meteor.js:1379)
``` 

The 'latest' working version of vue was 2.6.14 (not higher), tested both on Cordova iOS and Electron.

**Comment by leonardoventurini** [comment]
Hey @vbgm we have a task programmed to look into this for the v2.17 release which will occur sometime in the future.

**Comment by roman-orlovskiy** [comment]
Have the same error in meteor 3: https://forums.meteor.com/t/error-with-vue-in-meteor-3-projects/61924/6

Tested in yandex browser (based on chrome)

**Comment by AnderbergE** [comment]
I am also experiencing issues with Meteor + Vue + Cordova (Android).
My steps to reproduce are very similar to reported steps. I followed the create --vue app flow, then I've added android platform and I'm using Meteor 3.3.2.
The app runs perfectly in the regular dev-environment in the browser. But on the Android emulator I receive the following error:
```
TypeError: Cannot read properties of null (reading 'subTree')
    at getNextHostNode (chunk-LG6AQRJS.js?v=708dc4b8:8166:46)
    at ReactiveEffect.componentUpdateFn [as fn] (chunk-LG6AQRJS.js?v=708dc4b8:7603:11)
    at ReactiveEffect.run (chunk-LG6AQRJS.js?v=708dc4b8:505:19)
    at ReactiveEffect.runIfDirty (chunk-LG6AQRJS.js?v=708dc4b8:543:12)
    at callWithErrorHandling (chunk-LG6AQRJS.js?v=708dc4b8:2296:33)
    at flushJobs (chunk-LG6AQRJS.js?v=708dc4b8:2504:9)
```

I've tracked this down to be an issue with using vue-router. When I comment out the vue-router, the app renders.
Done multiple hours of troubleshooting with AI input, but nothing has solved the issue (including changing vue-router's history). I feel like I cannot easily move further in the debugging.

Has anyone possibly solved, or found a way to work around, this issue?

**Comment by vbgm** [comment]
Bumping it up - I've tried with Meteor 3.4, 3.3, 3.2 - <router-view /> content is not rendering..

**Comment by vbgm** [comment]
Now continue testing in Meteor 3.4, so I have managed to make the Click Me button to react on clicks, as well as the <router-view /> to render its content. But when I switch routes I still have issues:

1. Downgrade Vue and Vue Router versions strictly to:
“vue”: “3.3.9” (not “^3.3.9”), "3.3.13" can also work, anything above won't trigger the Click Me button
“vue-router”: “4.2.5” (not “^4.2.5”) - anything above won't trigger the route even once - will throw the error immediately

2. Wait for mounting the vue in the /ui/main.js
```
import { Meteor } from 'meteor/meteor'
import { createApp } from 'vue'
import { VueMeteor } from 'vue-meteor-tracker'

import './main.css'
import App from './App.vue'
import { router } from './router'

Meteor.startup(() => {
  const app = createApp(App)
  app.use(router)
  app.use(VueMeteor)

  if (Meteor.isCordova) {
    document.addEventListener('deviceready', async function () {
      await router.isReady()
      app.mount('#app')
      console.log('mounted in cordova')
    }, { once: true })
    return
  }

  app.mount('#app')
  console.log('mounted in web')
})
```

3. Now it renders the `<router-view />` correctly but it switches the route only once (clicking on About), but whenever trying to click twice (clicking back to Home) - it throws the error:
<img width="2030" height="1324" alt="Image" src="https://github.com/user-attachments/assets/3401b489-c7e3-41fc-9efe-cfcd62675ab3" />

4. When Cmd+R within the Simulator console (Safari > Develop > …) - it refreshes the view in Simulator and shows the correct route view, but then after second click throws the error again.

**Comment by vbgm** [comment]
**The solution is:** use the modified ecmascript-runtime-client package (extracted from the upcoming Meteor `release-3.4.1` branch), described here: [Google Maps JS API will stop working in Cordova in May for iOS+Android · Issue #13094 · meteor/meteor · GitHub](https://github.com/meteor/meteor/issues/13094#issuecomment-3638725140)

Since it’s already merged to the `release-3.4.1` branch (and thus will be automatically fixed in 3.4.1 - I hope if no other new issues arise) - just download the latest meteor codebase zip from this branch, and copy the `/packages/ecmascript-runtime-client/` folder from the meteor into your meteor project’s `/packages/` folder (create it if it does not exist). Then during the launch it will use this one instead of the wrong one bundled with meteor 3.4 (and eventually all previous meteor 3 versions).

<img width="254" height="193" alt="Image" src="https://github.com/user-attachments/assets/167ef71c-e9fd-490f-b994-69267823c838" />
