### ISSUE TITLE
Meteor 3 --open opens the browser before the app is started

### ISSUE THREAD

**Issue by StorytellerCZ** [meteor/meteor#13175]
As the title says, this results in a blank page for a bit which can be confusing, so if possible the open command should trigger once the app is running.

**Comment by nachocodoner** [comment]
Confirmed, the open behavior (`=> Opening your app in a browser...`) runs before the app is running. Likely an await missing somewhere, or the behavior misbehaving on latest changes.

## Meteor 3

![image](https://github.com/meteor/meteor/assets/2581993/9afd2ca2-0f96-4942-868c-9f4550836d71)


## Meteor 2

Opens as expected.

![image](https://github.com/meteor/meteor/assets/2581993/278ae771-72b3-461d-bc8c-7107c0581cb1)

We take a note for this task. Thanks!

**Comment by AvinRai** [comment]
I was able to reproduce this issue as well. Could I please work on this?

**Comment by StorytellerCZ** [comment]
@AvinRai yes, go ahead.

**Comment by AvinRai** [comment]
Hi @StorytellerCZ! After replicating the issue, we found 3 relevant files: meteor\tools\cli\main.js, meteor\tools\cli\commands.js and meteor\tools\runners\run-all.j. As suggested by nachocodoner, we identified a missing await statement (await runner.start()) in run-all.js as shown in the picture below.

![img1](https://github.com/user-attachments/assets/b6e7e7d4-fdde-46ed-9044-350cd158c93c)

After we changed “setTimeout(() => runner.start(), 0);” to “await runner.start();”, the bug was resolved. But to ensure the validity of this change, we reviewed the commit history of run-all.js on GitHub. 

![img2_](https://github.com/user-attachments/assets/16cc91ca-7a6e-43f3-bd11-18e49a815653)
#
We noticed that @denihs changed the code from “await runner.start();” to “runner.start();” on March 3, 2023 because of a “circular dependency error” ([commit](https://github.com/meteor/meteor/commit/a32cdab2cabff929c6c1d1db9d735c4a5a32dc35)). Then on June 01, 2023, @matheusccastroo replaced “runner.start();” to “setTimeout(() => runner.start(), 0);” ([commit](https://github.com/meteor/meteor/commit/6922fb6457d339d7b4fc76c73d10df3ed54c1871)). Additionally, on October 24, 2023, @grubba27 added an “OnBuilt '' function for run-all.js ([commit](https://github.com/meteor/meteor/commit/d236b4d24c2fb57294561f2b7bba2c1073cf9c68)).

Could you please give insights on the reasons behind these changes and how we may proceed from here? FYI -- I'm working with @rhumtea and @kbarr1212.

**Comment by StorytellerCZ** [comment]
@matheusccastroo @denihs @Grubba27 can one of you shed some light here?

**Comment by rhumtea** [comment]
Hi @StorytellerCZ, @denihs, @matheusccastroo, @grubba27, 
We wanted to give you an update on this issue. We have learnt more about asynchronous, and have gained some insights, but we still cannot replicate the “circular dependency error”. 

Here is what we understand so far:
- In line 163, we use async start() to initiate an asynchronous operation. By declaring a function with an async keyword, we can use the await keyword to pause the execution of the line 407 (onBuilt && onBuilt();) until the promise from start() is resolved.

![image](https://github.com/user-attachments/assets/75fc0610-2536-47b5-92f0-bd9b8589dc12)

- In Meteor 2.16, we used await runner.start(). However, Meteor rc 3.0 has switched to setTimeout(() => runner.start(), 0). We think this change has a similar purpose as an await which facilitates promise resolution within applications.

![image](https://github.com/user-attachments/assets/cf518577-9f73-4ac3-b265-f8c074dd1a4f)

However, in our research and test, it seems that using an await is the better alternative to setTimeout as it has more robust handling issues. Could you please review this and share your thoughts? FYI -- I'm working with @AvinRai and @kbarr1212.

**Comment by nachocodoner** [comment]
Thank you very much for addressing this issue, @AvinRai , @kbarr1212 and @rhumtea!

I appreciate the detailed information you provide about the fix. I am curious why it does not await immediately as well; perhaps there are performance implications, and running processes in parallel without awaiting provides a more efficient experience.

However, one possible improvement is to ensure we pass the open option [from the command parameters](https://github.com/meteor/meteor/blob/devel/tools/cli/commands.js) to [the runAll behavior](https://github.com/meteor/meteor/blob/devel/tools/cli/commands.js#L488-L520). Then, only `await runner.start` if the open option is set. In other cases, we can use the existing `setTimeout` strategy. This way, we await only when necessary, specifically when the open option is passed.

**Comment by matheusccastroo** [comment]
Hey!

Hmm, I'm not sure I remember all the details but I think we don't need to `await` this because we are `awaiting` the promise on line 404: `var result = await promise` and this promise is what will tell us when the build/startup actually finished.

From a quick look, the problem happens because the `onBuilt` function call is on the wrong place, it should be after line 404.

**Comment by AvinRai** [comment]
Hi @matheusccastroo and @nachocodoner !

We've gone through the codebase and experimented many times. Here are our findings:

Expected behavior: the app is built and the page is automatically opened on the browser (when using the --open tag while running).

Proposed Solution By You: The app is built but the page is not automatically opened (we have to manually open it).

We have moved the onBuilt function to line 404 which has resulted in this.

Our recommendation: remove setTimeout() and use await instead.

CC: @kbarr1212, @rhumtea, and @eKuG

**Comment by nachocodoner** [comment]
> Our recommendation: remove setTimeout() and use await instead.

This for sure solves it. I did test it myself.

But the `setTimeout` might not be worth to have it, but if we do wish to keep it, I propesed to only await when open option is passed. So I would suggest this, until we get confirmation that we can use `await` in all scenarios, since this seemed to have been changed on the past. cc @denihs

**Comment by kbarr1212** [comment]
We have opened a pull request! https://github.com/meteor/meteor/pull/13300 with @AvinRai and @rhumtea 
@nachocodoner

**Comment by denihs** [comment]
The fix for this is merged and released with 3.0.3. Thank you all for your work! 

I'm closing this PR now.
