### ISSUE TITLE
Running package tests with Meteor 2 broke after meteor-node-stubs update

### ISSUE THREAD

**Issue by zodern** [meteor/meteor#13691]
When running `meteor test-packages` with Meteor 2, it fails with:

```
Error: Error: Could not install npm dependencies for test-packages: Command failed: /Users/zodern/.meteor/packages/meteor-tool/.2.7.3.6yxbth.cu3fg++os.osx.arm64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.arm64/dev_bundle/bin/npm install
sh: npmignore: command not found
npm ERR! premature close

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/zodern/.npm/_logs/2025-04-07T19_36_59_258Z-debug.log
sh: npmignore: command not found
npm ERR! premature close

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/zodern/.npm/_logs/2025-04-07T19_36_59_258Z-debug.log

    at Object.error (/tools/utils/buildmessage.js:467:11)
    at /tools/cli/default-npm-deps.js:37:20
    at Object.enterJob (/tools/utils/buildmessage.js:356:14)
    at Object.install (/tools/cli/default-npm-deps.js:28:27)
    at doTestCommand (/tools/cli/commands.js:1837:40)
    at Command.func (/tools/cli/commands.js:1743:10)
    at /tools/cli/main.js:1534:15
```

When running package tests, Meteor installs a copy of some npm packages for the tests, including meteor-node-stubs. The issue is that Node 14 and npm 6 can not install `browserify-sign`, possibly after https://github.com/meteor-compat/crypto-browserify/commit/f834da554f5ae0ad20755064548ab7811357989d

I think it would be fixed by publishing https://github.com/meteor-compat/browserify-sign to the npm registry, instead of using git. This would allow npm to skip running the prepack command.

**Comment by italojs** [comment]
Wip

**Comment by italojs** [comment]
Status report: 
The proposed modifications have been addressed, and a patch for [@meteorjs/crypto-browserify](https://www.npmjs.com/package/@meteorjs/crypto-browserify) has been published; however, it did not resolve the issue at hand. Since @illusionfiled successfully remedied the problem in their packages by enforcing the use of version 1.2.13 (1.2.14 current), I will investigate a little bit more, I will consider reverting the patch in the last case.

**Comment by illusionfield** [comment]
Even though the fix has been scheduled for the Release 2.16.1 #13621, the issue actually affects all Meteor 2.x versions. I ran into it fairly quickly during production deployments.

I haven't had the time to dig into the root cause yet, so I opted for a quick workaround by pinning.

Really glad to see this being addressed — thanks for the follow-up and the effort!

**Comment by italojs** [comment]
After a short investigation, I figured that the suggested fix by @zodern actually works but I was getting a cached version from my packages. So please remove Meteor by running `rm -rf ~/.meteor`, then install it again using `curl https://install.meteor.com/?release=2.17 | sh`, and let me know if it is working well.

The issue was within the [@meteorjs/crypto-browserify](https://www.npmjs.com/package/@meteorjs/crypto-browserify) npm packages that were using GitHub references for `@meteorjs/browserify-sign` and `@meteorjs/create-ecdh`, instead of pointing to the npm registry as @zodern suggested. I just pushed a new patch for the package (3.12.4).

my output:
```
❯ curl https://install.meteor.com/\?release\=2.17 | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7868    0  7868    0     0  11348      0 --:--:-- --:--:-- --:--:-- 11337
This Meteor 2.x version runs on a deprecated Node.js version (14). Meteor 3.0 is now available and supports the latest Node.js version. For details, check the migration guide: https://guide.meteor.com/3.0-migration.
Downloading Meteor distribution


 ~ ────────────────────────────────────────── 0|1 ✘  55s  base Py  09:59:43 
❯ meteor test-packages
italojs, this is your first time using Meteor!
Installing a Meteor distribution in your home directory.
Downloading Meteor distribution
######################################################################## 100.0%
[[[[[ Tests ]]]]]                             

=> Started proxy.                             
=> Started MongoDB.                           
=> Started your app.                          

=> App running at: http://localhost:3000/
```
My previous output was the same as this issue description

**Comment by illusionfield** [comment]
Thanks for the update!

Just a heads-up: the `meteor-node-stubs` package on npm still does not include the latest `@meteorjs/crypto-browserify` patch version (`3.12.4`), so `meteor npm install` currently fails when resolving the dependency.

Also, I really hope we won't need to delete the entire `~/.meteor` folder — I currently have 16 different Meteor tool versions installed, and some are `arm64`, others are `x64`. Since Meteor doesn't allow both architectures of the same version to coexist, I had to manually manage which architecture to use per version. This setup is essential for switching environments (e.g. Intel vs Apple Silicon), and rebuilding it would be quite time-consuming.

![Image](https://github.com/user-attachments/assets/b1a687f9-1e4c-425a-bcb1-98f06a3a72d0)

Once the `mt-os.osx.arm64` variant of a given Meteor version (e.g. 3.1.1) is installed, it’s no longer possible to add the `mt-os.osx.x86_64` variant — attempting to do so results in:

```
/Users/hoffy/.meteor/packages/meteor-tool/.3.1.2.t4z90u.4qm1e++os.osx.arm64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.arm64/tools/cli/main.js:458
    throw Error("missing tool for " + archinfo.host() + " in " + toolsPkg + "@" + toolsVersion);
          ^

Error: missing tool for os.osx.x86_64 in meteor-tool@3.1.1
    at springboard (/tools/cli/main.js:498:11)
    at /tools/cli/main.js:1161:7

Node.js v22.13.1
```

I’ve been experimenting with a custom installer (multi-arch Meteor installs), it’s not impossible.

**Comment by italojs** [comment]
@illusionfield did you try `meteor npm update meteor-node-stubs `?

**Comment by illusionfield** [comment]
@italojs 

Of course I did! 🙂

Unfortunately, it doesn’t help with the pinned dependencies — as you can see in the [source of `meteor-node-stubs`](https://www.npmjs.com/package/meteor-node-stubs?activeTab=code), version `1.2.14` still references `@meteorjs/crypto-browserify@3.12.2`, so the update does not propagate the fix.

```
meteor npm update meteor-node-stubs

> browserify-sign@4.2.3 prepack /Users/hoffy/.npm/_cacache/tmp/git-clone-f031beff
> npmignore --auto --commentLines=autogenerated

sh: npmignore: command not found
npm ERR! premature close

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/hoffy/.npm/_logs/2025-04-10T14_05_36_785Z-debug.log
```

(I cleared the cache)

**Comment by italojs** [comment]
Since we are using `^` statement in `"@meteorjs/crypto-browserify": "^3.12.2",` is expected to download the newest patch version.

I know the package-lock.json on into ~/.meteor folder that is downloading the broken package, but in the package itself, we haven't a pkg-lock there, so i suppose update the package `meteor-node-stubs` in the npm won't fix the problem 

I'll give an extra investigation

**Comment by illusionfield** [comment]
Yes, I thought the same — the `^3.12.2` should technically allow patch upgrades like `3.12.4`.

However, the published `meteor-node-stubs` package on the npm registry actually **includes** its dependencies inside its own `node_modules` folder, rather than letting npm resolve them at install time. So it ships with `@meteorjs/crypto-browserify@3.12.2` baked in.

You can verify this by browsing the contents here:  
https://www.npmjs.com/package/meteor-node-stubs?activeTab=code

<img src="https://github.com/user-attachments/assets/3ed17fc3-fb45-4713-ac61-d27cd474cbf3" width="300">

**Comment by italojs** [comment]
nice catch, that node_modules was introduced before version 0.4.0, removed
https://www.npmjs.com/package/meteor-node-stubs?activeTab=code

**Comment by italojs** [comment]
We tested it with some internal Galaxy customers who were experiencing the same issue. It's working for them. Let me know if it's working for you @illusionfield.

**Comment by illusionfield** [comment]
@italojs 
it works, great!
thx
