### ISSUE TITLE
Trouble using jQuery UI sortable with an array within a Mongo document

### ISSUE THREAD

**Issue by JackAdams** [meteor/meteor#2003]
I've got a feeling this might be expected behaviour in Blaze, given how things are indexed using the {{#each}} block helper, but this is something that used to work in Spark.  Repo showing the problem is here: https://github.com/JackAdams/blaze-issue and the example app is deployed here: http://blaze-issue-example-app.meteor.com/

**Comment by skosch** [comment]
Has there been any progress on this? I've spent all day pulling my hair out before I found this (not using sortable but something similar) and would really like a workaround of some sort ...

**Comment by dkmooers** [comment]
I've been using Sortable with Meteor with no issues (may have pulled
workarounds from this thread, can't remember though, been a while) - what's
the problem you're running into?

**Comment by mitar** [comment]
Yea, not sure what is wrong? It seems to work?

**Comment by skosch** [comment]
Oh, really? Maybe it's just me then. (Not being sarcastic—thanks for the fast reply!)

I have a custom drag-and-drop setup (not a sortable, because the mechanics are somewhat, um, special). Initially, it's a bunch of `<div>`s with `data-index={{index}}` attributes that are rendered (via `{{#each}}`) based on a helper that returns some array A from a collection. They all show up in the correct order.

Then I drag and drop, which involves appending the elements to `<body>` and later reappending them to their original parent. This changes the `data-index` attributes and the new order is written to a temporary array B. So far, so good. When I now update array A using said temporary array B (instead of resetting the form and discarding B), the changes are successfully written to the collection and the helper is called again, but the `<div>`s and their `data-index` attributes are suddenly all wrong and end up in the wrong place. Reloading the page (and thus re-creating the DOM) fixes the problem.

I can post code if my explanation isn't clear. I'm running the latest version of Meteor.

**Comment by dkmooers** [comment]
Hmm... can you post your code? Would be easier for me if I could play with
it. There are a bunch of little things like Deps.flush() that I can try.
I've also had some bizarre, inexplicable issues with jQuery that
disappeared when I started using vanilla JS to manipulate stuff (in one
particular instance involving re-ordering of elements reactively, and
swapping data-XYZ attributes).

**Comment by skosch** [comment]
Thanks @dkmooers! It's not easy to create a minimal example off hand, but here is the abridged version—I hope it's enough to give you some insight.
```html
    {{#each foreach setItems}}   <!-- foreach adds $index, nothing to see here -->
    <div class="setItem" data-setindex="{{$index}}">{{n}}</div>
    {{/each}}
```
and
```javascript
TableDisplayTemp = new Ground.Collection('tableDisplayTemp', {connection: null});

Template.TableViewMenu.helpers({
  setItems: function() {
    // this is array A
    return solvers.findOne(solverid).t[this.tableName].p;
  }
});

Template.TableViewMenu.events({
  "click .btnSubmit": function(e, t) {
    // updatePivotSets sets solvers.solverid.t.tableName.p = tempArray
    // tempArray is array B
    var tempArray = TableDisplayTemp.findOne({t: t.data.tableName}).pt;
    Meteor.call("updatePivotSets", solverid, t.data.tableName, tempArray);
    
    // at this point, all the data is updated
    // successfully (according to the console at least),
    // and Blaze re-runs the helper, but messes up
    // when it comes to re-writing the data-index attributes
  }
});

Template.TableViewMenu.onRendered(function() {
  // a whole bunch of functions dealing with the drag/drop stuff, the most
  // relevant being:

  $("div.setItemSlot").drop(function(ev, dd) {
    // ...

    // swap the data-indices of the dragged div
    // and the div it's displacing
    var index1 = dd.drag.dataset.setindex; // dragged item's index
    var index2 = this.dataset.slotindex; // previous item's index
    previousSetItem.attr("data-setindex", index1);
    $(dd.drag).attr("data-setindex", index2);

    // also swap the underlying objects in the temp array
    var oldTempPivotArray = TableDisplayTemp.findOne({t: tableName}).pt;
    var setObj = {};
    setObj["pt." + index1] = oldTempPivotArray[index2];
    setObj["pt." + index2] = oldTempPivotArray[index1];
    TableDisplayTemp.update({t: tableName}, {$set: setObj});
  });
});
```

I hope that's enough to give you the idea. If I'm doing something wrong and my behaviour is unrelated to this bug, don't hesitate to send me to stackoverflow :)

**Comment by dkmooers** [comment]
Hmm... with var oldTempPivotArray, have you tried cloning that using
_.clone()? I've had some issues with accessing arrays that were fixed by
cloning them first.

Another idea. For these lines:

previousSetItem.attr("data-setindex", index1);
$(dd.drag).attr("data-setindex", index2);

Try using vanilla JS to set the data-setindex instead of jQuery. I had a
very similar issue using jQuery, and I had to bend over backwards to get
the element's ID using jQuery, then getElementById, then get/set attributes
using vanilla JS. That ended up working though.

One other idea - is your "updatePivotSets" available to the client as well,
or server only? If client, I'm wondering if their might be some issue with
the client running the latency compensation version of your method, and
conflicting with the Blaze updates as it pulls the updated version from the
server. Or if you're using GroundDB, is this client-only?

**Comment by skosch** [comment]
So, I've tried both: wrapping all array copies in _.clone() and using setAttribute() instead of attr(). Neither work, unfortunately.

This might be a latency compensation issue. Maybe. The method is available to the client, and it's not a grounded collection. If I wanted to dig further, where should I start?

**Comment by dkmooers** [comment]
Well you could try isolating the method temporarily to the server and see
if that fixes it.

My code's a bit different, I think, since it just grabs all the current
blocks / elements (after dropping) and iterates through them, updating all
their sort indices. But maybe a couple things in here to try? Like have you
tried Deps.flush()? Or wrapping your Meteor.call() in a setTimeout of 1ms?
I think those helped me fix the sortable issue, though it's been a year
since I wrote this code so I don't fully remember how it works:

Template.whatsDue.onRendered(function() {
 // Make recurring item blocks sortable
$('#sortable').sortable({
helper: "clone",
update: function( event, ui ) {

var originIndex = ui.item.data('originIndex');
var currentIndex = ui.placeholder.index();
if (currentIndex > originIndex) {
currentIndex -= 1;
}
 var index = 0;
var newData = [];
$('.block-sortable').each(function() {
newData.push({_id: $(this).attr('id'), sort: index});
index++;
});
*setTimeout(function() {*
Meteor.call('updateRecurringTaskSortOrderAll', newData, function(error,
result) {
if (_.isUndefined(error)) {
displayNotice('success', 'Sort order saved!');
} else {
displayNotice(error);
}
});
self.$('#sortable').sortable('cancel');
*Deps.flush();*
*}, 1);*
},
handle: ".block-title",
start: function(event, ui) {
ui.item.data('originIndex', ui.item.index());
},
});
});

**Comment by skosch** [comment]
Thank you. None of them make any difference, unfortunately. The problem is still the same: after re-ordering the array in the collection and re-rendering the `{{#each}}`, Blaze renders the elements in the wrong order.

If I make the Meteor.call to updatePivotSets manually via the console, without previously dragging and dropping (and thus appending to body and later re-appending in a different order), everything jumps into place perfectly. So the issue is the same as what @sotarules reported above. I'll try to make some changes to make sure the order of elements is kept intact after dropping and I'll report back if that fixes it. Thanks for your help so far!

**Comment by dkmooers** [comment]
Okay sounds good, good luck!

**Comment by sotarules** [comment]
@skosh if you have time try this file:

https://www.dropbox.com/s/u87yrhshifk4yc4/jquery-ui-1.10.4.custom.zip?dl=0

This is a copy of JQuery Sortable that I have patched to fix the issue.  If you search the file for the word "Meteor" in the code you'll find the subtle changes that I made.  The changes make the "cancel" process more intelligent so the DOM is always returned to the exactly the same state to prior to the beginning of the drag operation, including the sensitive arrangement of text nodes. 

Note that I had proposed a "pull" request to JQuery UI developers for this change, but they rejected it as too esoteric (Meteor is not a very large community and not a big concern yet).

**Comment by skosch** [comment]
Thanks David. I just took a look at your file; it's pretty much exactly what I tried 10 minutes ago myself (I slapped a `data-position` attribute on them and then, based on those, used jQuery's `before`/`after` functions to re-insert the dropped elements into exactly the same place DOM they were before). I'm not sure if I trust this yet, but it seems to work so far.

**Comment by nathanwebb** [comment]
Today was my turn to spend hours trying to fix this issue :) Hopefully I can add something to help with a workaround.

I had this issue with items being duplicated and appearing out of order, and think that in my case it came down to two issues:

1) I was sorting an array from a single document, and initially the items didn't have an _id field. I've now added that in, and the items no longer appear out of order - unless I move them between lists.
2) I can't see it mentioned anywhere above, but perhaps a difference between people who can't see any issue, and those that can, is sorting between lists using the "connectWith" option in sortable. After adding in the _id, I still saw problems when sorting between lists, such as duplicates appearing. If I only sort within the one list, then everything works well. I've had to rewrite some small parts of my code to make multiple lists appear as one single list, using an outer div element as the sortable element.

**Comment by hwillson** [comment]
It's been a while since there has been any activity on this issue, and it's a bit difficult to tell its status based on the large number of comments and lack of a runnable reproduction. It sounds like this issue is either only showing up in edge cases, or not at all (some people have mentioned having difficulty re-creating the same problem). I'll close this issue, but if anyone thinks it should still be looked into, please open a new issue in the [Blaze repo](https://github.com/meteor/blaze) (ideally with a linked to reproduction). Thanks for posting this issue and the interesting discussion!

**Comment by mitar** [comment]
Yes, I think this is still existing and I have seen similar issues in my recent code with Blaze. It works most of the time, but sometimes sortable gets confused.

@sotarules: The link above does not work anymore. Can you show the patch you made?

Maybe we could make some library/code which fixes the DOM so that it is working for Blaze after we cancel the move? Or is necessary DOM stuff lost?

**Comment by sotarules** [comment]
@mitar I've created another Dropbox link and I'll leave it out there for a while:

https://www.dropbox.com/s/5qzdtvhl9gjdt3i/jquery-ui-1.10.4.custom.js?dl=0

Please see functions `_mouseStart` and `cancel` or search for Meteor within the JavaScript and you'll find my comments.  What I'm doing is making sure that when **cancel** is called, the DOM is returned to precisely the original state (including the arrangement of text nodes).

**Comment by sotarules** [comment]
Oh BTW @mitar it is not clear to me how one might be "correct" the DOM after this kind of corruption occurs.  I had considered creating a "shadow" DOM of the area in question and then reinstating that completely when cancel is called.  This would be a non-intrusive way to deal with the issue (i.e., no need to modify JQuery UI), but I had trouble making a reliable copy with all of the necessary objects, particularly the DomRange objects that are set up by Blaze.  It may be possible to do this, but I was not successful.  It seemed like "rocket science" to me at the time, if I recall correctly.

**Comment by mitar** [comment]
Hm, then maybe a better approach would be to provide a copy of the DOM for jQuery to manipulate, while the original DOM would be temporary hidden while dragging is happening. And on cancel the original DOM would be restored.

**Comment by sotarules** [comment]
The one thing to keep in mind is that when the user is dragging something, the visual effect of seeing that drag operation in progress, including the opening up of space to allow for dropping the object into a "slot" as represented by the _placeholder_, all of that by nature manipulates the DOM.  That animation, for lack of a better word, is what causes the damage to the DomRanges, and that animation must be performed either on the real DOM or a copy.

**Comment by mitar** [comment]
I am reopening this because I think there should be at least some package or something which fixes this. Maybe at least Meteor version of jQuery UI could contain the patch. Maybe @mizzao could apply it?

**Comment by hwillson** [comment]
Thanks @mitar - do you think this issue should stay open here for tracking, or be moved to the Blaze repo?

**Comment by mitar** [comment]
I think we should be probably moved to Blaze. Could you do that please?

**Comment by hwillson** [comment]
Sure thing @mitar - done: meteor/blaze#186. Closing this one - thanks!

**Comment by mitar** [comment]
Thank you!
