### ISSUE TITLE
Meteor wont update packages unless you remove and add them

### ISSUE THREAD

**Issue by Tarang** [meteor/meteor#2500]
Meteor knows there is an update as seen below:

```
$ meteor list
accounts-base          1.0.0  A user account system
accounts-facebook      1.0.0  Login service for Facebook accounts
accounts-password      1.0.0  Password support for accounts
accounts-ui            1.0.0  Simple templates to add login widgets to an app
standard-app-packages  1.0.0  Include a standard set of Meteor packages in yo...
service-configuration  1.0.0  Manage the configuration for third-party services
natestrauser:select2   3.4.5* Select2 is a jQuery based replacement for selec...
accounts-google        1.0.0  Login service for Google accounts
mrt:jquery-jcrop       0.0.3  jQuery Jcrop repackaged for Meteor
package-stats-opt-out  1.0.0  Opt out of sending package stats
iron:router            0.9.1  Routing specifically designed for Meteor

 * New versions of these packages are available! Run 'meteor update' to update.
$ meteor update
Refreshing package metadata. This may take a moment.
This project is already at Meteor 0.9.0.1, the latest release.
$ meteor update --packages-only
Refreshing package metadata. This may take a moment.
All your package dependencies are already up to date.
$
```

As can be seen `natestrauser:select2` has the asterisk next to it.

I have raised this issue before but this time at least something can show this.

.meteor/packages
```
# Meteor packages used by this project, one per line.
#
# 'meteor add' and 'meteor remove' will edit this file for you,
# but you can also edit it by hand.

accounts-base
accounts-facebook
accounts-password
accounts-ui
standard-app-packages
service-configuration
natestrauser:select2@3.4.5
accounts-google
mrt:jquery-jcrop@0.0.3
package-stats-opt-out
iron:router
```

.meteor/versions
```
accounts-base@1.0.0
accounts-facebook@1.0.0
accounts-google@1.0.0
accounts-oauth@1.0.0
accounts-password@1.0.0
accounts-ui-unstyled@1.0.0
accounts-ui@1.0.0
application-configuration@1.0.0
autoupdate@1.0.5
binary-heap@1.0.0
blaze-tools@1.0.0
blaze@1.0.3
callback-hook@1.0.0
check@1.0.0
ctl-helper@1.0.2
ctl@1.0.0
deps@1.0.1
ejson@1.0.0
email@1.0.2
facebook@1.0.0
follower-livedata@1.0.0
geojson-utils@1.0.0
google@1.0.0
html-tools@1.0.0
htmljs@1.0.0
http@1.0.3
id-map@1.0.0
iron:core@0.3.2
iron:dynamic-template@0.3.0
iron:layout@0.3.0
iron:router@0.9.1
jquery@1.0.0
json@1.0.0
less@1.0.6
livedata@1.0.7
localstorage@1.0.0
logging@1.0.2
meteor@1.0.2
minifiers@1.0.2
minimongo@1.0.1
mongo-livedata@1.0.3
mrt:jquery-jcrop@0.0.3
natestrauser:select2@3.4.6
npm-bcrypt@0.7.7
oauth2@1.0.0
oauth@1.0.0
observe-sequence@1.0.1
ordered-dict@1.0.0
package-stats-opt-out@1.0.0
random@1.0.0
reactive-dict@1.0.0
reload@1.0.0
retry@1.0.0
routepolicy@1.0.0
service-configuration@1.0.0
session@1.0.0
sha@1.0.0
spacebars-compiler@1.0.1
spacebars@1.0.0
srp@1.0.0
standard-app-packages@1.0.0
templating@1.0.4
ui@1.0.0
underscore@1.0.0
webapp@1.0.2
```

To fix it i can manually force it by specifying the package:

```
$ meteor update natestrauser:select2
Refreshing package metadata. This may take a moment.
  downloading natestrauser:select2 at version 3.4.7 ...  done
  upgraded natestrauser:select2 from version 3.4.6 to version 3.4.7
$
```

On this positive side this is the 2500th issue, a nice whole round number :)

**Comment by glasser** [comment]
I think these bugs have been fixed.  (Hard to check without a reproduction.)

**Comment by bilalahmed70** [comment]
I am experiencing the same issue what @Tarang specified. I had to remove and add packages to get updated. Meteor version is 1.1.0.2

**Comment by glasser** [comment]
@bilalahmed70 Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

**Comment by ErikAbele** [comment]
Same here, this issue is still around! Here are the steps to reproduce it:

1) create example app via `meteor create test-2500`
2) create package via `cd test-2500` ; `mkdir -p packages/test_pkg`
3) add a file named package.js to the directory created in 2) with the following contents
    Package.describe({ name: "test:pkg", version: "0.0.1-dev" });
    Package.onUse(function(api) { api.use('meteorhacks:kadira@2.20.0'); });
4) add package via `meteor add test:pkg`
5) Meteor will now install 'meteorhacks:kadira' @ 2.20.*
6) now change your package.js file to use 'meteorhacks:kadira@2.0.0' (note the change in the minor version!)
7) run `meteor update`

This yields "Your packages are at their latest compatible versions." whereas one would expect to get an upgrade to the latest meteorhacks:kadira@2.*.* package which is already at 2.23.3…

The only work-around seems to be to run:

`meteor update meteorhacks:kadira` which in turn successfully upgrades to 2.23.3:

"meteorhacks:kadira  upgraded from 2.20.6 to 2.23.3"

I hope this helps – let me know if you need further details...

**Comment by JWo1F** [comment]
I have the same issue

**Comment by scott-cornwell** [comment]
Similar issue still happening. Was trying to use manuel:viewmodel with Meteor 1.4, thought it was incompatible. Turns out even with starting a new Meteor 1.4 project and doing `meteor add manuel:viewmodel` it put me at version 1.9.12, whereas the newest version is 6.0.0. `meteor update manuel:viewmodel` didn't work. Luckily I was able to work around by doing `meteor add manuel:viewmodel@6.0.0` and it seems to work fine with Meteor 1.4!

**Comment by Mklueh** [comment]
Still happening, any news?

**Comment by afriC84** [comment]
Wish it was. I came from meteor 1.5 and upgraded to 1.6 (now running 1.6.0.1).
After running `meteor update --all-packages`, this is what I see:
```
This project is already at Meteor 1.6.0.1, the latest release.
                                              
Changes to your project's package version selections from updating package versions:
                                              
coffeescript           downgraded from 1.12.7_3 to 1.12.6_1
coffeescript-compiler  removed from your project

                                              
The following top-level dependencies were not updated to the very latest version available:
 * dynamic-import 0.2.1 (0.3.0 is available)  
 * ecmascript 0.9.0 (0.10.0 is available)     
 * es5-shim 4.6.15 (4.7.1 is available)       
 * meteor-base 1.2.0 (1.3.0 is available)     
 * mfpierre:chartist-js 1.6.0 (1.7.1 is available)
 * mongo 1.3.1 (1.4.2 is available)           
 * softwarerero:accounts-t9n 1.3.11 (2.0.4 is available)
 * standard-minifier-css 1.3.5 (1.4.0 is available)
 * standard-minifier-js 2.2.3 (2.3.1 is available)
                                              
Newer versions of the following indirect dependencies are available:
 * autoupdate 1.3.12 (1.4.0 is available)     
 * babel-compiler 6.24.7 (7.0.0 is available) 
 * babel-runtime 1.1.1 (1.2.0 is available)   
 * boilerplate-generator 1.3.1 (1.4.0 is available)
 * callback-hook 1.0.10 (1.1.0 is available)  
 * check 1.2.5 (1.3.0 is available)           
 * coffeescript 1.12.6_1 (2.0.3_4 is available)
 * ddp-client 2.2.0 (2.3.1 is available)      
 * ddp-common 1.3.0 (1.4.0 is available)      
 * ddp-server 2.1.1 (2.1.2 is available)      
 * diff-sequence 1.0.7 (1.1.0 is available)   
 * ecmascript-runtime-client 0.5.0 (0.6.0 is available)
 * http 1.3.0 (1.4.0 is available)            
 * id-map 1.0.9 (1.1.0 is available)          
 * minifier-css 1.2.16 (1.3.0 is available)   
 * minifier-js 2.2.2 (2.3.1 is available)     
 * ordered-dict 1.0.9 (1.1.0 is available)    
 * random 1.0.10 (1.1.0 is available)         
 * reload 1.1.11 (1.2.0 is available)         
 * retry 1.0.9 (1.1.0 is available)           
 * url 1.1.0 (1.2.0 is available)             
 * webapp 1.4.0 (1.5.0 is available)          
These versions may not be compatible with your project.
To update one or more of these packages to their latest
compatible versions, pass their names to `meteor update`,
or just run `meteor update --all-packages`.
```
What should I do? That's a lot packages left...

**Comment by benjamn** [comment]
@afriC84 The real answer here is to run `meteor update --release 1.6.1`, since the newer versions of most of those packages become available with Meteor 1.6.1.
