### ISSUE TITLE
Support Node 0.12

### ISSUE THREAD

**Issue by Tarang** [meteor/meteor#3666]
Building works via `meteor build`, but when coming up to running an app:

Looks like the `npm-bcrypt` package is causing a couple of problems, no binary build maybe?

```
[Error: Module did not self-register.]
js-bson: Failed to load c++ bson extension, using pure JS version

/Volumes/App/application/programs/server/node_modules/fibers/future.js:245
						throw(ex);
						      ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (/Volumes/App/application/programs/server/npm/npm-bcrypt/node_modules/bcrypt/node_modules/bindings/bindings.js:74:15)
    at Object.<anonymous> (/Volumes/App/application/programs/server/npm/npm-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```

**Comment by jadsonlourenco** [comment]
I had a similar problem with this when I was compiling on OSX and then hosted on Linux server, so I added this tag to compile correctly for use on the server platform:
```
meteor build --architecture os.linux.x86_64
```

**Comment by glasser** [comment]
Thanks.  We haven't started on the work to support Node 0.12 (and/or io.js) yet (0.12.0 just was released last week).  Since it's an ABI change, that probably means you'll need new versions of all your C++ modules.  Might require adding a small feature to Isobuild to allow the version solver to choose versions based on ABI, or to allow multiple builds of the same version for the same architecture, or something.

**Comment by wmodes** [comment]
Workaround for now?

**Comment by Tarang** [comment]
This should be working now. Meteor 1.0.4 (i think) uses Node 12. I gave it a go rebuilding it and it seemed fine this time. I also copied the node binary included in meteor's directory to `npm install` and run the app.

**Comment by wmodes** [comment]
Running Meteor 1.0.5 locally on OSX (just fully updated)
Building with --architecture os.linux.x86_64
Deploying to Ubuntu Ubuntu 14.04.2 LTS x86_64 (just updated)
Running nodejs v0.12.1 (just built)
Serving app with nginx v1.4.0 

And still getting: 

    /home/secrethistory/bundle/programs/server/node_modules/fibers/future.js:245
                                                throw(ex);
                                                      ^
    Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (/home/secrethistory/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/node_modules/bindings/bindings.js:74:15)
    at Object.<anonymous> (/home/secrethistory/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)

Any tips or places to look next?

**Comment by glasser** [comment]
@Tarang Actually, we have not started bundling Node 0.12 with Meteor yet (or formally testing/QAing it).

There are ABI changes between 0.10 and 0.12, which we will have to address, as I mentioned above.

**Comment by Tarang** [comment]
@glasser you're kidding? Somehow my `node` bundled with meteor is 0.12. I'm not too sure why this is. Now that i've cleaned up and reinstalled its not that way anymore.

My issue with this remains then. My issue was slightly different because the same platform causes the issue. I `meteor build` on OS X on an OS X developed app then run `node main.js` on OS X to get the same error above.

**Comment by glasser** [comment]
Right, that's why this is an open issue :)

**Comment by wmodes** [comment]
A workaround for this problem was suggested here:  http://stackoverflow.com/questions/29340510/bcrypt-is-breaking-my-meteor-application-how-do-i-fix-it/29347616

**Comment by paralin** [comment]
Is there any way to force the meteor tool to use Node v0.12, regardless of any instabilities?

**Comment by wmodes** [comment]
@paralin, I assume you are talking about locally? If you have node v0.12.x installed, your app will use it, and that is where some of the incompatibilities come from.

**Comment by paralin** [comment]
@wmodes I mean in the meteor tool. I have v0.12.2 installed, but Meteor is using an older version.

**Comment by Tarang** [comment]
@paralin To 'force' it replace the `node` binary in the `meteor-tool` package with newest binary.

You can find this in `~/.meteor/packages/meteor-tool/$VERSION/$PLATFORM/dev_bundle/bin/node`

The quickest way to figure out the exact directory is to follow the symlink at `~/.meteor/meteor`

Follow the symlink at ~/.meteor/meteor` which matches up to  `~/.meteor/packages/meteor-tool/$VERSION/$PLATFORM/meteor`.

**Comment by ArjunRajJain** [comment]
So I have an Elastic Beanstalk Instance set up with Node Version 0.12, but I'm getting the following error: 
/home/secrethistory/bundle/programs/server/node_modules/fibers/future.js:245
                                            throw(ex);
                                                  ^
Error: Module did not self-register.

Is there a way for me to tell Meteor 1.1 to use Node 0.12.

**Comment by glasser** [comment]
Anyone is welcome to follow @Tarang 's directions, but you should be aware that you're then running the tool in an entirely untested and unsupported configuration.  I certainly hope that if you choose to make this change and file issues in this issue tracker that you make it incredibly clear that you've made this modification to the tool so that we can appropriately prioritize investigating to your issue.

**Comment by mohoff** [comment]
Is there any ETA on when Node 0.12 is officially supported by Meteor?

**Comment by jhuenges** [comment]
I am also interested in an ETA. Any updates?

**Comment by unbornchikken** [comment]
I think there is no good reason to use 0.12.x instead of io.js. With io.js we get almost full ES6 support (on the server), and v8 4+. Fibers already works with io.js 1.8.1. I can think of two other platforms that bundles node: nw.js and Atom Shell, and they are using io.js too.

**Comment by bmustata** [comment]
I have similar issues on Ubuntu Ubuntu 14.04.2:

```
node -v v0.12.3
npm -v 2.9.1
meteor --version Meteor 1.1.0.2  
```

**Comment by lukeadams** [comment]
Kind of old news, but [the io.js team recently joined the Node team](https://github.com/nodejs/io.js/issues/1664#issuecomment-101828384) to create the Node foundation.
I think we should wait for their first release and go from there, no?
[Here](https://github.com/nodejs/dev-policy/blob/master/convergence.md) is a (draft) plan for the transition.

**Comment by unbornchikken** [comment]
Yeah, awesome news indeed! By my opinion, this can wait. Now, the real question is if there will be generators supported, and even ES7 async/await is in the horizon, still hold the decision that was fibers the right choice? Fibers has the benefit that asynchronous code seems exactly like synchronous, but that often leads confusion, and will never be consistent with client code.

**Comment by justin-umesh** [comment]
Hi all, I am also facing the issue.. Help plz. 
bundle/programs/server/node_modules/fibers/future.js:245
						throw(ex);
						      ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (/sManage/builds/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/node_modules/bindings/bindings.js:74:15)
    at Object.<anonymous> (/sManage/builds/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)

**Comment by Oizor** [comment]
After fixing the bcrypt error following the post in the thread from @wmodes, I now stumble upon this error:

```
Error: Invalid listen argument: 8080
    at Server.listen (net.js:1245:15)
    at Object.main (packages/webapp/webapp_server.js:745:1)
    at /opt/repo/ROOT/programs/server/boot.js:255:27
```

Running at v0.12.2. The default Meteor application build runs without problems at the same server (with the same settings). Does anyone have a clue if this issue is related to the usage of running with v0.12.2, or should I look elsewhere. I did check the argument given to the listen method, it does have the value 80 and is of type number.

**Comment by kentonv** [comment]
Sandstorm.io [shipped our automatic HTTPS certificate provisioning today](https://blog.sandstorm.io/news/2015-10-01-free-ssl-certificates.html), but unfortunately users won't get forward secrecy for now since it's not supported by Node 0.10.x. Hoping Meteor gains compatibility with newer Node releases soon!

**Comment by MaxPleaner** [comment]
not sure why, but I got this future.js error when trying to install `collection2`. I realize that Node 0.12 is untested, and my `node --version` and `sudo node --version` both show 0.12. However, I am able to avoid the error by using sudo when installing collection2. Not sure why.

**Comment by laosb** [comment]
Related to #5124 , closing this one.
