### ISSUE TITLE
Android simulator doesn't work since Meteor 1.0.4

### ISSUE THREAD

**Issue by tobiaswaltl** [meteor/meteor#3989]
When entering "meteor run android" the simulator will only show a white page. In the browser everything is ok.
This problem doesn't occur with projects where I haven't updated Meteor yet.

My OS:
Ubuntu 14.04

Reproduction recipe:
- create a new meteor app ("meteor create test") and go to the app directory
- "meteor add-platform android"
- "meteor run android"

Here's the stack trace:
=> App running at: http://localhost:3000/
I20150321-19:00:15.219(1) (android:cordova.js:927) Uncaught Error: Error calling method on NPObject.
I20150321-19:00:19.277(1) (android:cordova.js:1169) deviceready has not fired after 5 seconds.
I20150321-19:00:19.283(1) (android:cordova.js:1162) Channel not fired: onCordovaReady
I20150321-19:00:19.299(1) (android:cordova.js:1162) Channel not fired: onFileSystemPathsReady
I20150321-19:00:19.318(1) (android:cordova.js:1162) Channel not fired: onCordovaInfoReady

**Comment by tobiaswaltl** [comment]
As a temporary workaround this downgrade will work again:
meteor run android --release 1.0.3.1

**Comment by glasser** [comment]
Hmm, this was a known issue with early RCs of 1.0.4 but I thought we fixed it.

**Comment by spinningarrow** [comment]
I'm seeing this too - just installed Meteor 1.0.5.

Could it have anything to do with running the emulator inside a virtual machine?

**Comment by CyberStrike** [comment]
just started going through the todo tutorial and got this myself.

**Comment by Slava** [comment]
I don't get this issue on Meteor 1.1 or the head of `devel` branch. I am on Mac OS X.

This bug does not have a reproduction, so I'm closing it. If anyone is able to come up a way to consistently reproduce it, we can reopen it.

**Comment by tobiaswaltl** [comment]
Hi,

I've just tried it again (Meteor 1.1.0.2) and I'm still getting this issue.
What I've written in the reproduction recipe is really everything you have to do. I.e. there's no specific code necessary - the boilerplate created with "meteor create" is sufficient to reproduce this issue.

As your are on Mac OS X it might be OS dependent (I'm on an Ubuntu 14.04 VM). Therefore it would be great to reopen this issue again and to reproduce it on a (virtual?) Ubuntu system.

If there's still something missing in the reproduction recipe please tell me what information exactly is missing and I'll add it.

Thanks!

**Comment by Slava** [comment]
I am going to reopen but I have to note that we tested Android on an Ubuntu VM when we released 1.0.4 and we fixed a similar issue. Would need to retest again for the next release.

**Comment by abhisheksoni27** [comment]
I am running Ubuntu 14.04 inside VirtualBox on Windows and this is the error: 


I20150616-12:10:26.091(-4) (android:cordova.js:927) Uncaught Error: Error calling method on NPObject.
I20150616-12:10:28.579(-4) (android:cordova.js:1169) deviceready has not fired after 5 seconds.
I20150616-12:10:28.581(-4) (android:cordova.js:1162) Channel not fired: onCordovaReady
I20150616-12:10:28.582(-4) (android:cordova.js:1162) Channel not fired: onFileSystemPathsReady
I20150616-12:10:28.584(-4) (android:cordova.js:1162) Channel not fired: onCordovaInfoReady

**Comment by mvol** [comment]
Exactly the same problem here - also running Ubuntu 14.04 inside VirtualBox und Windows

**Comment by ddaydd** [comment]
Same, Ubuntu 14.04 (not VM), METEOR@1.1.0.2
no solution?

**Comment by shanshuo0918** [comment]
I'm running on Mac OS X, have the same issue.
Any solutions?

**Comment by porta8080** [comment]
Same problem here folks

**Comment by JanAhrend** [comment]
I have the same issue. Running Max OS X. 
Downgrading didn't work for me (e.g. meteor run android --release 1.0.3.1)

**Comment by magbicaleman** [comment]
This still seems to be an issue on Mac OS : Meteor 1.1.0.3
