### ISSUE TITLE
"meteor mongo" doesn't work on METEOR@1.1.0.1

### ISSUE THREAD

**Issue by delgermurun** [meteor/meteor#4115]
After upgrading from `1.1` to `1.1.0.1`, `meteor mongo` doesn't work. Here is command output:
```
mongo: Meteor isn't running a local MongoDB server.

This command only works while Meteor is running your application locally. Start your application first. (This error will also occur if you asked Meteor to use a
different MongoDB server with $MONGO_URL when you ran your application.)

If you're trying to connect to the database of an app you deployed with 'meteor deploy', specify your site's name with this command.
```

Obviously I started application locally. 

Backward to `1.1`, it works.

OS: Ubuntu 14.10 64-bit

**Comment by scamianbas** [comment]
Same issue here.

**Comment by hamoid** [comment]
Same on Arch Linux. But ```mongo --port 3001``` does work.
I downgraded to 1.1 and ```meteor mongo``` was still not working.

**Comment by scamianbas** [comment]
Downgrade to 1.1 doesn't work here as well.
Ubuntu 14.04 64b

**Comment by hasiya** [comment]
who can we contact about this? Im currently working on my Honours project.. I really need this..

**Comment by hamoid** [comment]
@hasiya As I mentioned, you can install mongodb and use that to connect. Not ideal, but works.

**Comment by hamoid** [comment]
Aren't there tests that prevent this kind of issues getting released?

**Comment by glasser** [comment]
Due to a mistake with git during the preparation of 1.1, some code that was not intended to go into 1.1 (and did not go into 1.1!) was accidentally placed onto `master` in git.  So 1.1.0.1 was accidentally prepared with that additional change.  Unfortunately, while there is a test of this exact issue that was added as part of the change, the same git mistake didn't add the new test.

Folks who are having issues: can you tell me what `pgrep -lf mongod` prints?

**Comment by scamianbas** [comment]
@glasser 
pgrep is hashed (/usr/bin/pgrep)
0
1008 mongod
0

**Comment by delgermurun** [comment]
@glasser 
```
pgrep is /usr/bin/pgrep
0
1141 mongod
18509 mongod
0
```

**Comment by hamoid** [comment]
pgrep is /usr/bin/pgrep
    0
    7961 mongod
    0

(I had to put the code in a bash script, because by default I run fishshell)

**Comment by glasser** [comment]
OK, thanks.  Looks like in addition to the differences between `pgrep` implementations on Mac and Linux, there are multiple Linux versions, and they changed the implementation in 2012 according to http://serverfault.com/questions/77162/how-to-get-pgrep-to-display-full-process-info

> Since 3.3.4 (released in 2012), pgrep -a (--list-full) shows the full command line
> ...
> In older versions ... pgrep -fl matched the pattern against full command line and showed the full command line.

Ah, and here's the change: https://gitorious.org/procps/procps/commit/f12277c74d591245767d77badb6bb6af91335656

Sorry. This usually would have been caught during the RC stage or QA, but we do less QA on releases that are intended to only contain a single tiny change.

**Comment by delgermurun** [comment]
@glasser I forgive you :). You are doing great job.

**Comment by stubailo** [comment]
@hasiya you might be able to use `meteor shell` instead of `meteor mongo` for doing stuff with the database.

**Comment by glasser** [comment]
I've fixed the underlying bug on devel, and @stubailo is putting out a 1.1.0.2 that doesn't have the relevant change (which was never intended to be in 1.1.0.2 in the first place).

**Comment by diegoalberto** [comment]
Waiting for 1.1.0.2

**Comment by glasser** [comment]
@stubailo What happened to the 1.1.0.2 release process?  I see that the release exists but has not yet been marked as recommended.

**Comment by skagedal** [comment]
Got the fix, works great!

**Comment by delgermurun** [comment]
Thank you.

**Comment by etangreal** [comment]
Hi, I'm getting this "Unexpected mongo exit code 1. Restarting." 
Runtime:
    - Ubuntu 14.04 (running on my mac bia vagrant & virtualbox) 
    - meteor version 1.1.0.2

To be more precise:
   - vagrant init phusion/ubuntu-14.04-amd64
   - vagrant up
   - vagrant ssh
   - (install meteor ...)
   - meteor create test
   - cd test
   - meteor

after which I get this "Unexpected mongo exit code 1. Restarting." 
Have been searching - but not much to go on ...

**Comment by stefanve** [comment]
I also get this error with Ubuntu 14.04 LTS and meteor 1.1.0.2
It worked at first start, but after a reboot I get the error

**Comment by stubailo** [comment]
@etangreal - there is a problem with running Mongo on shared file systems like Vagrant. Here are some directions I found on Google about moving the db out of the shared folder: https://gist.github.com/gabrielhpugliese/5855677

**Comment by stubailo** [comment]
@stefanve are you also in vagrant? Can you provide more details?

**Comment by stefanve** [comment]
Well, I don't know... :) I use a Hetzner EX40SSD, default install Ubuntu 14.04 64-bit minimal. 
I installed meteor and git stuff from command line, so I just did minimal changes to the default install
https://www.hetzner.de/en/hosting/produkte_rootserver/ex40ssd

Seems like 14.04 is a common denominator though?
https://github.com/meteor/meteor/issues/4019

**Comment by stefanve** [comment]
It is not possible to do a reset either:
home/stefan/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:278
						throw(ex);
						      ^
Error: EACCES, unlink '/home/appname/.meteor/local/build-garbage-os0e3h/README'

**Comment by stubailo** [comment]
oh @stefanve did you create an app somewhere where you don't have delete permissions? try creating the app in your personal home directory rather than `/home/appname`.

**Comment by stefanve** [comment]
Sorry, deleted part of the path. It is in my home, /home/myname/appname

**Comment by stefanve** [comment]
Update on my issue: Vagrant was not involved. The server had two mirrored SSD disks. I uninstalled Meteor according to official instructions, removed my project and reinstalled from scratch after doing all the official 14.04 updates. Still did not work.
I then deployed the app properly with meteor-up and all went well. 
So my immediate problem is solved, but the "Unexpected mongo exit code 1. Restarting."   is still a mystery.

**Comment by nickgio** [comment]
I am still having the same issue with 1.1.0.2 - running Meteor locally, but still getting the same error:

```
mongo: Meteor isn't running a local MongoDB server.

This command only works while Meteor is running your application
locally. Start your application first. (This error will also occur if
you asked Meteor to use a different MongoDB server with $MONGO_URL
when you ran your application.)

If you're trying to connect to the database of an app you deployed
with 'meteor deploy', specify your site's name with this command.
```

**Comment by glasser** [comment]
Can we keep the discussion of "Unexpected mongo exit code 1. Restarting" on #4019?  I'm not sure why it started here, after a completely unrelated bug was solved and closed.

**Comment by spradnyesh** [comment]
i'm still facing the issue w/ 
- meteor 1.2.1
- mongo 2.4.14
on debian testing
