### ISSUE TITLE
Indirect dependencies with no version constraints choose oldest major/minor version

### ISSUE THREAD

**Issue by chmac** [meteor/meteor#4170]
**_2 Upvotes**_ Don't ask me how I found this out, or how many hours we wasted trying to figure out why our tests were failing, but I finally got to the bottom of it after I actually read the error messages! :-)

I created a very simple [example project](/chmac/meteor-versiontest) and [demo script](/chmac/meteor-versiontest/blob/master/demo.sh) to show the problem.
### Details

If I create a package and say `api.use('aldeed:collection2')` then I will get version `0.1.7` installed. But if I say `meteor add aldeed:collection2` I will get version `2.3.3` installed.

Normally, this isn't a problem, because my app explicitly requires the package, and so only the current version is made available. However, when I run `meteor test-packages`, only the `0.1.7` version is loaded, and then my code fails to run (some APIs have changed).
### Workaround

My work around is fairly simple, I can explicitly require a version. However, I need to manually increment the version every time, as specifying `@2.0.0` installs `2.0.1` not `2.3.3` as per #3282. So I use `api.use('aldeed:collection2@2.3.3')` and the correct version is loaded.

I don't think this is quite the same as #3282 so I created a new ticket, but feel free to merge if it is. I also tested with a git checkout of `devel` and I get the same behaviour.

**Comment by glasser** [comment]
I believe this is technically working as intended.  If you look at https://github.com/meteor/meteor/blob/devel/packages/constraint-solver/solver.js#L818-L820 you'll see that newly added packages which are indirect dependencies of your app use the mode `GRAVITY_WITH_PATCHES`, which prefers older major/minor versions (but newer patch versions).

This doesn't affect you that much if the direct dependency (eg `chmac:versiontest`) is a published Atmosphere package (which are required to declare some constraint for their dependencies).

I don't really understand why this choice was made, exactly.  I mean, I sort of get it — the idea is that these are packages that you as an app author don't care much about because you didn't mention them yourselves, just some package you use mentioned it.  And the version listed in the package's package.js is likely to be the version it was tested with, so it minimizes the chances that your app will break because some package you've never heard of had a new version with a possibly breaking change.

So that supports `@2.0.0` giving you `2.0.1` rather than `2.3.3`: your dependency's author has not necessarily ever heard of `2.3.x`, so let's be conservative and give you something close to what was requested.  (And it should be the case that `@2.3.0` is good enough to get you `2.3.3`, which I think is pretty reasonable.)

But I don't think that should imply that if there are NO version constraints on a package (which again, doesn't happen if the direct dependency was published), that we should still take the oldest major/minor version rather than the newest.  Seems to me that no constraints at all should leave you in the wild and crazy position of getting the newest thing available.

@dgreensp what do you think?  And is it easy for the solver code to differentiate between "new indirect dependency with at least one version constraint" and "new indirect dependency with no version constraints anywhere"?

**Comment by glasser** [comment]
See also #4165, which claims that we have docs that say newest versions are chosen.

**Comment by cmnjcs** [comment]
I suppose [the docs](http://docs.meteor.com/#/full/pack_use) don't explicitly state that the latest version is chosen, but it is certainly strongly suggested:

> In general, you must specify a package's version (e.g., 'accounts@1.0.0' to use version 1.0.0 **or a higher compatible** version (ex: 1.0.1, 1.5.0, etc.) of the accounts package).

(bolding mine)

**Comment by chmac** [comment]
That's the challenge. I read the docs and understood that `1.0.0` was equivalent of the latest version in the `1.*.*` series. It looks like it's actually the latest version in the `1.0.*` series. I'd guess a documentation change makes sense, and personally, I'd favour a change to the logic, but that's a decision above my expertise.

Can I specify that I want the latest version `1.*.*` somehow?

**Comment by glasser** [comment]
Well, there's two different things going on.

One is: what do these constraints mean, as far as what is the total set of allowed versions that match?  `@2.3.5` means "any version compatible with `2.3.5`", ie, anything that's at least as new as 2.3.5, but older than 3.0.0.  Any such version is an allowable result of the constraint solver.

The other part is: Given multiple possible solutions, all of which satisfy all of the constraints that are available across the entire project, which should we choose?  Which is the "best" of different "correct" matches?  Meteor has a [somewhat complex definition](https://github.com/meteor/meteor/blob/d956f0976f8189d42467ec757ddf0e7030bca54e/packages/constraint-solver/solver.js#L695-L822) and one of the choice we've made is that if a package author (who is probably not the person running the app) wrote `foo@2.3.5`, and nothing else in the project has any opinions about `foo`, then we're going to be conservative and prefer to stick with the 2.3.x series rather than jumping to 2.500.900 for a package that the app author has never heard of.

If your reaction as an app author is "wait, I do have strong opinions about what versions should be chosen... stronger than the only constraint written in my package", then well, you can add another constraint to your app (ie `meteor add foo@2.500.400`) and now that will be respected.

That said, I don't think we should be applying this "conservative" rule in cases where *no* version numbers have been mentioned anywhere.  Waiting to hear @dgreensp 's opinion when he gets back from vacation!

**Comment by dgreensp** [comment]
@glasser, I thought the rule was that if a local package is nested in an app, the package is built using the versions from the app's `.meteor/versions`?  That doesn't seem to be happening here.  Maybe that rule only applies to publishing, and test-packages is different because it basically creates a fresh project.

Ignoring `test-packages` for the moment, the intended workflow for adding a local package and then updating an indirect dependency is to type:

```
meteor add chmac:versiontest
meteor update aldeed:collection2
```

This will record in your app's `.meteor/versions` that you are using version 2.3.3 of `aldeed:collection2`.  If you ever want to take a newer version, just run the same `meteor update` command again.  This version number is intended to be very sticky.  It will only be changed if you add some other package to your app that requires a different version, and it will only be downgraded as a last resort (if there's literally no other way to avoid a conflict).

The main bug here may be that `meteor test-packages` should be respecting the `.meteor/versions` of the parent app and just using the version listed there.

For published packages, the story is a little different.  Now there is a question of what version of your package's dependencies another developer will get when they install your package.  You are required to specify a version constraint of some kind.  In general, the role of a constraint isn't so much to drive the choice of version as it is to constrain it and ban cases where an incompatibility is expected.  If a user of your package has a good reason to upgrade the minor version of a dependency, they can (by typing `meteor update` in the app), and if there's a *really* good reason that applies to everyone, you can put out a patch release of your package that bumps the minor version of a dependency.

It's common in package systems to be conservative about using versions of a package's dependencies besides the ones the package was tested with.  If you develop a package that uses something called XMLParser 1.2 under the hood, and the author of XMLParser releases XMLParser 1.3, that doesn't mean that the next time someone creates an app and adds your package, they should get XMLParser 1.3.  It's a subtle point, but the bottom line is that I think it's ok for a package to have to explicitly ask for new minor versions of its dependencies (bigger isn't always better), and it's nice if the experience that users of a published package have is somewhat uniform (i.e. you don't have some users of your package reporting bugs that only occur in conjunction with XMLParser 1.3, which you haven't gotten around to trying yet).

We'll never have a "use the latest version available at runtime" directive, because that breaks reproducible builds.  The way to say "use the latest" is to run `meteor update`, or for a published package to put the latest version in `api.use`.  For local packages in an app, they use the app's `.meteor/versions`, and for local packages not in an app, there is a `.versions` file.

@glasser, can we make `test-packages` respect versions files if it doesn't, so that it runs reproducibly?

There is also something to be said for not using the very very oldest version if there is NO constraint, and perhaps using the latest version instead.  However, that just turns "oldest version available at runtime" to "newest version available at runtime."  If we don't fix test-packages, tests might run against a newer version of the package than your app uses!  (Which would admittedly be less annoying and more likely to be close to what you want.)

**Comment by glasser** [comment]
@dgreensp I'm not sure where you're getting `test-packages` from here? The example given in this issue is using the case where you have a local package in your app (ie, unpublished and thus not required to have constraints on all of its dependencies) which has an unconstrained dependency.  There's no relevant `.meteor/versions` entry, because you're just adding the subpackage for the first time.

I mean, I'll believe that there's also a `test-packages` issue, but I'm currently just focusing on the simpler case of "there are no constraints anywhere and you're just adding a package".

**Comment by glasser** [comment]
Er, OK, I think you're right that `test-packages` ignoring the current app's constraints and previous versions (it runs in a temporary project app) is also a bug, but I think it has a separate fix than the thing I'm talking about.

**Comment by dgreensp** [comment]
> I'm not sure where you're getting test-packages from here

The original report is that the app worked but test-packages didn't.  The demo repo shows some behavior that may be surprising to some, unrelated to test-packages, but then concludes that the behavior is not a problem until test-packages gets involved.  I think we can agree there are two different issues here, but I didn't pull this one out of thin air. :)

I don't think the "pure" version of the problem you're talking about -- you add a local package to an app, both of which you wrote without specifying a version of `foo` anywhere, and get an unexpectedly old version of `foo` -- really bites people that hard, because the computer isn't doing something directly at odds with what you asked for, there's a paper trail in `.meteor/versions`, and there's a one-time fix of specifying the version you want somewhere (either in the app, by running `meteor update`, or in the package).  (I agree we should fix it; see below.)  In contrast, the test-packages case is unexpected and unexplainable, with no paper trail or one-time fix, with the obvious work-around being to put the correct version number of `foo` in two places, raising the question of how to keep them in sync.  I've found that issue threads where someone starts out saying "I'm getting a wrong, old version of an indirect dependency, why can't I just always get the latest?" usually amount to a bug where we aren't honoring the previous selected version (e.g. #3282 and #3653) but are instead inappropriately picking a version number from scratch, and I think that turned out to be the case here too.

All that said, we should change the behavior that results in picking v0.1.7 in the demo attached to the original report.  I wonder if we should ban unconstrained `api.use` more aggressively, i.e. even in local packages?  If you think a good fix is to have a `new_indirect_unconstrained` category of package that gets optimized in `MODE_UPDATE`, I'm open to that, but I probably need a nudge of reassurance that it's a principled solution.

Note that even if we made that change, a similar bug report could still have been filed, except the report would be that the app was using `foo 2.0` and test-packages was breaking because it was using `foo 3.0`.  That's why I think the test-packages part is important.

**Comment by chmac** [comment]
FWIW, @dgreensp I agree with your point about the version constraints expressed by packages. It makes sense to be conservative, and reproducible builds are a huge win.

There's really 3 issues going on here.

## Documentation confusion

Yes, there are really two separate things going on here. First, the documentation is a little misleading suggesting that a version constraint `2.0.0` allows `2.*.*` but it actually allows `2.0.*`. Personally, I think that makes sense, but the docs are misleading. I submitted a pull request to change the docs. #4225 I hope I got the right place. I think that covers this issue.

## Version confusion with `test-packages`

The second thing, and the one that really bit me in the ass, is the fact that `test-packages` picks a totally different version than `meteor run`. I'd imagine one issue here is that packages can be tested outside of a meteor application directory. Is that true? I haven't tested, but if so, then there may not always be a `.meteor/versions` file to rely on. Then, you break the reproducible builds paradigm by relying on it if it exists, and not otherwise. Then the tests may pass or fail depending on where I run them.

Maybe the better solution is to complain loudly when there's no explicit version specified?

It's not perfect, but I understand that explicit versions in a package make sense. We're building our whole app in packages, so I don't actually have to maintain version numbers in 2 places. In my case, the problem arose because I started with a boilerplate. The boilerplate added a few packages which I then re-added in my packages. If I had started with a clean meteor install, I'd have gotten version `0.1.7` all the time.

## Picking the oldest version by default

Currently, if no version is explicitly specified, the oldest version gets picked. That's probably never a good idea. If you decide that explicitly choosing a version is a requirement, then this issue goes away. But if not, I think it will always make sense to pick the latest version instead of the oldest. Assuming no version was specified, you have 2 choices, oldest or newest. `meteor add foo` adds the newest. I think it makes sense to do likewise in `package-tests`.

With this approach, tests might break when a new package version is released. That makes more sense to me anyway. If a new version is released, and my tests start breaking, I have to take some kind of action. I can either downgrade the package, problem solved, or fix the issues.

**Comment by dgreensp** [comment]
@chmac, sounds good to me.  I commented on your docs PR to say that I don't agree with this exact change, but I will make that section clearer.

There is a provision for packages outside of an application directory, which is to use a file called `.versions`, which is supposed to be exactly like `.meteor/versions` -- you check it into your repo and it keeps the state for reproducible runs.

As for the hard error, at the moment, it feels like overkill to me, but I wonder if we should print more about what's going in cases like this.  For example, it's not exactly the same thing, but maybe whenever we select a version for a package from scratch (not just when you run `meteor add` or `meteor update`) we should print a message saying what we picked.  In that world, the current `meteor test-packages` in this case would print a big list of versions that aren't actually the right ones, which would be a giveaway since it should probably always be respecting some versions file or another.

**Comment by chmac** [comment]
@dgreensp Sure thing. Wasn't sure if the PR was the way to go, but figured it was more helpful to offer the change than just talk about it! :-)

I think printing versions would help, but I'd say warning people when no version constraint is supplied is more useful. I probably wouldn't have noticed the issue if there was a long list of packages + versions. I'd have ignored it. But if it had said something like "We're picking the oldest version of xyz package because no version was specified in package.js, we recommend you do that, as per [link to docs]", then even if I ignored it, I'd have had no reason to complain afterwards! :-)

**Comment by mitar** [comment]
I was also just bitten by the fact that if one does not specify a package version, the oldest one is picked. It seems that is happening on meteorpad as well. (Try adding `peerlibrary:blaze-components` there and it will add 0.1.0 version instead of latest 0.7.0.)

**Comment by offthegrass** [comment]
+1 for a warning. I want the last 24 hours back.

**Comment by dgreensp** [comment]
@mitar that is not what happens when you `meteor add` on the command-line.  I've reported this on a MeteorPad bug thread: https://github.com/rissem/meteorpad/issues/16

@offthegrass, sorry about that!

Coming up with a fix to this situation is now on my front burner.

**Comment by dgreensp** [comment]
I wrote a hackpad about this topic: https://meteor.hackpad.com/Packaging-UX-Gravity-Hurts-FoTnLTVUklt

Currently planning to address the "totally unconstrained package" case and the test-packages case, essentially as discussed here.

**Comment by laosb** [comment]
+1 here. Also cause the problem that **can't update a package when it was added both by `meteor add` and `package.js` in a package.**

**Comment by offthegrass** [comment]
@laosb are you specifying the version? e.g. `api.use('my:package@2.1.1')`

**Comment by laosb** [comment]
@offthegrass I haven't specified a version; but some package authors did. So I think, Meteor should use the latest version for default, and package authors should be aware with backwards compatibility.

**Comment by offthegrass** [comment]
Idea:

1. When publishing: 
 - package authors write a short changelog
 - package authors can __flag__ an update as containing major / breaking changes

2. When running `meteor update`, package users see the changelog for each package in the terminal (similar to how users see a package description when using `meteor add`)

3. If a package has been __flagged__, users have a choice about whether to approve the update (similar to bower, I think). _Could there also be a 'test' option at this point?_

**Comment by chmac** [comment]
Changelogs in the console is an interesting idea. Some package authors will do better jobs than others, so they'll be of mixed quality.

The semver spec defines how breaking changes should be communicated by version numbers, so we already have that information (assuming packages use semver) without the need for an additional flag.

**Comment by laosb** [comment]
@offthegrass Good idea. But things could be better. You know, even with a major version update, the API can be backwards-compatible. So if there is a breaking change, just email all the packages authors whose package depends on that packge. Since package users may don't know a lot about the internals of packages, these problems should be solved by package authors. However, if a top dependence package has breaking changes, we should notify the package user.

**Comment by offthegrass** [comment]
@laosb 

I don't think I was clear:

By ___user___ I mean ___package author using a package inside their package via api.use___. 

>  just email all the packages authors whose package depends on that packge 

Yeah, the changelog could be automatically sent their meteor dev emails as soon as the update is pushed. Obviously this would be in addition to options like _confirm_, _deny_, _test_ or _decide later_ in the terminal.

**Comment by mitar** [comment]
I think I also found one other possible issue with current system. Semver defines:

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

It seems that Meteor does not handle `0.*` versions specially at all. I have seen it upgrade version from 0.6.0 to 0.7.0 automatically (and things broke, because APIs were not compatible, because it is not yet stabilized). The same goes for the other direction. Choosing 0.1.0 instead the latest 0.7.0 probably breaks an app which was build against 0.7.0 because 0.1.0 is not really compatible. Semver allows that. And for a good reason. It allows one to have some time to develop a stable API before it is frozen.

**Comment by dgreensp** [comment]
@mitar, that's correct, we don't do anything special with 0.x versions.  I don't understand the second part of your example, because we will never give 0.1.0 to a package or app that asks for 0.7.0.  We also don't "automatically upgrade", though we will upgrade if you type `meteor update`.  We made `meteor update` reluctant to upgrade top-level dependencies to incompatible versions, but that feature is brand-new and I'm not sure anyone asked for it, I just implemented it. :)

That said, you are right, if semver's rules for 0.x are intended to make 0.5.0 and 0.6.0 incompatible, we could honor that by, for example, refuse to run if one package requires foo@0.5.0 and another requires foo@0.6.0, rather than running with 0.6.0 as we do now.  Or maybe we could print a warning.  My impression (which could be wrong) is that people wouldn't want strict rules about 0.x packages.  You can always pin to an exact version if you want, but there's a large use case where you just want to follow the latest version, even if things are breaking all the time.  Like the early days of npm.

**Comment by rfox90** [comment]
Does anyone have anyway of automating this?

I'm ok manually incrementing my package versions once they are present but getting them present is another matter :(

I don't want to have to manually retrieve version numbers for all of my packages.

**Comment by dandv** [comment]
Was also bitten by this but fortunately spent only ~1 hour debugging the cause. Minimal reproduction at https://github.com/dandv/meteor-bug-semver-aldeed-collection2

Actually, the version of aldeed:collection2 chosen, 0.1.7 isn't the oldest (that would be 0.1.0).

Also, there's a fatal error when picking this version:

> The package aldeed:collection2 at 0.1.7 is incompatible with Meteor 0.9.0 or later.

This is likely to become a more and more common occurrence as Meteor breaks backwards compatibility with old constructs.

**Comment by hwillson** [comment]
Hi all - the originally reported issue does still occur with the most recent version of Meteor (1.5.1 as of today). The logic behind which version of an indirect unconstrained dependency gets selected hasn't changed (it's still the oldest version possible). Given the pros/cons of altering this approach, the current implementation still seems to make the most sense however (the analysis outlined in https://meteor.hackpad.com/Packaging-UX-Gravity-Hurts-FoTnLTVUklt is still quite valid). 

Over the past 2 years Meteor has added a few extra tools that help make it easier to notice and fix the original problem outlined in this issue:

1. The `meteor update` command output now includes a section that mentions when indirect dependencies have available updates, along with the current version installed and the latest version available (changes introduced in https://github.com/meteor/meteor/commit/b0273ad010f4de407e47b011940bc2042182ef48).

2. To help make it easier to update all packages at once, including indirect dependencies, `meteor update` now supports an `--all-packages` flag (changes introduced in https://github.com/meteor/meteor/commit/0693c84d8744e2e50df243d5708ae3bac67ad569).

3. The next Meteor 1.5.x release (likely 1.5.2) will introduce a new utility (`meteor list --tree [--weak]`) for listing all application dependencies, including indirect dependencies (changes introduced in https://github.com/meteor/meteor/pull/8913/commits/96db56b0bae5168fa852eead7cbf0131a12c0ec8).

Outside of the above changes which help mitigate this issue, Meteor has also added ES2015 module support. The packages-for-everything approach that used to be quite popular has significantly decreased in usage. Applications are now being created with very few local packages, which means adding constraints to dependencies in those local packages is easier to manage.

Given that there are currently no plans to change how indirect unconstrained dependencies are resolved, and that there are now fairly straightforward ways to find out which package version is being used (including indirect dependencies), I'll close this issue. I'm happy to re-open this issue if anyone disagrees with this decision, but please keep in mind that a future [full transition to npm](https://github.com/meteor/meteor/blob/devel/Roadmap.md#full-transition-to-npm) is still being considered, which means core package version solver changes like this are not a priority.
