### ISSUE TITLE
Add an offline installer for Windows

### ISSUE THREAD

**Issue by TamarAmit** [meteor/meteor#4589]
Hey guys,
A couple of weeks ago, the full installer download file was changed to a minimal installer that requires an open internet connection while it runs.
I already know about a few users that really love this platform and are developing meteor based applications in an offline environment (with no direct connection to the internet).
It would be great if you could add an extra link to a full version of the installer (wherever you think it's appropriate, also not on the main meteor download page).
It will save each of us the time required to diff and merge those files and create a full meteor folder each time a new version is released.

Thanks alot in advanced!

**Comment by laosb** [comment]
Second that.

**Comment by inbaldoron** [comment]
I also use the offline installation. It's an important feature

**Comment by stubailo** [comment]
Hi!

We made the decision to change to an installer that automatically downloads the newest version for a couple reasons:

1. Most people probably want the newest version
2. This way we don't need to re-build the installer for every new release, which is a complex process that involves code-signing with a physical key

To alleviate some of the issues with the switch, we have published alternate install directions which will let you pre-download an archive and then unpack it without needing internet access (allowing you to distribute Meteor on a flash drive or similar)

See the directions here: https://github.com/meteor/meteor/wiki/Meteor-on-Windows:-Alternate-installation

Does this solution work for you?

**Comment by TamarAmit** [comment]
Thanks a lot Sashko!
It sounds great :)

**Comment by Shaunakde** [comment]
The online installer has some issues on Windows 10, esp if a previous install of meteor existed. I am following your alternate install instructions and will let you know if that worked.

**Comment by stubailo** [comment]
Interesting, we should investigate.

However, what is the use case for using the installer twice on the same machine? You can simply update with `meteor update` rather than running the installer again.

**Comment by susenmaharjan** [comment]
Online installer always gets stuck and has no use in a country with slow Internet like Nepal. I've tried like 50 times but still unable to install it! Need standalone installer asap!

**Comment by stubailo** [comment]
Have you tried this method? https://github.com/meteor/meteor/issues/4589#issuecomment-113599055

**Comment by ehsangifani** [comment]
Online installer gets stuck, doesn't work, is very slow (using only 10% of download speed capability.)
How can I download from github-windows.s3.amazonaws.com directly?

--using win 10 x64 home

**Comment by cpmpub** [comment]
How to install Github for Windows without an internet connection? Direct link install offline setup
https://cpmpub.com

**Comment by abernix** [comment]
@cpmpub This is not the GitHub for Windows project.

**Comment by vipinkumarpsr** [comment]
Guys u may visit to my blog I have myself made this offline desktop  github latest application for windows . And dnt forget to comment about ur experience. in blog.  thank you 😊


https://makeiteg.blogspot.in/2016/11/how-to-download-github-desktop.html?m=1
