### ISSUE TITLE
Improve Hot Code Push on mobile by moving functionality into native code

### ISSUE THREAD

**Issue by martijnwalraven** [meteor/meteor#4722]
Hot Code Push on mobile has some performance and reliability issues that I think we can fix by moving functionality into native code. In particular, Hot Code Push of faulty code should no longer require a reinstall of the app.

This should also help fix issues like https://github.com/meteor/meteor/issues/4038.

**Comment by Igor1201** [comment]
This and #4723 will surely make Meteor mobile development faster and much more stable. Certainly will fix most of the annoyances we've been through. Count me in on any tests that will need to be done!

**Comment by MoeBadr** [comment]
I would love to see this issue resolved, I have spent many many hours on this issue. 
I'm also happy to test. 

Thanks for addressing the issue :+1:

**Comment by Tim-W** [comment]
+1

I'd be happy to test this.

**Comment by chriswessels** [comment]
+1. This is an important issue for us, as is #4723. Happy to test.

**Comment by woniesong92** [comment]
+1. This is so important.

**Comment by woniesong92** [comment]
Until this is fixed, here's a workaround. Instead of running `meteor run ios-device` everytime you change your code, do the following.

1. `meteor run ios-device --mobile-server myapp.meteor.com`
2. make some changes
3. `meteor deploy myapp.meteor.com`

Then your running app is automatically updated, not broken at all.

**Comment by MoeBadr** [comment]
@woniesong92  I'm currently using `build`: 
 meteor build --server xx --architecture os.linux.x86_64 build

I haven't been able to find workaround

**Comment by sorenpeterson** [comment]
When I build for the mobile version I use `meteor build --server=http://0.0.0.0/`

Obviously this breaks the hot code push but it is better than a broken application.

`0.0.0.0` is safe (I'm pretty sure) because it is specifically for the purpose of designating and invalid target. 

Source: https://en.wikipedia.org/wiki/0.0.0.0

**Comment by markoshust** [comment]
This doesn't help, because you still need to delete/rebuild the app to test new changes. This defeats a lot to the purpose of rapid development and testing.

**Comment by woniesong92** [comment]
@markoshust Do you still have to rebuild the app if you do it the way I described above?

**Comment by MoeBadr** [comment]
@woniesong92 in order to deploy a new version you need to build again.

**Comment by woniesong92** [comment]
@MoeBadr Right, but you don't have to delete the app, install it and run it again, right?

**Comment by MoeBadr** [comment]
@woniesong92 if the app breaks due to this issue (#4038), then you do need to reinstall or clear all app data in order to use the app.

**Comment by derwaldgeist** [comment]
This bug is really annoying and makes me feel very unsure if the Cordova integration is really "ready for prime-time". As described in #4924, in my app I have the problem that even "clean code" pushed by the hot push mechanism sometimes leave the app in an unusable state, where only a re-install can solve the problem.

Is there any work-around available, even if it means to disable the hot push functionality for apps? I tried out mdg:reload-on-resume, but this did not work at all - it even made my app more unstable, as described in https://github.com/meteor/mobile-packages/issues/72.

Would it be safe to just uninstall the autoupdate package until these problems have been fixed, or would this result in other unwanted side-effects? I'm feeling a bit uncomfortable deactivating a standard core package without any info if this is even possible.

**Comment by jirimusil** [comment]
Hi, having similar problem, although hcp do not crash my app often, it makes first start of the app taking 20+ secs with half of the time with blank screen which i think is really not the sort of experience you want to give to the fresh new user.

I'm able to avoid next updates after this first one by using Meteor._reload.migrate returning [false] as described somewhere but it does not help too much in real world since most of users do not accept tens of seconds long app load time (native app loads 2secs, meteor about 10 secs with splash is still ok but white screen of deatch for next ten secs present the app as crashed even if its not really true).

I also tried to remove autoupdate with no success, also tried to rewrite Autoupdate object tu false

**Comment by markoshust** [comment]
@jirimusil your 20 sec lag sounds reminiscent of hosting a dev site at xxx.meteor.com -- is that where it is hosted? that is the dev meteor site going to sleep after usage. you'll get much better db/response times by switching to a better host, that is really only meant for dev.

**Comment by derwaldgeist** [comment]
My app also takes a lot of time to load, about 9-10 secs plus a hot code push if the server side has changed, which may pretty well sum up to approx. 20 secs, which is inacceptable, if you ask me. I'm running a local server, and the app is pretty small. This huge delay is one of the reasons why I am now following a hybrid approach (use native screens for the first pages and switch over to the web app later).

**Comment by pors** [comment]
+1

**Comment by dnish** [comment]
That fix should be important. After 5-10 hot-code updates my whole app crashes and I need to reinstall it again via Play Store. That's too bad for user experience.

**Comment by ijpiantanida** [comment]
+1

**Comment by Tim-W** [comment]
@derwaldgeist are you using crosswalk?

**Comment by markoshust** [comment]
Has anyone experienced crash problems when implementing <a href="https://github.com/meteor/mobile-packages/blob/master/packages/mdg:reload-on-resume/README.md" target="_blank">`reload-on-resume`</a>, and using `Reload.isWaitingForResume()` with `window.location.reload()`?

When implementing this combo (and also adding a pretty "app updating" screen that is much needed), I haven't had a crash yet. This may be a solid workaround, but doesn't close out this ticket.

**Comment by dnish** [comment]
@markoshust I've tried it, but I still get user complaints that the app only shows a blank screen, so it still crashes. We deploy our app with <code>mup deploy</code> and also use <code>meteor-cluster</code>. There is a moment where the app isn't working anymore when we deploy it  to the servers, could be possible that this maybe causes the crash on the devices of currently active users.

**Comment by derwaldgeist** [comment]
@markoshust In my app, the ```reload-on-resume``` package did not show any effect at all. The HCR still took place.

**Comment by derwaldgeist** [comment]
@Tim-W No, I'm not using Crosswalk yet. Reason is that I'm still on Meteor 1.1 (mainly because I'm waiting for the re-worked mobile HCR, but also because 1.2 caused too many incompatibilities with packages). I know that you can integrate Crosswalk in 1.1 as well, but I wanted to wait for the official support in 1.2.

**Comment by dnish** [comment]
@derwaldgeist We use <code>reload-on-resume</code>, but also disable the hot code push on startup:

    if(Meteor.isCordova)
    {
        Meteor._reload.onMigrate(function() {
            return [false];
        });

    }

In our case, the app reloads the new code in background. The user will see the new version, when the app get's killed and he has to open it again. Main problem: <code>reload-on-resume</code> also fires, when your app pauses / goes into background. So if the user opens the app after a minute again, he'll get a full hot code reload - that's a behavior we didn't want. With the function above, we've disabled this behavior.

BTW: We are using Crosswalk on Android, so I don't know if this will work for you.

**Comment by derwaldgeist** [comment]
Thanks for that tip. I was indeed missing this code. Will try it!

**Comment by Exilz** [comment]
I can confirm @dnish 's answer is the way to go. That's how I do it too, until a new version of HCP is released.

**Comment by markoshust** [comment]
I like @dnish's setup. In my case, I want the user to have a new code update on app reload, so I'm leaving that code out.

Just adding `reload-on-resume` seems to completely fix this crashing issue. @dnish I've noticed that when changing or deploying to a new server, I get a blank page, regardless of if `reload-on-resume` is installed or not. You said you were using `cluster`, which represents a similar situation where your client could be hitting a different server. I believe this issue may be tied to loading the app where the user is logged in, but hitting a different server? This is an issue, however this could perhaps be solved with additional router/redirection logic, as it may just be an issue with that and not the actual hardware. I'll look deeper at this as things should still work when starting a new session and the user still being logged in. We might have to manually trigger a refresh in those scenarios.

@derwaldgeist The `reload-on-resume` package should disable code refresh, but only on Cordova. Perhaps you were testing in browser?

Here's how I'm handling my refresh. I want it triggered whenever the home page is hit. The `loading` path shows a loading template while the app update occurs so the user just doesn't see an odd 'blink`/refresh.

```
Tracker.autorun(function() {
  FlowRouter.watchPathChange();
  var currentContext = FlowRouter.current();

  if (Reload.isWaitingForResume() && currentContext.route.name == "home") {
    FlowRouter.go("loading");

    window.location.href = currentContext.route.path;
  }
});
```

**Comment by derwaldgeist** [comment]
No, I tried it in a Cordova app, but it did not have any effect. The reloads still happened each time I updated the code.

**Comment by caioreis** [comment]
@markoshust, great job. But how do you know that the updated finished and the user can go back?

**Comment by markoshust** [comment]
The `window.location.href` is what updates the code (really just a page refresh). I wanted to add a `loading` screen, so I redirected the user there first. The `currentContext` above is how I get the "current" url (before sent to loading screen), so I know which route to load after the refresh.

**Comment by akshaylive** [comment]
Hey Martijn, I saw that you are working on these issues on multiple related issues. Any updates on this?

**Comment by guilhermedecampo** [comment]
Would like to know also @martijnwalraven, if you have any update on these issues :+1:

**Comment by Exilz** [comment]
Yup, can't wait to see what you'll come up with ! @guilhermedecampo @martijnwalraven

**Comment by martijnwalraven** [comment]
No updates, still working on it, but this will be in Meteor 1.3.

**Comment by akshaylive** [comment]
Thanks for the confirmation. Lemme know if I can review your branch and
contribute!

**Comment by derwaldgeist** [comment]
And I hoped it would be an minor update for 1.2, so I could finally upgrade to this version. :-) Anyway, thanks for the update. Good to hear you're still working on it.

**Comment by guilhermedecampo** [comment]
Awesome to hear from you @martijnwalraven =)

**Comment by dotnetwise** [comment]
+1

**Comment by martijnwalraven** [comment]
This has been fixed in Meteor 1.3! A new beta is now available, please give it a try: https://github.com/meteor/meteor/issues/6266.

**Comment by cpalanzo** [comment]
Okay - so now this is ONLY going to work in Meteor 1.3! Great - but I've wasted time trying to implement "reload-on-resume" for iOS - until I did this research.

You really **SHOULD** update both Atmosphere AND Github - to be clear that this package is NOT supported in 1.2.

**Comment by martijnwalraven** [comment]
@cpalanzo: Although hot code push has been much improved in Meteor 1.3, `reload-on-resume` should definitely work with earlier releases.

**Comment by dotnetwise** [comment]
But will the `Android` version of `hot-code-push` be supported `natively` in `1.3`?

**Comment by cpalanzo** [comment]
It does not appear to. I installed and ran with a locally attached ios-device. Code pushes just continue to happen on update and I put Reload.isWaitingForResume() into a help to pop-up a message - it never triggers. (of course I could be doing something wrong)

**Comment by martijnwalraven** [comment]
@dotnetwise: Yes, hot code push uses a rewritten native plugin for both iOS and Android.

@cpalanzo: I'm not sure what could be wrong in your case. Anything else you can mention about your setup? Other packages or plugins you use maybe?

**Comment by cpalanzo** [comment]
I pulled it out - but I'll look again this weekend.
My initial implementation was very simple -added a conditional Div
{{#if NewCode}}
---> ask user to restart
{{/if}}

Put helper - which I expect to be reactive.
NewCode: function(){
return Reload.isWaitingForResume():
}

meteor ios-device etc....

**Comment by cpalanzo** [comment]
Okay - What I did was very simple I think - please see screen capture below - but understand, I'm still learning so there may be something really basic that is incorrect, like variable use!

- I have a complex project, and have had professional development help as you can see

- I added your Cordova package as you can see in the lower terminal window

- in my top level client template, called "appLayout.html" I use conditional spacebars to check the result of my help function, which I expect to be a boolean #if newCode.  If True I create a simple DIV with a notice that NEW Code is waiting.

- in my associated Javascript file - right pane - I add the appropriate helper function to return newCode. I believe it is returned as a boolean? And that my conditional in spacebars will interpret the value correctly?

- I expect that anytime I change code anywhere in the project that would require a push to the client newCode will be True and hence the div will be presented.

- I did not explicitly check for Cordova in the spacebars test - but I guess I could do that so the div will only test and show if running in an app 

- Then I simply did meteor run ios-device --settings settings. json to start the code, open XCODE and download to my attached iPhone. 

- After the initial download to my phone the app executes. I then CHANGE a file anywhere in the project - when the client reloads it pushes to my phone - the DIV never appears.

![screen shot 2016-03-13 at 4 34 02 pm](https://cloud.githubusercontent.com/assets/9503630/13731180/700e0996-e939-11e5-9ba4-496a45884190.png)
