### ISSUE TITLE
Meteor 1.3.1 startup warning

### ISSUE THREAD

**Issue by joetidee** [meteor/meteor#6762]
***4 Upvotes*** I upgraded to 1.3.1 and received these errors when running my Meteor app:

```
W20160409-00:34:16.556(0)? (STDERR) WARNING: npm peer requirements not installed:
W20160409-00:34:16.561(0)? (STDERR)  - react@0.14.8 installed, react@15.x needed
W20160409-00:34:16.562(0)? (STDERR)  - react-addons-pure-render-mixin@0.14.8 installed, react-addons-pure-render-mixin@15.x needed
W20160409-00:34:16.562(0)? (STDERR)
W20160409-00:34:16.563(0)? (STDERR) Read more about installing npm peer dependencies:
W20160409-00:34:16.563(0)? (STDERR)   http://guide.meteor.com/using-packages.html#peer-npm-dependencies
W20160409-00:34:16.563(0)? (STDERR)
```

I could not upgrade to the react 15.0.0 package because if I do, this throws the following errors:

```
npm ERR! peerinvalid The package react@15.0.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-addons-create-fragment@0.14.8 wants react@^0.14.8
npm ERR! peerinvalid Peer react-addons-css-transition-group@0.14.8 wants react@^0.14.8
npm ERR! peerinvalid Peer react-addons-linked-state-mixin@0.14.8 wants react@^0.14.8
npm ERR! peerinvalid Peer react-addons-perf@0.14.8 wants react@^0.14.8
npm ERR! peerinvalid Peer react-addons-pure-render-mixin@0.14.8 wants react@^0.14.8
npm ERR! peerinvalid Peer react-addons-test-utils@0.14.8 wants react@^0.14.8
npm ERR! peerinvalid Peer react-addons-transition-group@0.14.8 wants react@^0.14.8
npm ERR! peerinvalid Peer react-addons-update@0.14.8 wants react@^0.14.8
npm ERR! peerinvalid Peer react-data-components@0.6.0 wants react@^0.14.1
npm ERR! peerinvalid Peer react-dom@15.0.0 wants react@^15.0.0
npm ERR! peerinvalid Peer redbox-react@1.2.2 wants react@>=0.13.2 || ^0.14.0-rc1
```

**Comment by hobartwang** [comment]
I've had the same problem. It may be result in meteor-react-data,I think.

**Comment by capensisma** [comment]
@joetidee @hobartwang downgrade bros 
`meteor update --release 1.3`

and that's all for today ;)

**Comment by hobartwang** [comment]
@capensisma 
Thank you for your help,but it doesn't work.As follow:
meteor update --release 1.3
....
app: updated to Meteor 1.3.
➜  app git:(master) ✗ meteor
[[[[[ ~/Documents/app ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Meteor 1.3.1 is available. Update this project with 'meteor update'.
W20160410-11:35:39.069(8)? (STDERR) WARNING: npm peer requirements not installed:
W20160410-11:35:39.070(8)? (STDERR)  - react@0.14.8 installed, react@15.x needed
W20160410-11:35:39.070(8)? (STDERR)  - react-addons-pure-render-mixin@0.14.8 installed, react-addons-pure-render-mixin@15.x needed
W20160410-11:35:39.070(8)? (STDERR)
W20160410-11:35:39.070(8)? (STDERR) Read more about installing npm peer dependencies:
W20160410-11:35:39.070(8)? (STDERR)   http://guide.meteor.com/using-packages.html#peer-npm-dependencies
W20160410-11:35:39.070(8)? (STDERR)
=> Started your app.

=> App running at: http://localhost:3000/

**Comment by ziarno7** [comment]
if you want to downgrade, you might have to reset all the package versions to the state before you upgraded to 1.3.1 - for me, I just reverted the files `packages`, `versions` and `release` and works fine after downgrading to 1.3. 

Other than that, I have the same problem with 1.3.1 :P

**Comment by joetidee** [comment]
I have the same errors as hobartwang, perhaps Meteor could look at factoring in some reversion logic in a future release?

**Comment by sarkistlt** [comment]
+1

**Comment by fortunto2** [comment]
+1

**Comment by chetmurphy** [comment]
+1

Meteor 1.3.1 is available. Update this project with 'meteor update'.
W20160412-06:10:23.901(-7)? (STDERR) WARNING: npm peer requirements not installed:
W20160412-06:10:23.902(-7)? (STDERR)  - react@0.14.8 installed, react@15.x needed
W20160412-06:10:23.902(-7)? (STDERR)  - react-addons-pure-render-mixin@0.14.8 installed, react-addons-pure-render-mixin@15.x needed
W20160412-06:10:23.902(-7)? (STDERR)
W20160412-06:10:23.904(-7)? (STDERR) Read more about installing npm peer dependencies:
W20160412-06:10:23.905(-7)? (STDERR)   http://guide.meteor.com/using-packages.html#peer-npm-dependencies
W20160412-06:10:23.905(-7)? (STDERR)

Node dependencies remind me of DDL hell. I have tried meteor 1.31, and react 15, but I can't seem to find the sweet spot. I've also reinstalled node-modules multiple times.

**Comment by capensisma** [comment]
+1

**Comment by capensisma** [comment]
+2

**Comment by chetmurphy** [comment]
Success. Fingers crossed. YMMV.

I've update meteor to 1.3.2-rc.5 (1.3.2 should be out by tomorrow). I then removed react 0.14.8 and installed react 15.0.1 and its dependents. No errors at this point. Finally, I installed material-ui 0.15.0-alpha.2, but this does generate peer dependencies on react 0.14.0 add react 0.14.8. 

Based on the assumption that material-ui 0.15.0-alpha.2 should work with react 15.0.1. I then manually edited the package.json files in node_modules and set the react dependencies to 15.0.1. The errors are now gone. I realize that this assumption may not be accurate, but so far meteor is running without warnings or errors. And even node and npm are happy.

**Comment by hobartwang** [comment]
Warning in 1.3 too.

**Comment by mbools** [comment]
Same here. Issue remains even after updating meteor to 1.3.2-rc.6 so started removing and reinstalling meteor packages. Turned out to be `kadira:react-layout` causing the problem in my project.

**Comment by capensisma** [comment]
:+1:

**Comment by ljack** [comment]
I think the issue appeared after running `meteor update` which caused `react-meteor-data  upgraded from 0.2.7 to 0.2.9`. This is after I started to see the issue, maybe it's just warning or downgrade `react-meteor-data`.

**Comment by ciwolsey** [comment]
I'm pretty sure this isn't a bug, it's just that react-meteor-data now wants you to install react 15.x
```
npm install react@^15.x.x --save
```
should fix this.

**Comment by hobartwang** [comment]
The warning is gone AFTER I install the material-ui-v0.15.0.beta.1.
Other package also use the latest version.

**Comment by capensisma** [comment]
Meteor 1.3.2: Improvements to deploying binary npm packages,
importing stylesheets from node_modules, and more:
https://github.com/meteor/meteor/blob/master/History.md#v132

`meteor update`

**Comment by eliezedeck** [comment]
I now just updated to 1.3.2.2 (thru successful `meteor update`) and I still get:

```
=> Started proxy.                             
=> Started MongoDB.                           
W20160419-09:35:31.283(3)? (STDERR) WARNING: npm peer requirements not installed:
W20160419-09:35:31.283(3)? (STDERR)  - react@15.0.1 installed, react@0.14.x needed
W20160419-09:35:31.284(3)? (STDERR)  - react-dom@15.0.1 installed, react-dom@0.14.x needed
W20160419-09:35:31.284(3)? (STDERR)  - react-addons-transition-group@15.0.1 installed, react-addons-transition-group@0.14.x needed
W20160419-09:35:31.284(3)? (STDERR)  - react-addons-css-transition-group@15.0.1 installed, react-addons-css-transition-group@0.14.x needed
W20160419-09:35:31.284(3)? (STDERR)  - react-addons-linked-state-mixin@15.0.1 installed, react-addons-linked-state-mixin@0.14.x needed
W20160419-09:35:31.284(3)? (STDERR)  - react-addons-create-fragment@15.0.1 installed, react-addons-create-fragment@0.14.x needed
W20160419-09:35:31.284(3)? (STDERR)  - react-addons-update@15.0.1 installed, react-addons-update@0.14.x needed
W20160419-09:35:31.284(3)? (STDERR)  - react-addons-pure-render-mixin@15.0.1 installed, react-addons-pure-render-mixin@0.14.x needed
W20160419-09:35:31.284(3)? (STDERR)  - react-addons-test-utils@15.0.1 installed, react-addons-test-utils@0.14.x needed
W20160419-09:35:31.284(3)? (STDERR)  - react-addons-perf@15.0.1 installed, react-addons-perf@0.14.x needed
W20160419-09:35:31.285(3)? (STDERR)           
W20160419-09:35:31.285(3)? (STDERR) Read more about installing npm peer dependencies:
W20160419-09:35:31.285(3)? (STDERR)   http://guide.meteor.com/using-packages.html#peer-npm-dependencies
W20160419-09:35:31.285(3)? (STDERR)           
=> Started your app.                          
                                              
=> App running at: http://localhost:3000/
```

I just want to note, that the application is working absolutely fine even with these warnings. Nevertheless, it's quite an annoying thing to have these pop-up in both the Web and actual Command-line console.

How do we satisfy this thing so it won't display this **harmless** warnings?

**Comment by chetmurphy** [comment]
Try reinstalling node-modules. If your package.json is up to date then delete the contents of your node_modules folder and run npm install. Otherwise, delete the contents of your node_modules folder and run npm install <packages>.

**Comment by capensisma** [comment]
Hey guys, the real issue isn't coming from Meteor itself but from you packages you are using!

```
npm peer requirements not installed:
W20160419-09:35:31.283(3)? (STDERR)  - react@15.0.1 installed, react@0.14.x needed
```


Which mean that one of you npm packages need and rely on react@0.14.x (which is an old version now)

You can make some changes to package.json and see what's wrong...

**Comment by ChenLi0830** [comment]
I can confirm the solution of @capensisma worked for me. 
Here is my previous error log 
```
npm ERR! Darwin 15.4.0
npm ERR! argv "node" "/Users/Chen/.meteor/packages/meteor-tool/.1.3.2_4.ht2fd6++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm" "install" "--save" "meteor-node-stubs"
npm ERR! node v0.10.43
npm ERR! npm  v2.14.22
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react@15.0.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer material-ui@0.15.0-beta.1 wants react@^15.0.0
npm ERR! peerinvalid Peer react-addons-pure-render-mixin@15.0.1 wants react@^15.0.1
npm ERR! peerinvalid Peer react-bootstrap@0.28.5 wants react@>=0.14.0
npm ERR! peerinvalid Peer react-dom@15.0.1 wants react@^15.0.1
npm ERR! peerinvalid Peer react-intl@2.1.0 wants react@^0.14.0 || ^15.0.0-0
npm ERR! peerinvalid Peer react-tap-event-plugin@1.0.0 wants react@^15.0.0-0
npm ERR! peerinvalid Peer reflux@0.3.1 wants react@>=0.12.2 <0.15.0
```
As can be seen reflux requires 'react@>=0.12.2 <0.15.0', so I updated the version of reflux and now the error is gone!

**Comment by preexo** [comment]
1.3.2.3 actually has solved all the issues for me automatically.

**Comment by mwdavisii** [comment]
Chetmurphy's comment for worked for me. I deleted node_modules from the project directory and re-added one a time. No more messages.
METEOR@1.3.2.4 
react@15.0.2

**Comment by iamrudra** [comment]
Following @preexo I did a `meteor update` and it solved the issues.

**Comment by abernix** [comment]
A combination of using the latest Meteor 1.3.2.4 and the correct version NPM dependencies in your package should resolve this.

If you're still having problems, as others have said above, make sure your `package.json` is up to date with it's dependencies (you should be fine if you are using `--save`/`--save-dev` when installing new packages), remove your `node_modules` directory, and run `meteor npm install` to refresh everything.

Closing this, but if anyone is still having a problem, please open a new issue with a reproduction repository per [the guidelines for reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug).

**Comment by jagi** [comment]
If anyone is still having this problem the solution can be removing the `kadira:react-layout` package which probably requires older version of react.

**Comment by pgmvva** [comment]
following command fixed the issue for me:
meteor npm update
