### ISSUE TITLE
Feature request: import `.scss` and other types of files within javascript files.

### ISSUE THREAD

**Issue by AlexFrazer** [meteor/meteor#6798]
Take the following "component"

```
├── list
│   ├── index.js
│   ├── list.js
│   ├── list.scss
│   └── list.jade
```

One inconsistency I have found is that, in order to include the `list` and its styles, it would instead require two files: a .scss file to import the scss, and a js file to include the js.

It would be far more intuitive to do the following within the `list.js` or `index.js`:

```
// list.js
import {FlowRouter} from "meteor/kadira:flow-router";

import "./list.jade";
import "./list.scss";

// ... component stuff here.
```

**Comment by lyquocnam** [comment]
this may use webpack:webpack package, but in this time, webpack have issue can not deploy production.

**Comment by benjamn** [comment]
This already works! That is, if the files are inside an `imports` directory. The key is that the `.scss` and `.jade` file have to be *lazy*; otherwise, they'll go into the combined CSS bundle in the `<head>`, and importing them from a JS module won't have any additional effect.

**Comment by lyquocnam** [comment]
dear, @benjamn !
as you said we can import less, sass, css file from javascript (js) file mr @benjamn  ?
if it right, i tried like this:

`import '/imports/client/style.less';`

and this message on console client:

`Uncaught Error: Cannot find module '/imports/client/style.less'`

i sure it right path to style.less file. and i added package meteor too.
import less package too.
`import 'meteor/less';`

this is bug or my missing ?

**Comment by AlexFrazer** [comment]
^ Same with mine, it WILL work with css, just not scss or less.

**Comment by benjamn** [comment]
Had a [discussion](https://github.com/meteor/meteor/commit/cd8bc10b1d7be519d43ec92c612e738ca091a311) with @sebakerckhof about why this was happening, and what to do about it. I think this is fixed in `1.3.2-rc.6` for `less`, and will be fixed in `fourseven:scss` the next time it's released.

**Comment by sebakerckhof** [comment]
FYI, this is now fixed in fourseven:scss (version 3.4.3)

**Comment by exah** [comment]
Doesn't work with stylus files.
install.js:78 Uncaught Error: Cannot find module '/imports/components/Button/Button.styl'

**Comment by lfilho** [comment]
I'm having this issue with `.less` files too. With `.css` works.
I'm running last version as of this writing: 1.3.2.4 (just runned a `meteor update` before writing here).

If just renaming it to have a `.css` extension then it works again.

I even tried `rm -rf .meteor/local/build && meteor` to no luck.
Other relevant versions: `less@2.6.0, flemay:less-autoprefixer@1.2.0` (all last versions as of this writing too)

**Comment by lfilho** [comment]
Passing by to say that I'm still having this issue, updated versions:
```
meteor 1.3.4.1
flemay:less-autoprefixer@1.2.0
less@2.6.3_1
```
My simple test:

- Add a `test.less` to `imports/startup/client/css/` with the following content: `body { background: red }`
- Imported it via a js file like so: `import './css/test.less'`
- App reloads. Nothing changed.
- Rename file `test.less` to `test.css` and update the import line above
- App reloads. Background is now red.

I'm also using the semantic-ui package but I presume it has nothing to do with this.

**Comment by lfilho** [comment]
Can we reopen this, @benjamn ?

**Comment by abernix** [comment]
@lfilho I don't believe this issue warrants re-opening at this time.

`.css` imports will work **in client-side Meteor code** without additional packages.  However, because the use of a pre-processor becomes necessary when using `.less`,  `.styl`, etc. a plugin is necessary for these:

Make sure you use the appropriate Meteor core pre-processor for the type of file that you're importing:
* `meteor add less` (for `.less` files)
* `meteor add stylus` (for `.styl` files)

If you're using different packages than these core packages, those will need to be recently updated versions which work properly Meteor 1.3+.  I'm not sure that `flemay:less-autoprefixer` (a third-party plugin) meets this criteria as it appears it's last release was over 8 months ago (before 1.3).

I _believe_ the recommended option to achieve the same functionality as `flemay:less-autoprefixer` (though I'm not intimately familiar with it) is to use `less` (core) + [`juliancwirko:postcss`](https://github.com/juliancwirko/meteor-postcss).

**Comment by lfilho** [comment]
@abernix Hey, thanks for your reply. If you read my previous message you'll see that I already have the packages you mentioned: core `less@2.6.3_1`. Do you think `flemay:less-autoprefixer` is causing the issue? I don't think so...

**Comment by abernix** [comment]
> Do you think flemay:less-autoprefixer is causing the issue? I don't think so...

Yes, that's exactly what I meant.  It hasn't been updated since Meteor 1.3 was released and there have been very important changes in the plugin/compiler framework.

Plus, your reproduction steps work perfectly when `flemay:less-autoprefixer` is removed. :wink:

**Comment by lfilho** [comment]
Thanks, @abernix I pinged @flemay in there to see if there's any plan on his side. Otherwise I'll try using your postcss + plugins approach. 
Thanks again
