### ISSUE TITLE
[1.4] Cannot find lib-sass bindings

### ISSUE THREAD

**Issue by clayne11** [meteor/meteor#7390]
I'm not sure if this is the same issue as #7297 but I'm having trouble with the `lib-sass` bindings as well with this package.

I ran `meteor npm install` to install `node-sass` but it didn't help.

Cross-referencing from https://github.com/nathantreid/meteor-css-modules/issues/55

```
➜  casalova-web git:(meteor-1.4) meteor update --release 1.4-beta.9
=> Errors while initializing project:

While building package casalova:aleo:
error: No plugin known to handle file 'aleo.scss'. If you want this file to be a static asset, use addAssets instead of addFiles; eg,
api.addAssets('aleo.scss', 'client').

While loading plugin `mss` from package `nathantreid:css-modules`:

/Users/clayne/.meteor/packages/nathantreid_css-modules/.1.2.0.12x0xqc++os.osx.x86_64+web.browser+web.cordova/plugin.mss.os.osx.x86_64/npm/node_modules/meteor/mss/node_modules/node-sass/lib/extensions.js:158:11:
The `libsass` binding was not found in
/Users/clayne/.meteor/packages/nathantreid_css-modules/.1.2.0.12x0xqc++os.osx.x86_64+web.browser+web.cordova/plugin.mss.os.osx.x86_64/npm/node_modules/meteor/mss/node_modules/node-sass/vendor/darwin-x64-46/binding.node
This usually happens because your node version has changed.
Run `npm rebuild node-sass` to build the binding for your current node version.
at Object.sass.getBinaryPath
(/Users/clayne/.meteor/packages/nathantreid_css-modules/.1.2.0.12x0xqc++os.osx.x86_64+web.browser+web.cordova/plugin.mss.os.osx.x86_64/npm/node_modules/meteor/mss/node_modules/node-sass/lib/extensions.js:158:11)
at Object.<anonymous>
(/Users/clayne/.meteor/packages/nathantreid_css-modules/.1.2.0.12x0xqc++os.osx.x86_64+web.browser+web.cordova/plugin.mss.os.osx.x86_64/npm/node_modules/meteor/mss/node_modules/node-sass/lib/index.js:16:36)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Module.Mp.load
(/Users/clayne/.meteor/packages/meteor-tool/.1.4.0-beta.9.nkjjk++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/reify/node/runtime.js:16:23)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at npmRequire (/tools/isobuild/bundler.js:1642:14)
at Module.npmRequire.useNode (packages/modules-runtime/modules-runtime.js:61:1)
at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:140:1)
at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
at meteorInstall.node_modules.meteor.mss.scss-processor.js (packages/mss/scss-processor.js:3:1)
at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:141:1)
at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
at node_modules/meteor/mss/node_modules/recursive-readdir/node_modules/minimatch/node_modules/sigmund/sigmund.js:39:1
at node_modules/meteor/mss/node_modules/recursive-readdir/node_modules/minimatch/node_modules/sigmund/sigmund.js:39:1


While building package casalova:styles:
error: No plugin known to handle file 'mixins/_pre_variables.scss'. If you want this file to be a static asset, use addAssets instead of
addFiles; eg, api.addAssets('mixins/_pre_variables.scss', 'client').
error: No plugin known to handle file 'mixins/_color.scss'. If you want this file to be a static asset, use addAssets instead of addFiles;
eg, api.addAssets('mixins/_color.scss', 'client').
error: No plugin known to handle file 'mixins/_mixins.scss'. If you want this file to be a static asset, use addAssets instead of addFiles;
eg, api.addAssets('mixins/_mixins.scss', 'client').
error: No plugin known to handle file 'mixins/_color-functions.scss'. If you want this file to be a static asset, use addAssets instead of
addFiles; eg, api.addAssets('mixins/_color-functions.scss', 'client').
error: No plugin known to handle file 'mixins/_variables.scss'. If you want this file to be a static asset, use addAssets instead of
addFiles; eg, api.addAssets('mixins/_variables.scss', 'client').
error: No plugin known to handle file 'mixins/_button-mixins.scss'. If you want this file to be a static asset, use addAssets instead of
addFiles; eg, api.addAssets('mixins/_button-mixins.scss', 'client').
error: No plugin known to handle file '_styles.scss'. If you want this file to be a static asset, use addAssets instead of addFiles; eg,
api.addAssets('_styles.scss', 'client').
error: No plugin known to handle file 'stylesheets/icons-material-design.scss'. If you want this file to be a static asset, use addAssets
instead of addFiles; eg, api.addAssets('stylesheets/icons-material-design.scss', 'client').
error: No plugin known to handle file 'stylesheets/popups.scss'. If you want this file to be a static asset, use addAssets instead of
addFiles; eg, api.addAssets('stylesheets/popups.scss', 'client').
error: No plugin known to handle file 'stylesheets/scaffolding.scss'. If you want this file to be a static asset, use addAssets instead of
addFiles; eg, api.addAssets('stylesheets/scaffolding.scss', 'client').
error: No plugin known to handle file 'stylesheets/tooltips.scss'. If you want this file to be a static asset, use addAssets instead of
addFiles; eg, api.addAssets('stylesheets/tooltips.scss', 'client').
error: No plugin known to handle file 'stylesheets/typography.scss'. If you want this file to be a static asset, use addAssets instead of
addFiles; eg, api.addAssets('stylesheets/typography.scss', 'client').
error: No plugin known to handle file 'material-design/styles.scss'. If you want this file to be a static asset, use addAssets instead of
addFiles; eg, api.addAssets('material-design/styles.scss', 'client').

While building package casalova:core:
error: No plugin known to handle file 'both/toasts.scss'. If you want this file to be a static asset, use addAssets instead of addFiles;
eg, api.addAssets('both/toasts.scss', 'client').

While building package casalova:infinite-card-list:
error: No plugin known to handle file 'infinite-card-list.scss'. If you want this file to be a static asset, use addAssets instead of
addFiles; eg, api.addAssets('infinite-card-list.scss', 'client').

While building package casalova:neighborhood-map-marker:
error: No plugin known to handle file 'neighborhood-map-marker.scss'. If you want this file to be a static asset, use addAssets instead of
addFiles; eg, api.addAssets('neighborhood-map-marker.scss', 'client').

While building package casalova:star-rating:
error: No plugin known to handle file 'star-rating.scss'. If you want this file to be a static asset, use addAssets instead of addFiles;
eg, api.addAssets('star-rating.scss', 'client').

While loading package meteorhacks:kadira-binary-deps@1.4.0:
error: Command failed:
/Users/clayne/.meteor/packages/meteor-tool/.1.4.0-beta.9.nkjjk++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm
rebuild
In file included from ../src/binding.cpp:2:
../node_modules/nan/nan.h:189:68: error: too many arguments to function call, expected at most 2, have 4
return v8::Signature::New(v8::Isolate::GetCurrent(), receiver, argc, argv);
~~~~~~~~~~~~~~~~~~                                      ^~~~~~~~~~
/Users/clayne/.node-gyp/4.4.7/include/node/v8.h:4675:3: note: 'New' declared here
static Local<Signature> New(
^
In file included from ../src/binding.cpp:2:
../node_modules/nan/nan.h:271:3: error: redefinition of 'NanNew'
NanNew<v8::StringObject, v8::Handle<v8::String> >(
^
../node_modules/nan/nan.h:264:3: note: previous definition is here
NanNew<v8::StringObject, v8::Local<v8::String> >(
^
../node_modules/nan/nan.h:289:36: error: redefinition of 'NanNew'
NAN_INLINE v8::Local<v8::RegExp> NanNew(
^
../node_modules/nan/nan.h:283:36: note: previous definition is here
NAN_INLINE v8::Local<v8::RegExp> NanNew(
^
../node_modules/nan/nan.h:301:36: error: redefinition of 'NanNew'
NAN_INLINE v8::Local<v8::RegExp> NanNew(
^
../node_modules/nan/nan.h:295:36: note: previous definition is here
NAN_INLINE v8::Local<v8::RegExp> NanNew(
^
../node_modules/nan/nan.h:481:19: error: no type named 'ExternalAsciiStringResource' in 'v8::String'; did you mean
'ExternalStringResource'?
v8::String::ExternalAsciiStringResource *resource) {
~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
ExternalStringResource
/Users/clayne/.node-gyp/4.4.7/include/node/v8.h:2210:19: note: 'ExternalStringResource' declared here
class V8_EXPORT ExternalStringResource
^
In file included from ../src/binding.cpp:2:
../node_modules/nan/nan.h:480:36: error: redefinition of 'NanNew'
NAN_INLINE v8::Local<v8::String> NanNew(
^
../node_modules/nan/nan.h:475:36: note: previous definition is here
NAN_INLINE v8::Local<v8::String> NanNew(
^
../node_modules/nan/nan.h:495:27: error: redefinition of '_NanEscapeScopeHelper'
NAN_INLINE v8::Local<T> _NanEscapeScopeHelper(v8::Local<T> val) {
^
../node_modules/nan/nan.h:490:27: note: previous definition is here
NAN_INLINE v8::Local<T> _NanEscapeScopeHelper(v8::Handle<T> val) {
^
../node_modules/nan/nan.h:511:12: error: no matching function for call to '_NanEscapeScopeHelper'
return NanEscapeScope(NanNew(v8::Undefined(v8::Isolate::GetCurrent())));
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:499:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEscapeScopeHelper(val))
^~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:495:27: note: candidate template ignored: substitution failure [with T = v8::Primitive]
NAN_INLINE v8::Local<T> _NanEscapeScopeHelper(v8::Local<T> val) {
^
../node_modules/nan/nan.h:516:12: error: no matching function for call to '_NanEscapeScopeHelper'
return NanEscapeScope(NanNew(v8::Null(v8::Isolate::GetCurrent())));
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:499:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEscapeScopeHelper(val))
^~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:495:27: note: candidate template ignored: substitution failure [with T = v8::Primitive]
NAN_INLINE v8::Local<T> _NanEscapeScopeHelper(v8::Local<T> val) {
^
../node_modules/nan/nan.h:521:12: error: no matching function for call to '_NanEscapeScopeHelper'
return NanEscapeScope(NanNew(v8::True(v8::Isolate::GetCurrent())));
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:499:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEscapeScopeHelper(val))
^~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:495:27: note: candidate template ignored: substitution failure [with T = v8::Boolean]
NAN_INLINE v8::Local<T> _NanEscapeScopeHelper(v8::Local<T> val) {
^
../node_modules/nan/nan.h:526:12: error: no matching function for call to '_NanEscapeScopeHelper'
return NanEscapeScope(NanNew(v8::False(v8::Isolate::GetCurrent())));
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:499:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEscapeScopeHelper(val))
^~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:495:27: note: candidate template ignored: substitution failure [with T = v8::Boolean]
NAN_INLINE v8::Local<T> _NanEscapeScopeHelper(v8::Local<T> val) {
^
../node_modules/nan/nan.h:755:13: error: no member named 'smalloc' in namespace 'node'
, node::smalloc::FreeCallback callback
~~~~~~^
../node_modules/nan/nan.h:766:12: error: no matching function for call to 'New'
return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
^~~~~~~~~~~~~~~~~
/Users/clayne/.node-gyp/4.4.7/include/node/node_buffer.h:31:40: note: candidate function not viable: no known conversion from 'uint32_t'
(aka 'unsigned int') to 'enum encoding' for 3rd argument
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
^
/Users/clayne/.node-gyp/4.4.7/include/node/node_buffer.h:43:40: note: candidate function not viable: 2nd argument ('const char *') would
lose const qualifier
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
^
/Users/clayne/.node-gyp/4.4.7/include/node/node_buffer.h:28:40: note: candidate function not viable: requires 2 arguments, but 3 were
provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
^
/Users/clayne/.node-gyp/4.4.7/include/node/node_buffer.h:36:40: note: candidate function not viable: requires 5 arguments, but 3 were
provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
^
In file included from ../src/binding.cpp:2:
../node_modules/nan/nan.h:770:12: error: no viable conversion from returned value of type 'v8::MaybeLocal<v8::Object>' to function return
type 'v8::Local<v8::Object>'
return node::Buffer::New(v8::Isolate::GetCurrent(), size);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/clayne/.node-gyp/4.4.7/include/node/v8.h:210:7: note: candidate constructor (the implicit copy constructor) not viable: no known
conversion from 'v8::MaybeLocal<v8::Object>' to 'const v8::Local<v8::Object> &' for 1st argument
class Local {
^
/Users/clayne/.node-gyp/4.4.7/include/node/v8.h:210:7: note: candidate constructor (the implicit move constructor) not viable: no known
conversion from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object> &&' for 1st argument
/Users/clayne/.node-gyp/4.4.7/include/node/v8.h:214:13: note: candidate template ignored: could not match 'Local' against 'MaybeLocal'
V8_INLINE Local(Local<S> that)
^
/Users/clayne/.node-gyp/4.4.7/include/node/v8.h:326:13: note: candidate template ignored: could not match 'S *' against
'v8::MaybeLocal<v8::Object>'
V8_INLINE Local(S* that)
^
In file included from ../src/binding.cpp:2:
../node_modules/nan/nan.h:777:26: error: no member named 'Use' in namespace 'node::Buffer'
return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
~~~~~~~~~~~~~~^
../node_modules/nan/nan.h:1809:12: error: no matching function for call to '_NanEscapeScopeHelper'
return NanEscapeScope(NanNew(handle)->Get(kCallbackIndex)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:499:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEscapeScopeHelper(val))
^~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:495:27: note: candidate template ignored: substitution failure [with T = v8::Function]
NAN_INLINE v8::Local<T> _NanEscapeScopeHelper(v8::Local<T> val) {
^
../node_modules/nan/nan.h:1824:12: error: no matching function for call to '_NanEscapeScopeHelper'
return NanEscapeScope(node::MakeCallback(
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:499:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEscapeScopeHelper(val))
^~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:495:27: note: candidate template ignored: substitution failure [with T = v8::Value]
NAN_INLINE v8::Local<T> _NanEscapeScopeHelper(v8::Local<T> val) {
^
../node_modules/nan/nan.h:1897:12: error: no matching function for call to '_NanEscapeScopeHelper'
return NanEscapeScope(handle->Get(NanNew(key)).As<v8::Object>());
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:499:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEscapeScopeHelper(val))
^~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:495:27: note: candidate template ignored: substitution failure [with T = v8::Object]
NAN_INLINE v8::Local<T> _NanEscapeScopeHelper(v8::Local<T> val) {
^
../node_modules/nan/nan.h:2103:12: error: no member named 'IsExternalAscii' in 'v8::String'; did you mean 'IsExternal'?
if (str->IsExternalAscii()) {
^~~~~~~~~~~~~~~
IsExternal
/Users/clayne/.node-gyp/4.4.7/include/node/v8.h:2174:8: note: 'IsExternal' declared here
bool IsExternal() const;
^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/sysinfo/src/binding.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit
(/Users/clayne/.meteor/packages/meteor-tool/.1.4.0-beta.9.nkjjk++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.5.0
gyp ERR! command
"/Users/clayne/.meteor/packages/meteor-tool/.1.4.0-beta.9.nkjjk++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node"
"/Users/clayne/.meteor/packages/meteor-tool/.1.4.0-beta.9.nkjjk++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js"
"rebuild"
gyp ERR! cwd
/Users/clayne/.meteor/packages/meteorhacks_kadira-binary-deps/.1.4.0.aho2qb++os.linux.x86_64+os.osx.x86_64+web.browser+web.cordova/npm/node_modules/.temp-1079zw/node_modules/usage
gyp ERR! node -v v4.4.7
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

npm ERR! Darwin 15.5.0
npm ERR! argv
"/Users/clayne/.meteor/packages/meteor-tool/.1.4.0-beta.9.nkjjk++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node"
"/Users/clayne/.meteor/packages/meteor-tool/.1.4.0-beta.9.nkjjk++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm"
"rebuild"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! usage@0.5.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the usage@0.5.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the usage package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs usage
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls usage
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!
/Users/clayne/.meteor/packages/meteorhacks_kadira-binary-deps/.1.4.0.aho2qb++os.linux.x86_64+os.osx.x86_64+web.browser+web.cordova/npm/node_modules/.temp-1079zw/npm-debug.log
In file included from ../src/binding.cpp:2:
../node_modules/nan/nan.h:189:68: error: too many arguments to function call, expected at most 2, have 4
return v8::Signature::New(v8::Isolate::GetCurrent(), receiver, argc, argv);
~~~~~~~~~~~~~~~~~~                                      ^~~~~~~~~~
/Users/clayne/.node-gyp/4.4.7/include/node/v8.h:4675:3: note: 'New' declared here
static Local<Signature> New(
^
In file included from ../src/binding.cpp:2:
../node_modules/nan/nan.h:271:3: error: redefinition of 'NanNew'
NanNew<v8::StringObject, v8::Handle<v8::String> >(
^
../node_modules/nan/nan.h:264:3: note: previous definition is here
NanNew<v8::StringObject, v8::Local<v8::String> >(
^
../node_modules/nan/nan.h:289:36: error: redefinition of 'NanNew'
NAN_INLINE v8::Local<v8::RegExp> NanNew(
^
../node_modules/nan/nan.h:283:36: note: previous definition is here
NAN_INLINE v8::Local<v8::RegExp> NanNew(
^
../node_modules/nan/nan.h:301:36: error: redefinition of 'NanNew'
NAN_INLINE v8::Local<v8::RegExp> NanNew(
^
../node_modules/nan/nan.h:295:36: note: previous definition is here
NAN_INLINE v8::Local<v8::RegExp> NanNew(
^
../node_modules/nan/nan.h:481:19: error: no type named 'ExternalAsciiStringResource' in 'v8::String'; did you mean
'ExternalStringResource'?
v8::String::ExternalAsciiStringResource *resource) {
~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
ExternalStringResource
/Users/clayne/.node-gyp/4.4.7/include/node/v8.h:2210:19: note: 'ExternalStringResource' declared here
class V8_EXPORT ExternalStringResource
^
In file included from ../src/binding.cpp:2:
../node_modules/nan/nan.h:480:36: error: redefinition of 'NanNew'
NAN_INLINE v8::Local<v8::String> NanNew(
^
../node_modules/nan/nan.h:475:36: note: previous definition is here
NAN_INLINE v8::Local<v8::String> NanNew(
^
../node_modules/nan/nan.h:495:27: error: redefinition of '_NanEscapeScopeHelper'
NAN_INLINE v8::Local<T> _NanEscapeScopeHelper(v8::Local<T> val) {
^
../node_modules/nan/nan.h:490:27: note: previous definition is here
NAN_INLINE v8::Local<T> _NanEscapeScopeHelper(v8::Handle<T> val) {
^
../node_modules/nan/nan.h:511:12: error: no matching function for call to '_NanEscapeScopeHelper'
return NanEscapeScope(NanNew(v8::Undefined(v8::Isolate::GetCurrent())));
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:499:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEscapeScopeHelper(val))
^~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:495:27: note: candidate template ignored: substitution failure [with T = v8::Primitive]
NAN_INLINE v8::Local<T> _NanEscapeScopeHelper(v8::Local<T> val) {
^
../node_modules/nan/nan.h:516:12: error: no matching function for call to '_NanEscapeScopeHelper'
return NanEscapeScope(NanNew(v8::Null(v8::Isolate::GetCurrent())));
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:499:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEscapeScopeHelper(val))
^~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:495:27: note: candidate template ignored: substitution failure [with T = v8::Primitive]
NAN_INLINE v8::Local<T> _NanEscapeScopeHelper(v8::Local<T> val) {
^
../node_modules/nan/nan.h:521:12: error: no matching function for call to '_NanEscapeScopeHelper'
return NanEscapeScope(NanNew(v8::True(v8::Isolate::GetCurrent())));
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:499:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEscapeScopeHelper(val))
^~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:495:27: note: candidate template ignored: substitution failure [with T = v8::Boolean]
NAN_INLINE v8::Local<T> _NanEscapeScopeHelper(v8::Local<T> val) {
^
../node_modules/nan/nan.h:526:12: error: no matching function for call to '_NanEscapeScopeHelper'
return NanEscapeScope(NanNew(v8::False(v8::Isolate::GetCurrent())));
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:499:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEscapeScopeHelper(val))
^~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:495:27: note: candidate template ignored: substitution failure [with T = v8::Boolean]
NAN_INLINE v8::Local<T> _NanEscapeScopeHelper(v8::Local<T> val) {
^
../node_modules/nan/nan.h:755:13: error: no member named 'smalloc' in namespace 'node'
, node::smalloc::FreeCallback callback
~~~~~~^
../node_modules/nan/nan.h:766:12: error: no matching function for call to 'New'
return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
^~~~~~~~~~~~~~~~~
/Users/clayne/.node-gyp/4.4.7/include/node/node_buffer.h:31:40: note: candidate function not viable: no known conversion from 'uint32_t'
(aka 'unsigned int') to 'enum encoding' for 3rd argument
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
^
/Users/clayne/.node-gyp/4.4.7/include/node/node_buffer.h:43:40: note: candidate function not viable: 2nd argument ('const char *') would
lose const qualifier
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
^
/Users/clayne/.node-gyp/4.4.7/include/node/node_buffer.h:28:40: note: candidate function not viable: requires 2 arguments, but 3 were
provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
^
/Users/clayne/.node-gyp/4.4.7/include/node/node_buffer.h:36:40: note: candidate function not viable: requires 5 arguments, but 3 were
provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
^
In file included from ../src/binding.cpp:2:
../node_modules/nan/nan.h:770:12: error: no viable conversion from returned value of type 'v8::MaybeLocal<v8::Object>' to function return
type 'v8::Local<v8::Object>'
return node::Buffer::New(v8::Isolate::GetCurrent(), size);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/clayne/.node-gyp/4.4.7/include/node/v8.h:210:7: note: candidate constructor (the implicit copy constructor) not viable: no known
conversion from 'v8::MaybeLocal<v8::Object>' to 'const v8::Local<v8::Object> &' for 1st argument
class Local {
^
/Users/clayne/.node-gyp/4.4.7/include/node/v8.h:210:7: note: candidate constructor (the implicit move constructor) not viable: no known
conversion from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object> &&' for 1st argument
/Users/clayne/.node-gyp/4.4.7/include/node/v8.h:214:13: note: candidate template ignored: could not match 'Local' against 'MaybeLocal'
V8_INLINE Local(Local<S> that)
^
/Users/clayne/.node-gyp/4.4.7/include/node/v8.h:326:13: note: candidate template ignored: could not match 'S *' against
'v8::MaybeLocal<v8::Object>'
V8_INLINE Local(S* that)
^
In file included from ../src/binding.cpp:2:
../node_modules/nan/nan.h:777:26: error: no member named 'Use' in namespace 'node::Buffer'
return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
~~~~~~~~~~~~~~^
../node_modules/nan/nan.h:1809:12: error: no matching function for call to '_NanEscapeScopeHelper'
return NanEscapeScope(NanNew(handle)->Get(kCallbackIndex)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:499:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEscapeScopeHelper(val))
^~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:495:27: note: candidate template ignored: substitution failure [with T = v8::Function]
NAN_INLINE v8::Local<T> _NanEscapeScopeHelper(v8::Local<T> val) {
^
../node_modules/nan/nan.h:1824:12: error: no matching function for call to '_NanEscapeScopeHelper'
return NanEscapeScope(node::MakeCallback(
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:499:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEscapeScopeHelper(val))
^~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:495:27: note: candidate template ignored: substitution failure [with T = v8::Value]
NAN_INLINE v8::Local<T> _NanEscapeScopeHelper(v8::Local<T> val) {
^
../node_modules/nan/nan.h:1897:12: error: no matching function for call to '_NanEscapeScopeHelper'
return NanEscapeScope(handle->Get(NanNew(key)).As<v8::Object>());
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:499:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEscapeScopeHelper(val))
^~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:495:27: note: candidate template ignored: substitution failure [with T = v8::Object]
NAN_INLINE v8::Local<T> _NanEscapeScopeHelper(v8::Local<T> val) {
^
../node_modules/nan/nan.h:2103:12: error: no member named 'IsExternalAscii' in 'v8::String'; did you mean 'IsExternal'?
if (str->IsExternalAscii()) {
^~~~~~~~~~~~~~~
IsExternal
/Users/clayne/.node-gyp/4.4.7/include/node/v8.h:2174:8: note: 'IsExternal' declared here
bool IsExternal() const;
^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/sysinfo/src/binding.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit
(/Users/clayne/.meteor/packages/meteor-tool/.1.4.0-beta.9.nkjjk++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.5.0
gyp ERR! command
"/Users/clayne/.meteor/packages/meteor-tool/.1.4.0-beta.9.nkjjk++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node"
"/Users/clayne/.meteor/packages/meteor-tool/.1.4.0-beta.9.nkjjk++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js"
"rebuild"
gyp ERR! cwd
/Users/clayne/.meteor/packages/meteorhacks_kadira-binary-deps/.1.4.0.aho2qb++os.linux.x86_64+os.osx.x86_64+web.browser+web.cordova/npm/node_modules/.temp-1079zw/node_modules/usage
gyp ERR! node -v v4.4.7
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

npm ERR! Darwin 15.5.0
npm ERR! argv
"/Users/clayne/.meteor/packages/meteor-tool/.1.4.0-beta.9.nkjjk++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node"
"/Users/clayne/.meteor/packages/meteor-tool/.1.4.0-beta.9.nkjjk++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm"
"rebuild"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! usage@0.5.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the usage@0.5.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the usage package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs usage
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls usage
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!
/Users/clayne/.meteor/packages/meteorhacks_kadira-binary-deps/.1.4.0.aho2qb++os.linux.x86_64+os.osx.x86_64+web.browser+web.cordova/npm/node_modules/.temp-1079zw/npm-debug.log
I installed my npm dependencies with meteor npm install but it's still not working. This is during the upgrade process, so I can't even get up to Meteor 1.4-beta.9 nevermind running it.

I ran into the same issue with 1.4-beta.6 and 1.4-beta.7 as well.

Works fine with Meteor 1.3.4.4
```

I'm on OS X.

**Comment by benjamn** [comment]
There seem to be a couple different issues at play here (both real & legitimate):
* The failure of `meteor add nathantreid:css-modules` should be fixed by the same solution I found for https://github.com/meteor/meteor/issues/7297; that is, [this commit](https://github.com/meteor/meteor/commit/f001d223fa0728c824ebf1edd7becefb403cab95). I'll release that change in `1.4-beta.10` soon.
* The failure of `meteor add meteorhacks:kadira-binary-deps` is due to that package [using `v8-profiler@5.2.0`](https://github.com/meteorhacks/kadira-binary-deps/blob/434f9f2a3e3282d28d7f2a56475d38c3f9660141/package.js#L10), which is not compatible with the version of V8 that Node 4 uses. I think that can be fixed by publishing a new version of `meteorhacks:kadira-binary-deps` that uses `v8-profiler@5.6.5` (the latest version).

**Comment by clayne11** [comment]
Thanks. I'll post this on the `meteorhacks:kadira ` issues as well.

**Comment by arunoda** [comment]
Thanks @benjamn I'll do a new release with the testing.

**Comment by clayne11** [comment]
This is still not working for me with `nathantreid:css-modules@2.1.0`.

I tried nuking my `~/.meteor` and `.meteor/local` to no avail.

I get the following error now:

```
=> Errors while initializing project:

While loading plugin `mss` from package `nathantreid:css-modules`:
error: Can't load npm module 'node-sass' from packages/modules-runtime.js. Check your Npm.depends().
```

**Comment by clayne11** [comment]
I managed to get around this issue. The key was using the same version of `node` to `npm install` my dependencies as Meteor `1.4` uses even before doing the update.

I had to delete my `node_modules` folder and then `nvm use 4` to switch to the correct version of `node`. Then I did an `npm install` and only then was I able to update with `meteor update --release-1.4-beta.14`.

This is a pretty confusing and difficult to debug experience though. Hopefully this can be improved.

Although I did now manage to get my app updated to `1.4-beta.14`, it won't start.

Now I'm getting this:

```
W20160715-11:30:39.505(-5)? (STDERR) /Users/clayne/.meteor/packages/meteor-tool/.1.4.0-beta.14.uo5kdf++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20160715-11:30:39.580(-5)? (STDERR)            				throw(ex);
W20160715-11:30:39.580(-5)? (STDERR)            				^
W20160715-11:30:39.581(-5)? (STDERR)
W20160715-11:30:39.581(-5)? (STDERR) Error: Module did not self-register.
W20160715-11:30:39.581(-5)? (STDERR)     at Error (native)
W20160715-11:30:39.583(-5)? (STDERR)     at Object.Module._extensions..node (module.js:434:18)
W20160715-11:30:39.583(-5)? (STDERR)     at Module.load (module.js:343:32)
W20160715-11:30:39.584(-5)? (STDERR)     at Module.Mp.load (/Users/clayne/.meteor/packages/babel-compiler/.6.9.0-beta.14.b57a7u++os+web.browser+web.cordova/npm/node_modules/reify/node/runtime.js:16:23)
W20160715-11:30:39.584(-5)? (STDERR)     at Function.Module._load (module.js:300:12)
W20160715-11:30:39.584(-5)? (STDERR)     at Module.require (module.js:353:17)
W20160715-11:30:39.585(-5)? (STDERR)     at require (internal/module.js:12:17)
W20160715-11:30:39.585(-5)? (STDERR)     at bindings (/Users/clayne/.meteor/packages/npm-bcrypt/.0.8.7.1rqvxzh++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/bindings/bindings.js:76:44)
W20160715-11:30:39.585(-5)? (STDERR)     at Object.<anonymous> (/Users/clayne/.meteor/packages/npm-bcrypt/.0.8.7.1rqvxzh++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/bcrypt/bcrypt.js:3:35)
W20160715-11:30:39.586(-5)? (STDERR)     at Module._compile (module.js:409:26)
   Starting your app                         -
```

I deleted `.meteor/local` before starting. This build also took about 10 minutes to build. Usually it takes ~2 minutes on my machine.

**Comment by benjamn** [comment]
@clayne11 You should make sure you've updated to Meteor 1.3.5.1 by running `meteor update`, so that `meteor node` and `meteor npm` will know how to infer the correct versions of `node` and `npm` from your app's `.meteor/release` file (which will probably say `METEOR@1.4-rc.1`), even though the `meteor` script still points to Meteor 1.3.5.1 (until Meteor 1.4 is officially released).

**Comment by benjamn** [comment]
If you update to Meteor 1.3.5.1, then running `meteor npm version` outside of an app directory will show Node 0.10.46 and `npm` 3.10.5 (the versions used by 1.3.5.1), whereas running `meteor npm version` inside an app directory will show the versions appropriate for that app (according to its `.meteor/release` file). In this case, Node 4.4.7 and `npm` 3.10.5.

**Comment by benjamn** [comment]
This should be fixed in Meteor 1.4, which has now been released: `meteor update --release 1.4` (and soon just `meteor update`). Feel free to reopen if similar problems persist after updating to 1.4.

**Comment by Spiralis** [comment]
I am still getting an issue. Not as verbose as above:
```
=> Started proxy.                                       
=> Started MongoDB.                                     
=> Errors prevented startup:                            
                                                        
   While loading plugin `mss` from package `nathantreid:
   error: Can't load npm module 'node-sass' from package
   Npm.depends().                                       
                                                        
=> Your application has errors. Waiting for file change.
```

running `meteor npm version` inside and outside the app-folder shows the same info:
```
{ hub: '0.1.0-proto',
  npm: '3.10.5',
  ares: '1.10.1-DEV',
  http_parser: '2.5.2',
  icu: '56.1',
  modules: '46',
  node: '4.4.7',
  openssl: '1.0.2h',
  uv: '1.8.0',
  v8: '4.5.103.36',
  zlib: '1.2.8' }
```

I was already on 1.3.5.1 before I today did a upgraded to 1.4. I followed the migration suggestions given here: https://guide.meteor.com/1.4-migration.html

When it failed I also tried to do a `meteor reset` and a `meteor npm rebuild`. The meteor reset is probably not relevant, but i included it for completeness. The rebuild completed, but starting the app still failed. 

I then nuked the `node_modules` and `.meteor/local` folders and tried to run `meteor` again. Still fails with same error message. 

I then ran `meteor npm install --save`, but I still get the same error. 

Any ideas?

**Comment by Spiralis** [comment]
I got it working!

Found a discussion [here](https://github.com/nathantreid/meteor-css-modules/issues/51) that discussed something similar. 

Did an `npm uninstall node-sass` followed by a `meteor npm install node-sass` and my app started as it should.
