### ISSUE TITLE
[1.3.4.4] [modules] CommonJS require statements return undefined for circular references

### ISSUE THREAD

**Issue by mrmowgli** [meteor/meteor#7459]
This seems to be an ongoing issue with Meteor 1.3’s modules- Dealing with CommonJS circular references for non ES6 code like CoffeeScript (and by extension, with any other language that compiles to ES5 JavaScript). 

There is currently a Coffeescript branch of the todos that illustrates this issue very well and this issue was first raised in [ Issue #6381  ](https://github.com/meteor/meteor/issues/6381).  It was resolved in 1.3 Beta 12 by using non-destructuring requires.  However updating to Meteor 1.3.4.4+ breaks even this workaround.

Steps to reproduce:
` Check out the latest TODO's application from github
- Change to coffeescript branch `git checkout coffeescript`
- Update NPM `meteor npm install`

Running `meteor` at this point will work, and inserting a new todo in a current list works. To break:
- meteor update 
- Try and add a new todo item.

In the file: incompleteCountDenormalizer.coffee both ListsModule and TodosModule requires return empty objects.

**Comment by benjamn** [comment]
[Since Meteor 1.3.3](https://github.com/meteor/meteor/blob/devel/History.md#v133), you can now use `import` and `export` directly in `.coffee` files, by enclosing the statements in back-ticks:
```coffee
`import { a, b } from "./c"`
`export default a + b`
```
Note especially this bullet point from the 1.3.3 release notes:

* The `coffeescript` plugin now passes raw JavaScript code enclosed by back-ticks to `BabelCompiler`, enabling all ECMAScript features (including `import` and `export`) within CoffeeScript. #6000 #6691

No module system can completely protect you from problems arising from circular dependencies, but ES2015 does a much better job of mitigating those problems than `require`, thanks to live bindings.

**Comment by mrmowgli** [comment]
I see.  So all modules need to be rewritten for both import and export.  Perhaps then this should be an update in the guide?  Also an update to the todos coffeescript branch as reference.  Trying it out now.

**Comment by GeoffreyBooth** [comment]
There’s a bug here, and it deserves to be investigated. The code in the [CoffeeScript Todos](https://github.com/meteor/todos/tree/coffeescript) already accounts for circular references, or else the `require` statements wouldn’t have worked in 1.3; a bug was introduced between 1.3 and 1.3.4.4. Odds are that this bug is having other unintended consequences that we should at least know about.

I just updated CoffeeScript Todos to incorporate all the changes to the `master` branch since the last time I worked in that branch. The bug @mrmowgli refers to can be seen in `imports/api/todos/incompleteCountDenormalizer.coffee`. At the top of the file, I have this:

```coffee
TodosModule = require './todos.coffee'
ListsModule = require '../lists/lists.coffee'
```

which should resolve to `TodosModule.Todos` and `ListsModule.Lists` like they do in the other files. Further down, though, I have this:

```coffee
incompleteCountDenormalizer =
  _updateList: (listId) ->
    TodosModule = require('./todos.coffee') unless TodosModule.Todos?
    incompleteCount = TodosModule.Todos.find
      listId: listId
      checked: no
    .count()
```

So that `require` line in there? That’s an ugly workaround that I just added after the upgrade to 1.3.4.4. If you set a breakpoint there and inspect `TodosModule` you’ll find not that it’s undefined—_it’s an empty object._ I’m not sure why this would be.

**Comment by hwillson** [comment]
Native coffeescript support for `import` / `export` declarations was added in Meteor [1.4.2](https://github.com/meteor/meteor/blob/devel/History.md#v142), which means this issue has been resolved (if using ES2015 modules). The [todos `coffeescript` branch has been updated](https://github.com/meteor/todos/pull/206) to reflect this. Closing - thanks for reporting this originally!

**Comment by GeoffreyBooth** [comment]
@hwillson I wouldn’t close this if I were you. [What I wrote on Aug. 29](https://github.com/meteor/meteor/issues/7459#issuecomment-243341399) still stands; something in the way that Meteor works with CommonJS broke things between 1.3 and 1.3.4.4. Seeing as the ES2015 `import` and `export` statements are just being transpiled into `require`, it behooves you to investigate what broke between those two versions. This isn’t a bug in CommonJS itself, that ES2015 modules solve; it’s a bug in Meteor’s build system and how it processes `require` statements, that used to work but no longer does.

**Comment by hwillson** [comment]
Thanks for the update @GeoffreyBooth - looking at meteor/todos#206 however, it appears as though the safeguards you put in place to protect against circular dependencies (mentioned in https://github.com/meteor/meteor/issues/7459#issuecomment-243341399) were removed, as they were no longer needed after updating to `1.4.2.3`. Is that not the case? I'm happy to re-open this issue if this is still happening (but I'll leave it closed for now since we're trying hard to reduce the open issue backlog - innocent until proven guilty! 😄 ).

**Comment by GeoffreyBooth** [comment]
They’re no longer needed in Todos with `import`/`export`, but they were also not needed in Meteor 1.3 with CommonJS. The question is whether those safeguards are needed in 1.4.2.3 with CommonJS. If they’re needed, then the bug that generated this ticket is still present.

Try converting the current `coffeescript` branch (or just the files that had the circular dependency issue) back to CommonJS and see if the bug reappears. Or take the last commit before I added the circular dependency workarounds, probably back in 1.3, and upgrade that commit to 1.4.2.3 and see if it works without workarounds. If it works without the hacks I added for the circular dependency, and without converting the `require` statements to `import`, then the bug is gone.

If your policy is that everyone should just use `import`/`export` going forward and you’re not going to support debugging CommonJS issues anymore, then this can stay closed. Otherwise, before closing this issue I think someone should check that the bug truly is gone in 1.4.2.3 Meteor when using CommonJS.

**Comment by hwillson** [comment]
Thanks @GeoffreyBooth - so the issue is fixed when using ES2015 module support, but could still exist when using CommonJS. I can't speak for MDG (I'm just a community triager), but I'm pretty sure their policy is to look at every issue that comes in, and address as many of them as they can. Due to the sheer volume/number of issues though, some issues really do need to be prioritized over others. In this case there hasn't been much interest/activity on this issue in 6 months, and the lack of +1's leads me to believe the number of people potentially impacted by this issue is quite low. I can always re-open this issue, but I have a feeling it's just going to sit open for a while longer, before being closed again. I'm definitely happy to take a look at a repro showing this issue (or even create one if necessary), but again given Meteor's push into ES2015 module land (which fixes this problem), I'm not sure if that will be time well spent.

But alas - I'm also easily convinced, so reply back saying I'm crazy and I'll throw in the towel and re-open! 😄

**Comment by GeoffreyBooth** [comment]
I’m fine with closing it, it would just be nice if there was some way to mark it as unresolved. Usually closed means fixed, but that’s not the case here.
