### ISSUE TITLE
[1.4] MongoError: no primary found in replicaset

### ISSUE THREAD

**Issue by dr-dimitru** [meteor/meteor#7492]
Hi folks!

After upgrading to Meteor@1.4
There was in issue described in #7450 , which is successfully solved - see [this comment](https://github.com/meteor/meteor/issues/7450#issuecomment-235246586)
Everything is working fine on VPS, dedicated servers, but not on Heroku. Unfortunately Heroku can not connect to MongoDB. As I remember in `mongodb-native` driver this can be solved by increasing connection timeout. Any idea how to solve this in Meteor@1.4?

Full Heroku error stack:
```
heroku[web.1]: Starting process with command `node main.js`
app[web.1]: 
app[web.1]: /app/programs/server/node_modules/fibers/future.js:313
app[web.1]:            throw(ex);
app[web.1]:            ^
app[web.1]: MongoError: no primary found in replicaset
app[web.1]:     at Object.Future.wait (/app/programs/server/node_modules/fibers/future.js:449:15)
app[web.1]:     at new MongoConnection (packages/mongo/mongo_driver.js:216:27)
app[web.1]:     at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
app[web.1]:     at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
app[web.1]:     at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
app[web.1]:     at new Mongo.Collection (packages/mongo/collection.js:103:40)
app[web.1]:     at AccountsServer.AccountsCommon (packages/accounts-base/accounts_common.js:23:18)
app[web.1]:     at new AccountsServer (packages/accounts-base/accounts_server.js:18:5)
app[web.1]:     at meteorInstall.node_modules.meteor.accounts-base.server_main.js (packages/accounts-base/server_main.js:9:12)
app[web.1]:     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
app[web.1]:     - - - - -
app[web.1]:     at /app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/replset.js:558:32
app[web.1]:     at [object Object].<anonymous> (/app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/replset.js:385:24)
app[web.1]:     at [object Object].g (events.js:260:16)
app[web.1]:     at emitOne (events.js:77:13)
app[web.1]:     at [object Object].emit (events.js:169:7)
app[web.1]:     at Object.cb (/app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:265:14)
app[web.1]:     at /app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:443:18
app[web.1]:     at authenticateStragglers (/app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:399:16)
app[web.1]:     at [object Object].messageHandler (/app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:421:5)
app[web.1]:     at Socket.<anonymous> (/app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:294:22)
heroku[web.1]: Process exited with status 1
heroku[web.1]: State changed from starting to crashed
```

Connection strings:
```
MONGO_OPLOG_URL: mongodb://usr:pwd@<IP>:27017,<IP>:27018,<IP>:27019/local?authSource=admin&replicaSet=rs0
MONGO_URL:       mongodb://usr:pwd@<IP>:27017,<IP>:27018,<IP>:27019/dbname?authSource=admin&replicaSet=rs0
```

**Comment by thsowers** [comment]
Running into the same issue:

`Error: No primary found in set
    at Object.Future.wait (/bundle/bundle/programs/server/node_modules/fibers/future.js:449:15)
    at new MongoConnection (packages/mongo/mongo_driver.js:213:27)
    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
    at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
    at new Mongo.Collection (packages/mongo/collection.js:103:40)
    at AccountsServer.AccountsCommon (packages/accounts-base/accounts_common.js:23:18)
    at new AccountsServer (packages/accounts-base/accounts_server.js:18:5)
    at meteorInstall.node_modules.meteor.accounts-base.server_main.js (packages/accounts-base/server_main.js:9:12)
    at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
    - - - - -
    at /bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/connection/repl_set/repl_set.js:483:45
    at [object Object].<anonymous> (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:566:7)
    at [object Object].emit (events.js:106:17)
    at [object Object].<anonymous> (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:156:15)
    at [object Object].emit (events.js:98:17)
    at Socket.<anonymous> (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
    at Socket.emit (events.js:95:17)
    at net.js:834:16
`

I downgraded back to 1.3.5.1, but i'm still having this problem

**Comment by dr-dimitru** [comment]
__Update__:
I've tried to set next connection string parameters between 0 and 600000:
 - `connectTimeoutMS`
 - `socketTimeoutMS`

Unfortunately it doesn't helped at all

**Comment by dr-dimitru** [comment]
@thsowers could you try `connectTimeoutMS` and `socketTimeoutMS` parameters?
See [the docs](https://docs.mongodb.com/manual/reference/connection-string/#connections-connection-options), just wondering if it will help you.
Are you on Heroku too?

**Comment by thsowers** [comment]
@dr-dimitru  I had a separate issue where the URL I was pointing at had stepped down to a secondary. So, it does appear to work on 1.3.5.1

I'm on DigitalOcean using Mupx, i'm currently running into #7475 and I think my issue is specific to that. However, I did run into this issue when editing the mupx package to use a different base docker image, so it's possible they could be related, but right now I can't say for sure

**Comment by dr-dimitru** [comment]
Never liked `mup` nor `mupx`.
Let me know if you will fix it somehow.

**Comment by abernix** [comment]
@dr-dimitru @thsowers Who runs your Mongo deployments?  This sounds like an a misconfiguration in your Mongo server and not an error in Meteor.  The Mongo driver that Meteor had been using prior to Meteor 1.4 was very old and the new driver has evolved signifcantly to provide very important information.

I would expect this error if you provided the wrong name for `replicaSet` in the URL, or if you actually in fact, do not have a primary server.

If you connect to your `mongo` shell, what is the output of `rs.isMaster()`?

**Comment by thsowers** [comment]
@abernix I run my mongo deployments on DO, and you were correct, it was a misconfiguration in my server and not an error in Meteor

**Comment by abernix** [comment]
I'm actually going to close this as I'm confident that it's a misconfiguration.  Please refer to the Mongo docs (and other resources) for more information as this error is actually coming directly from Mongo, not from Meteor.

**Comment by dr-dimitru** [comment]
@abernix 
I've deployed same application to the dedicated server, and successfully connected to the same MongoDB, with same connection strings. Actually all my other meteor apps (on different servers and platforms) shares same MongoDB, and all of them updated successfully to Meteor@1.4, except those hosted on Heroku.

Output of the `rs.isMaster()`:
```
rs0:PRIMARY> rs.isMaster()
{
	"hosts" : [
		"127.0.0.1:27017",
		"127.0.0.1:27018",
		"127.0.0.1:27019"
	],
	"setName" : "rs0",
	"setVersion" : 1,
	"ismaster" : true,
	"secondary" : false,
	"primary" : "127.0.0.1:27019",
	"me" : "127.0.0.1:27019",
	"electionId" : ObjectId("7fffffff0000000000000008"),
	"maxBsonObjectSize" : 16777216,
	"maxMessageSizeBytes" : 48000000,
	"maxWriteBatchSize" : 1000,
	"localTime" : ISODate("2016-07-27T13:26:32.815Z"),
	"maxWireVersion" : 4,
	"minWireVersion" : 0,
	"ok" : 1
}
```

`db.version()`:
```
rs0:PRIMARY> db.version()
3.2.7
```

@thsowers what have you exactly changed in configuration?

**Comment by abernix** [comment]
@dr-dimitru How are you _absolutely_ sure that Heroku is sending the correct value for `MONGO_URL` with `replicaSet=rs0` on the end?

**Comment by dr-dimitru** [comment]
Yes. 100% sure.
```
$ heroku config
=== meteor-files-neo Config Vars
DDP_DEFAULT_CONNECTION_URL: https://wssfiles.veliov.com
MONGO_OPLOG_URL:            mongodb://aaa:bbb@x.y.z.a:27017,x.y.z.a:27018,x.y.z.a:27019/local?authSource=admin&replicaSet=rs0
MONGO_URL:                  mongodb://ccc:ddd@x.y.z.a:27017,x.y.z.a:27018,x.y.z.a:27019/mfiles?authSource=admin&replicaSet=rs0
ROOT_URL:                   https://files.veliov.com
```

Tested with same env.vars locally - working.

**Comment by abernix** [comment]
Hmm.  I don't really have any other suggestions, unfortunately.  That configuration definitely should work and does work from other environments.  This points to a problem with the driver or some sort of communication/permission/user issue (insufficient permissions?) with your Mongo server.

**Comment by dr-dimitru** [comment]
The previous version of meteor of the same app (without changes in app codebase), working fine.

**Comment by dr-dimitru** [comment]
@abernix I guess it can be managed via `connectTimeoutMS` and/or `socketTimeoutMS`. Or maybe you can tell me other direction to dig-in?

**Comment by abernix** [comment]
I'll reopen this for now but this is going to be very difficult for someone here to debug.  Have you tried simply specifying those options in the URL options?

e.g. `?authSource=admin&replicaSet=rs0&connectTimeoutMS=10000&socketTimeoutMS=10000` or higher values?  They should be [supported in the URI](https://mongodb.github.io/node-mongodb-native/driver-articles/mongoclient.html#connection-configuration).

**Comment by dr-dimitru** [comment]
Already [tried yesterday](https://github.com/meteor/meteor/issues/7492#issuecomment-235399340), but to me it feels like ignored.

What about `Mongo.setConnectionOptions()`? Any chance to set something via this method?

**Comment by abernix** [comment]
Yup!  But #7455 makes it a bit tricky if you have any packages that use `Mongo.Collection`'s.  Ideally, for testing purposes, I'd recommend making a separate 1.4 project that has no `accounts` packages (or any other packages that might use a collection) and then similar to my instructions in this post:

https://forums.meteor.com/t/meteor-with-the-new-mongodb-3-2-1-compose-io/17763/11?u=abernix

Set the options like this:

```js
Mongo.setConnectionOptions({
  mongos: {
    socketOptions: {
      connectTimeoutMS: 30000,
      socketTimeoutMS: 30000,
    },
  },
});
```

(I _believe_ that to be right based on the [2.2 driver API](https://mongodb.github.io/node-mongodb-native/2.2/api/MongoClient.html) + [Mongos options](https://mongodb.github.io/node-mongodb-native/2.2/api/Mongos.html))

**Comment by arggh** [comment]
Same here. I've been trying two days to deploy, no luck.

```
=> Starting meteor app on port:80
[server] 
[server] /bundle/bundle/programs/server/node_modules/fibers/future.js:313
						throw(ex);
						^
[server] MongoError: no primary found in replicaset
[server]     at Object.Future.wait (/bundle/bundle/programs/server/node_modules/fibers/future.js:449:15)
[server]     at new MongoConnection (packages/mongo/mongo_driver.js:216:27)
[server]     at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
[server]     at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
[server]     at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
[server]     at new Mongo.Collection (packages/mongo/collection.js:103:40)
[server]     at AccountsServer.AccountsCommon (packages/accounts-base/accounts_common.js:23:18)
[server]     at new AccountsServer (packages/accounts-base/accounts_server.js:18:5)
[server]     at meteorInstall.node_modules.meteor.accounts-base.server_main.js (packages/accounts-base/server_main.js:9:12)
[server]     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
[server]     - - - - -
[server]     at /bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/replset.js:558:32
[server]     at [object Object].<anonymous> (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/replset.js:385:24)
[server]     at [object Object].g (events.js:260:16)
[server]     at emitOne (events.js:77:13)
[server]     at [object Object].emit (events.js:169:7)
[server]     at [object Object].<anonymous> (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:295:21)
[server]     at emitOne (events.js:77:13)
[server]     at [object Object].emit (events.js:169:7)
[server]     at [object Object].<anonymous> (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:251:12)
[server]     at [object Object].g (events.js:260:16)
```

I did as told in issue #7450, then I got this. I have a three node Mongo replica set, where if I check the status with rs.status() I get all three members fine and healthy, one of them being the primary.

**Comment by arggh** [comment]
Thought I'd share all the strategies I've tried so far:

1) Deploying with mupx like with 1.3, as we know, it doesn't work

2) Then switching to deployment using:

- muproackanew -version of mupx
- meteor up using the `abernix/meteord:base` by @abernix 
 
-> `MongoError: no primary found in replicaset` when starting the app.

I have set the replicaSet query parameter on both `MONGO_URL` and `MONGO_OPLOG_URL` and tried the `connectTimeoutMS`and `socketTimeoutMS` parameters as well, with no effect.

I also tried creating a package that would call the `Mongo.setConnectionOptions`-function setting those same parameters before the accounts-packages (as instructed in another, possibly related, issue), but it didn't help either .

Then I remove the `METEOR_OPLOG_URL` from mup.js and set the `MONGO_URL` pointing only to the primary Mongo-instance (without the replicaSet specified), and the deployment goes fine and the app starts. 

If I point it to any of the secondaries, starting the app fails as expected.

I don't know what to do.

**Comment by dr-dimitru** [comment]
An update:
 - Upgraded app to Meteor@1.4.0.1
 - Tested `Mongo.setConnectionOptions()`
 - Tested `Mongo.setConnectionOptions()` via package which loads fist

No luck, same error: `MongoError: no primary found in replicaset`

**Comment by mjmasn** [comment]
If anybody is using a Mongo server with IP whitelisting (e.g. the new MongoDB Atlas service, Compose if you turn that setting on) - you will get this error if you haven't added the relevant server IP to your whitelist. The error message sort of makes sense when you think about how it works but it's definitely not clear.

**Comment by arggh** [comment]
@mjmasn : I suppose that the whitelisting is a setting offered by Atlas- or Compose.io -services, not MongoDB itself?

In my case, my app servers are connected to the Mongo servers with VPN, so they share the same secure private network. If I ditch the replicaSet-parameters (and the secondary servers) from my MONGO_URL, everything works and my app can connect to the primary Mongo instance. If I try to use the replicaSet (and OPLOG), Meteor complains about the missing **primary** in replica set when deploying.. so frustrating.

My setup worked like a dream **before Meteor 1.4**.

**Comment by dr-dimitru** [comment]
@mjmasn 
My situation is same with @arggh , no changes have been made to MongoDB server, although I use external IPs it was working __before Meteor 1.4__.

And it keeps working with any dedicated/vps machine, but not Heroku.

**Comment by mjmasn** [comment]
@arrgh / @dr-dimitru was just a suggestion based on my experience but there's probably a lot of reasons why you might see that error. Have you tried creating a new Meteor 1.4 app `meteor create my-app` with a collection or two and deploying that to your server/heroku with the same connection settings?

I have to say the probability is that it's a config issue, not a Meteor issue. With regards to it working on a VPS but not Heroku, then the issue would seem to be with the Heroku configuration. Are you sure you're deploying the correct version of the app, correct version of Node, and all the correct environment variables. What happens if you create a new heroku app/config and deploy your app there?

If anyone can come up with a minimal reproduction on a test database and stick it in a public GitHub repo someone will probably be able to help.

**Comment by dr-dimitru** [comment]
Related: https://github.com/mafintosh/mongojs/issues/319

**Comment by abernix** [comment]
@dr-dimitru As the issue is with the _actual_ Mongo driver (as supplied by Mongo), I suggest you follow the official Native Mongo Driver issue which covered this here: https://jira.mongodb.org/browse/NODE-753 (and related)

Your configuration sounds very, very similar to others in that thread and it sounds like they are claiming it is an implementation prone to failure and thus why it is no longer supported.  It does sounds like they will discuss it internally at Mongo and consider any additional changes they may want to make, so if you become aware of an official change that they make to the driver to resolve your problem, please report back.

**Comment by arggh** [comment]
Thanks @dr-dimitru and @abernix for pointing in the right direction: after changing the host names of my replica set members everything works again. Happy times.

**Comment by abernix** [comment]
Glad you got it fixed, @arggh.

I'm more convinced than ever that this is just a misconfiguration of the Mongo server.  I understand that these things are tricky, but hopefully everyone understands this is simply a long-overdue change from Mongo themselves that simply needs to get worked through.  They have definitely changed things but Mongo's best practices have changed as well and I think they're just trying to enforce those.

Closing as the solution lies in a proper Mongo configuration.

**Comment by dr-dimitru** [comment]
@abernix thank you.
Fixed via assigning domain name to server with mongo
Using same domain name in Replica Set configuration on MongoDB server and in connection strings

**Comment by abernix** [comment]
Glad to hear it!  (And glad that I now know that this is the specific issue!)

**Comment by dr-dimitru** [comment]
@abernix thank you for help and patience. Probably it should me mentioned somewhere in docs about production stage.

In case someone will came here in a future - [tutorial for Replica Set with OpLog](https://veliovgroup.com/article/2qsjtNf8NSB9XxZDh/mongodb-replica-set-with-oplog), *I'll keep it updated*, additions, suggestions and comments is always welcome.

**Comment by abernix** [comment]
No worries, and nice tutorial!  I think an issue on the meteor/guide repo _might_ be welcome for discussion and possible inclusion, but I'm not sure it will be accepted.  

Unfortunately, I think the configuration of a production Mongo server, let alone a Replica Set, is far outside the scope of Meteor and best left to outside resources both for security and practicality.  Anyway, you might see where it goes!  I'm sure this issue alone will help many people. :)

**Comment by timbrandin** [comment]
This is still an issue for hosting on an internal VPN with hosts alias et al, suggest you upgrade the mongo driver to 2.2.1 which relaxes the requirement for correct anything.
https://jira.mongodb.org/browse/NODE-746

**Comment by abernix** [comment]
@timbrandin Meteor 1.4.3 (coming _very_ soon) will come with the Node Mongo Driver v2.2.16 and definitely includes [NODE-746](https://jira.mongodb.org/browse/NODE-746).

**Comment by tzapu** [comment]
i still seem to be having this issue on meteor 1.4.3 & 1.4.3.1

**Comment by allenfuller** [comment]
I ran into this issue this afternoon and it turned out to be an issue with IP address whitelisting on MongoDB Atlas. Double checking the IP fixed it.

**Comment by AndreasGalster** [comment]
It seems to me the only way people fixed this is with replicaSets? How can we resolve this with Compose? I've followed the guys, it's still complains about no replicaSet being used.

**Comment by abernix** [comment]
@AndreasGalster Are you sure there aren't multiple hosts which should be included in that `MONGO_URL`?  (e.g. `MONGO_URL=mongodb://user:password@aws-us-east-1-portal.9.dblayer.com:12345,aws-us-east-1-portal.19.dblayer.com:54321/staging?ssl=true` – note the comma `,`).

**Comment by AndreasGalster** [comment]
Yes, I've tried both, does not work :/ We set up a brand new deployment on Compose, db user rights are same as on our old Classic account but it just won't work. We've tried tinkering with this for hours already without success :(

**Comment by abernix** [comment]
@AndreasGalster Meteor (and Nodel.js) can absolutely handle multiple – that article is very out of date.

**Comment by AndreasGalster** [comment]
I think I've been able to track it down a bit further. This seems to be related to one of the packages installed. https://forums.meteor.com/t/meteor-with-the-new-mongodb-3-2-1-compose-io/17763/10 Following this guide works **if** we remove all packages. So far it seems to be related maybe to CFS or Blaze templating, trying to reproduce it as much as I can by bringing packages one by one.

**Comment by drone1** [comment]
Holy crap, did no one solve this? I'm running into this now.

Things I did recently: 

* Changed Atlas password and roles for admin account.
* npm i -g npm (update to npm v5.1.0)
* meteor add accounts-ui accounts-password
* meteor add alanning:roles

**Comment by Mklueh** [comment]
I´m running in the same error now on my local machine trying to deploy with docker-compose and a custom Docker image

**Comment by MichaelJCole** [comment]
Hi, I'm also running into this issue with completely different versions of everything. (Meteor 1.8, mongDB 4)

In docker compose, I found the replica sets were not configuring quickly enough for Meteor to connect.  Appending the timeouts didn't seem to have an effect (a 10 seconds timeout, should take well 10 seconds before throwing an error)

Adding `restart: always` to the Meteor image let's meteor thrash around a bit before finally connecting.

**Comment by tmihelcich** [comment]
I was also getting this error after I switched my cluster to MongoDB Atlas hosted in AWS us-east-1.
Turns out, I had to upgrade my Galaxy app to Pro (to enable IP whitelisting), when I enabled whitelisting it gave me some IP addresses that I needed to add to my MongoDB Atlas whitelist. Once I added them, I was able to connect without error, no problem.
