### ISSUE TITLE
Have different timeouts for expiration of password reset and enrollment

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#7794]
#7534 introduced token expiration, but one could want a different expiration for password reset and enrollment (or even disable expiration for enrollment).

We could address this by adding a reason for token to the database, and then use different expiration based on that reason.

**Comment by tmeasday** [comment]
I think this is a reasonable approach. So what would the key look like?

**Comment by mitar** [comment]
`reason: 'reset'` or `reason: 'enroll'`

**Comment by tmeasday** [comment]
So the token would look like:

```
  var tokenRecord = {
    token: token,
    email: email,
    when: when,
    reason: 'reset' | 'enrol'
  };
```

That makes sense to me. And we would add a separate option for setting the two timeouts and add two intervals to do the checks?

**Comment by mitar** [comment]
Yea.

**Comment by tmeasday** [comment]
Ok, I'll mark PR-encouraged then.

**Comment by alphanso** [comment]
@tmeasday I have created a PR for this issue. Please check.

**Comment by mitar** [comment]
This has been resolved.

**Comment by zarvox** [comment]
The patch which purported to fix this issue appears to have a showstopper bug which causes enrollment tokens to be cleaned up under the reset token expiry rules.  The net effect is that under the default settings, enrollment tokens are still destroyed after 3 days, rather than after 30 days, and enrollment tokens can't stay in the database longer than password reset tokens.

In particular, when processing password reset token expiry at https://github.com/meteor/meteor/pull/7817/files#diff-2ae5b6c36ab4132c1a2d0e33b5fd8443R1158 a `tokenFilter` with an `$or` specifying the appropriate token reason is passed to `expirePasswordToken`, but in https://github.com/meteor/meteor/pull/7817/files#diff-2ae5b6c36ab4132c1a2d0e33b5fd8443R1081 that `$or` clause is overwritten by the one which only looks at the `when` field.  Perhaps the two clauses should be added to an `$and` clause instead?

We're working around this by bumping the validity duration of password reset tokens, but figured you'd want a heads-up that `passwordEnrollTokenExpirationInDays` is basically broken.

Let me know if I should file this as a new issue.

**Comment by abernix** [comment]
@zarvox Thanks for reporting this!  Please do file this as a new issue so it doesn't get lost on this closed issue!  Additionally, if you can offer any help to fix it, that would be much appreciated (a pull request would be awesome!).

**Comment by phuongvietle** [comment]
Is this finally resolved?

**Comment by timmakken** [comment]
Im still having issues with enrollment so i guess not...
Running meteor@1.5 with accounts-base@1.3.0 but it looks like the token generated has a when property with a date obj in it thats milliseconds off the user creation time( in my case ). i tried manually setting the date to ensure the token would be valid but it keeps giving the error "token expired". im not sure what im doing wrong.

also `Accounts.config({ passwordEnrollTokenExpirationInDays: 40 });` does not seem to affect this value.
