### ISSUE TITLE
[1.4.3.1] Android SDK not found with Android SDK 25.3.0 or higher.

### ISSUE THREAD

**Issue by YannLeBihan** [meteor/meteor#8464]
Hi,

Tried this today on two different machines running macOS Sierra 10.12.3 :

1) Fresh install of Meteor
2) Fresh install of Android Studio 2.3 + all possible SDK platforms
3) Create a Meteor project, cd to its directory
4) Run `meteor add-platform android`

Always got the same errors :

`✗ Android target: Android SDK not found. Make sure that it is installed. If it is not at the default location, set the ANDROID_HOME environment variable.`

`✗ Gradle: Could not find gradle wrapper within Android SDK. Might need to update your Android SDK.`

Here's what I tried :

1) Checked `$ANDROID_HOME` and `$PATH` after setting them like said in the [Meteor Guide](https://guide.meteor.com/mobile.html#installing-prerequisites) : both are OK;
2) Downgraded Android Studio to its previous version (2.2.3) that had been working up to yesterday : same result, even after removing all Android Studio support and pref files;
3) Ran several times `meteor remove-platform android` and `meteor add-platform android` : same errors;
4) Removed all SDK platforms from Android Studio, reinstalled just Android 5.1, then tried the same with Android 7.1.1 : ditto.

I'd like to know if others are experiencing the same issue, and if they found a solution or workaround.

Thanks in advance !

**Comment by robertross** [comment]
+1 

Yes same here!
Pretty much exact same scenario with me.  Took the same steps as you outlined and have failed to get it working.

**Comment by abernix** [comment]
Meteor 1.4.3.1 uses Cordova 6.4.0 which I'm fairly sure requires Android SDK version 25 to be installed with the Android Studio SDK Manager (whereas previous versions used 24 or 23).  I just updated the Guide to reflect this (see above commit) as I'm almost positive this is required.  We should probably update `History.md` too in order to make sure this is clear, but do you mind confirming first if this fixes your issue?

If you don't have the full Android Studio, you should be able to start the SDK Manager with something like:

    $ANDROID_HOME/bin/android sdk

Can you report back if this works for you and we'll get the `History.md` updated with that note?

**Comment by YannLeBihan** [comment]
Thank you for your answer. Meanwhile, I have installed Android SDK version 25 twice :
1) first with Android Studio's integrated tool, which led to the same errors
2) then with the standalone version I had kept from a previous SDK folder : after this second try, things started to get better, Meteor was able to build for Android again.

But as soon as I tried to bring Android Studio to the party (to build signed apks, manage virtual devices, etc.) it prompted me to upgrade some tools in that folder, including Gradle : I accepted the upgrade, which broke things again.

I then took a look into Gradle's former folder : it had been moved elsewhere - hence the Meteor/Cordova error about Gradle, I guess.

Will now try to get a stable setup by reusing a copy of this folder and not doing the faulty Gradle upgrade, to see if it is a viable workaround.

**Comment by YannLeBihan** [comment]
OK, I can now confirm that the most recent updates in Android Studio (SDK Tools + Gradle) break the link between Android and Meteor/Cordova, at least on the Mac : just updating the SDK Tools to latest version is enough to raise the errors I described in my first post, with no obvious way to fix them.

As for Gradle, Meteor tries to find it inside `/tools/templates/gradle/`, but the `templates` directory disappears after the SDK Tools upgrade.

The only workaround I found up to now is to reuse an old `android-sdk-macosx` folder from a previous install, to point Android Studio to that folder rather than its default SDK folder, and to refuse updating SDK Tools and Gradle when prompted to. This way, I can fire `meteor run android`, `meteor run android-device` and `meteor build` with success. Updates are done by double-clicking on `android-sdk-macosx/tools/android` rather than through Android Studio.

It seems to work for the moment, but I don't know if it will be useable for production very long.

An advice to those who would be willing to try this workaround : above all, keep a zipped backup of your previous SDK folder next to it before touching anything.

**Comment by abernix** [comment]
@YannLeBihan I'll have to revisit this because I tested Meteor 1.4.3 with Cordova 6.4.0 on macOS Sierra before we released Meteor 1.4.3.x and it worked fine.

Also, my above command for running the SDK Manager was incorrect, my apologies.  It should have been:

    $ANDROID_HOME/tools/android sdk

(Note `tools` instead of `bin` – I've corrected the above comment to avoid confusion by others).

In case it's any help, here's what my SDK Manager looks like:

![image](https://cloud.githubusercontent.com/assets/841294/23706332/6dc7dd62-0416-11e7-8a02-f5d48b4f05d1.png)

This also seems to possibly be a trending issue right now as a search for the following returned a number of active issues, such as [this one](https://forum.ionicframework.com/t/error-could-not-find-gradle-wrapper-within-android-sdk/79527):

    Could not find gradle wrapper within Android SDK. Might need to update your Android SDK.

Hope this helps until someone can look at this more!

**Comment by robertross** [comment]
@abernix 

So I'm running Mac Os El Capitan 10.11.6.

`$ANDROID_HOME/tools/android sdk`

Still seems incorrect I'm afraid. It gives me...

```
The android command is no longer available.
For manual SDK and AVD management, please use Android Studio.
For command-line tools, use tools/bin/sdkmanager and tools/bin/avdmanager
```

I can run sdkmanager using that path.. have check installed all relevent pacakges for platform-25  but still seeing...

meteor run android-device ........

```
Getting installed version for platform android in Cordova project
Checking Cordova requirements for platform Android
                                              
Your system does not yet seem to fulfill all requirements to build apps for Android.
                                              
Please follow the installation instructions in the mobile guide:
http://guide.meteor.com/mobile.html#installing-prerequisites
                                              
Status of the individual requirements:        
✓ Java JDK                                    
✓ Android SDK                                 
✗ Android target: Android SDK not found. Make sure that it is installed. If it is not at the default location, set the ANDROID_HOME environment variable.
✗ Gradle: Could not find gradle wrapper within Android SDK. Might need to update your Android SDK.
  Looked here: /Users/robertross/Library/Android/sdk/tools/templates/gradle/wrapper
```

Has anyone any more insight into what's happening here?

Unfortunately @YannLeBihan 's Suggested workaround of pointing to an older android-sdk-macosx directory isn't practical for me.

**Comment by loredanacirstea** [comment]
Solved by replacing the new updated 25.3.1 Android SDK Tools with version 25.2.5:
- download it from http://dl-ssl.google.com/android/repository/tools_r25.2.5-macosx.zip 
- (possibly optional) uninstall Android SDK Tools 25.3.1 from the SDK Manager
- replace the `tools` folder from `/Users/username/Library/Android/sdk` with the new one


I had the same issues after this morning's update: Android Studio to ver. 2.3, Feb 24 build + sdk&co. 
Meteor ver. 1.4.3.1
Mac OS Sierra 10.12.3

```
✓ Java JDK                                    
✓ Android SDK                                 
✗ Android target: Android SDK not found. Make sure that it is installed. If it is not at the default location, set the ANDROID_HOME
  environment variable.
✗ Gradle: Could not find gradle wrapper within Android SDK. Might need to update your Android SDK.
  Looked here: /Users/loredana/Library/Android/sdk/tools/templates/gradle/wrapper
```

**Comment by robertross** [comment]
@loredanacirstea Yes that worked for me also. 

Thanks for the workaround and the link.

I did not have to uninstall Android SDK Tools 25.3.1, I just switched out the tools folder. Feels wrong though.

**Comment by abernix** [comment]
I certainly didn't test with Android SDK Tools 25.3.x, but rather 25.2.5 as you can see in my screenshot.  Android SDK Tools 25.3 (which came out after Meteor 1.4.3) [definitely has a lot of breaking changes](https://developer.android.com/studio/releases/sdk-tools.html) according to their release notes.

This will need to be looked at and if anyone who uses Cordova on a more regular basis is able to look into it, it would be greatly appreciated.  

Unfortunately, it's not a regular occurrence for deep-dives into Cordova so this may take a bit to get resolved.  Furthermore, the changes appear substantial, though I'm hoping that's just at first glance.  The good news is that if you stick with Android SDK 25.2.5 (or anything in the 25.x series before 25.3.0) for the time being, you should be okay; my builds still work properly with 25.2.5.

I've updated the Guide to clarify this limitation with https://github.com/meteor/guide/commit/adc963a2ebdef1004f38a5677b2e8ea8c0075e4e.

Help requested!

**Comment by eric-burel** [comment]
This link does provide working SDK tools 25.2.3 : [http://androidsdkoffline.blogspot.fr/p/android-sdk-tools.html](url).
It has been succesfully tested on Debian, simply following the process proposed by @loredanacirstea

**Comment by abernix** [comment]
The 25.2.3 tools are still linked from the [official Android source](https://developer.android.com/studio/index.html#downloads) (at the very bottom), so no need to use the blogpost link at the current moment (Though they appear to point to the same, official sources):

https://developer.android.com/studio/index.html#downloads

**Comment by dnish** [comment]
I guess the Cordova team is working on it:

https://issues.apache.org/jira/browse/CB-12554

**Comment by fcacheda** [comment]
Thanks a lot for the help. I managed to change the tools directory and move on from the Android SDK error. However, now I get an error regarding gradle plugin.
In fact when I try to access with my browser to the URL for the pom, there is a 404 Not found error.

Any ideas about what's going on?

`   FAILURE: Build failed with an exception.
   
   * What went wrong:
   A problem occurred configuring root project 'android'.
   > Could not resolve all dependencies for configuration ':classpath'.
   > Could not resolve com.android.tools.build:gradle:2.2.1.
   Required by:
   :android:unspecified
   > Could not resolve com.android.tools.build:gradle:2.2.1.
   > Could not get resource
   'https://repo1.maven.org/maven2/com/android/tools/build/gradle/2.2.1/gradle-2.2.1.pom'.
   > Could not GET
   'https://repo1.maven.org/maven2/com/android/tools/build/gradle/2.2.1/gradle-2.2.1.pom'.
   > sun.security.validator.ValidatorException: PKIX path building failed:
   sun.security.provider.certpath.SunCertPathBuilderException: unable to find
   valid certification path to requested target
   > Could not resolve com.android.tools.build:gradle:2.2.1.
   > Could not get resource
   'https://jcenter.bintray.com/com/android/tools/build/gradle/2.2.1/gradle-2.2.1.pom'.
   > Could not GET
   'https://jcenter.bintray.com/com/android/tools/build/gradle/2.2.1/gradle-2.2.1.pom'.
   > sun.security.validator.ValidatorException: PKIX path building failed:
   sun.security.provider.certpath.SunCertPathBuilderException: unable to find
   valid certification path to requested target`

**Comment by MrGarrowson** [comment]
I'm on Linux, I uninstalled android-studio and only installed tools and platform tools.  I installed tools_r25.2.5-linux.zip and I still have a problem.
`Status of the individual requirements:        
✓ Java JDK                                    
✓ Android SDK                                 
✗ Android target: Android SDK not found. Make sure that it is installed. If it
  is not at the default location, set the ANDROID_HOME environment variable.
✓ Gradle  `

this is in my .bashrc, although I doubt it is a problem with the PATH

`export ANDROID_HOME=/opt/Android/Sdk
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/platform-tools
export PATH=$PATH:$ANDROID_HOME/build-tools
`

**Comment by abernix** [comment]
@MrGarrowson What happens if you type the following at your command prompt?

    echo $ANDROID_HOME

and...

   ls -la $ANDROID_HOME/

It's entirely possible that you should have `$ANDROID_HOME/bin` in your path too as that is where the `android` command itself lives.  For example, you should be able to run `android sdk` on your console and the SDK manager should load.

**Comment by MrGarrowson** [comment]
@abernix Thanks for the reply, 
`echo $ANDROID_HOME`
prints
`/opt/Android/Sdk`
and
`ls -la $ANDROID_HOME/`
prints
`total 28`
`drwxr-xr-x  6 root root 4096 mar 19 19:47 .`
`drwxr-xr-x  3 root root 4096 mar 19 19:13 ..`
`drwxr-xr-x  3 root root 4096 mar 19 19:47 build-tools`
`-rw-r--r--  1 root root   16 mar 19 22:07 .knownPackages`
`drwxr-xr-x  5 root root 4096 mar 19 22:07 platform-tools`
`drwxr-xr-x  2 root root 4096 mar 19 19:47 temp`
`drwxr-xr-x 12 root root 4096 mar 19 19:36 tools`

I don't have $ANDROID_HOME/bin and if I run `android sdk` it tells me command not found, I think that's it, thank you very much. I'll go  to /opt/Android/Sdk and run android update sdk and install it.

**Comment by abernix** [comment]
@MrGarrowson You can put the tools where ever you would like, including in your home directory, you just need to make sure that `$ANDROID_HOME` points to where that is and that the `PATH` uses the `$ANDROID_HOME` variable (remember, order is important here).  You can evaluate your current "`PATH`" by running `echo $PATH`.

Assuming the permissions are corrected and that your `PATH` is as you specified, you should have no problem running `android` since the `android` command should be in the `/opt/Android/Sdk/tools` directory.  If you continue to have problems, I may recommend installing the larger Android Studio which might take care of some things for you, including permissions and SDK location.

**Comment by Atout-Agile** [comment]
On mint 18.1 (cinnamon) , I had exact same issue (on a fresh install).

   - removed directory  /Android/sdk/**tools**

   - downloaded https://dl.google.com/android/repository/tools_r25.2.3-linux.zip

   - Unziped 
~~~
    cd path/where/you/unzipped
    sudo move tools path_to/Android/sdk
~~~
Then when I issue  `meteor add-platform android` I get : 
`
Subproject Path: CordovaLib                  /
Subproject Path: CordovaLib                  \
Subproject Path: CordovaLib                  \
android: added platform  
`
Passed.

@abernix  Thank you for updating doc. I'm not familiar with meteor, it was really helpful.

**Comment by petrometro** [comment]
I confirm this worked for me too.

**Comment by YeelerG** [comment]
yeah. It works. Thanks a lot, Atout-Agile.
Actually, SDK Tools version 25.2.5 works too.

http://mirrors.neusoft.edu.cn/android/repository/tools_r25.2.5-linux.zip
https://developer.android.com/studio/releases/sdk-tools.html

**Comment by adamgins** [comment]
Hi, trying to back track here... I upgraded my Android Studio to 2.3.1 and everything went south with 
`CordovaError: Could not find gradle wrapper within Android SDK. Might need
   to update your Android SDK.`

I am guess it's to do I have `26` in the SDK tools... here

<img width="744" alt="screen shot 2017-04-13 at 8 42 51 am" src="https://cloud.githubusercontent.com/assets/7233741/24982756/79a998ce-2026-11e7-8b17-02cb9baca3fe.png">
<img width="654" alt="screen shot 2017-04-13 at 8 43 20 am" src="https://cloud.githubusercontent.com/assets/7233741/24982760/7f1da840-2026-11e7-8036-4fca1c59df1b.png">
<img width="707" alt="screen shot 2017-04-13 at 8 43 28 am" src="https://cloud.githubusercontent.com/assets/7233741/24982764/8315c932-2026-11e7-9370-b397da0e8f04.png">
<img width="710" alt="screen shot 2017-04-13 at 8 43 38 am" src="https://cloud.githubusercontent.com/assets/7233741/24982767/8780475e-2026-11e7-9dbb-184f57ae5e2f.png">

Do I need to uninstall Android Studio or can I just install http://mirrors.neusoft.edu.cn/android/repository/tools_r25.2.5-linux.zip ?

(any quick instructions would be awesome)

Any help appreciated

ps. would be good to have some instructions/warnings in the guide https://guide.meteor.com/mobile.html#installing-prerequisites-android

**Comment by YeelerG** [comment]
Have you tried to run "meteor run Android"? I got an error in Elementary OS

**Comment by kurapikats** [comment]
@Atout-Agile your solution worked for me.
I'm on **OSX Sierra**, using **Meteor 1.4.4.1** with **Android Studio 2.3.1**
Here's the download url for sdk tool
https://dl.google.com/android/repository/tools_r25.2.3-macosx.zip

Thank you!

**Comment by nanu-c** [comment]
> I guess the Cordova team is working on it:
> 
> https://issues.apache.org/jira/browse/CB-12554

In this issue was resolved on 29/Mar/17 18:18  so we can include the new version of cordova?

**Comment by maciejsaw** [comment]
It took me 2 hours to figure out how to build Android for older version of Meteor (1.1), which I needed to do because Xervo/Modulus shut down their hosting. 

1. You need to download this file and replace the "tools" folder in the ~/Library/Android/sdk/ 
https://dl.google.com/android/repository/tools_r23.0.1-macosx.zip 

2. You need to install SDK version 22 with SDK manager that comes with Android Studio

**Comment by adamgins** [comment]
Hi anyone having this issue https://github.com/meteor/meteor/issues/8655 running the emulator after apply this hack?

**Comment by qaoo8** [comment]
The solution worked for me too. by add the platform to Android after install the Android SDK 25.2.5; 
but when i run " meteor run android-device  --verbose" the Meteor can add the app to my device???

WARNING: You are testing your app on a remote device. For the mobile app to be able to connect to the local server, make sure your device is on
         the same network, and that the network configuration allows clients to talk to each other (no client isolation).
Running Cordova app for platform Android with options --device
ANDROID_HOME=/home/jackylee2/android-sdk-linux/
JAVA_HOME=/home/jackylee2/jdk1.8.0_101
Subproject Path: CordovaLibDevice            /
Downloading http://services.gradle.org/distributions/gradle-2.14.1-all.zip
=> Started your app.                          
                                              
=> App running at: http://localhost:3000/

the operation keep running at here and can not add the app to my device, please help!!!

**Comment by adamgins** [comment]
@qaoo8 I think this is a similar issue to me see here https://github.com/meteor/meteor/issues/8655
I can do a build... but cannot get meteor to run the app on the emulator or device

**Comment by kepler** [comment]
I was having exactly the same issue as the OP. After reading in the [release notes](https://developer.android.com/studio/releases/sdk-tools.html) that in version 26.0.0
> tools/android now attempts to reproduce the functionality of android in tools prior to version 25.3.0 by invoking the new tools
I updated it and now `cordova requirements` stopped complaining:
```
Requirements check results for android:
Java JDK: installed 1.8.0
Android SDK: installed true
Android target: installed android-25
Gradle: installed /Applications/Android Studio.app/Contents/gradle/gradle-3.2/bin/gradle
```

**Comment by ray-kay** [comment]
What exactly did you update @kepler ?

**Comment by kepler** [comment]
Sorry, should have been more specific. I updated Android SDK.

That said, standalone Cordova started working after, but not Meteor. I can take another look and post more details, if needed.

**Comment by skirunman** [comment]
I can confirm with Meteor 1.4.4.2 (Cordova Android 6.1.1) running on MacOS Sierra 10.12.4 that the build process is still broken with Android SDK tools 26.0.x (26.0.3 tested with Android Studio 2.3.1, did not test with 2.3.2 released today). Looks like this could be resolved if we upgraded to Cordova Android 6.2.0. I'd like to see us upgrade entire Cordova suite including to Cordova Android 6.2.2 ASAP. See https://github.com/meteor/meteor/issues/8686 

Resolved build issue as per above by manually installing SDK tools 25.2.5

**Comment by kwuite** [comment]
+1

Confirmed with Meteor 1.4.4.2 running on windows 8.1. I downloaded the tools from: http://dl-ssl.google.com/android/repository/tools_r25.2.5-windows.zip and replaced the tool folder, installed Android 6.x.x and got it working again.

**Comment by kepler** [comment]
Confirming, this time with version numbers: under macOS Sierra (10.12.4), Android SDK Tools 26.0.2, Meteor 1.4.4.2, the build process is broken.

Using a standalone cordova 7.0.0 installation, the build process works (on a different project).

**Comment by shakealot** [comment]
In the guide is written : "Meteor 1.4.3.1 or later: Android SDK Tools v.25.2.x (mac, linux, windows) or v.26.0.0 or later"
v.26.0.2 is not working too :/ 
We have to stick to v.25.2.5

**Comment by skirunman** [comment]
@shakealot Yes, this change https://github.com/meteor/guide/pull/634/files#diff-7c5cee7ce6ee93fca4d840ccf414e0c6R127 should not have been merged (yet). We need to fix the underlying issue https://github.com/meteor/meteor/issues/8686

**Comment by layik** [comment]
If you land here and you are using OSX make sure you follow @maciejsaw's latest by downloading
https://dl.google.com/android/repository/tools_r23.0.1-macosx.zip

**Comment by skirunman** [comment]
@layik No quite true as you can use any version of Android SDK tools up to v25.2.5
https://dl.google.com/android/repository/tools_r25.2.5-macosx.zip

**Comment by mibcadet** [comment]
Still not working ?

**Comment by skirunman** [comment]
If you can please test the [Meteor 1.5.3-beta.4 release](https://github.com/meteor/meteor/tree/release/METEOR%401.5.2-beta.4) with latest Android SDK tools v26.x.x, which includes the update to [Cordova Android v6.2.3](https://cordova.apache.org/announcements/2017/05/04/android-release.html).

**Comment by ignacy130** [comment]
@skirunman I believe it is 1.5.**2**-beta.4 :)

**Comment by skirunman** [comment]
@ignacy130 Yep, thanks, fixed typo!

**Comment by scottburch** [comment]
Do we have any idea on when this will be resolved?  We are using BuddyBuild for our Android/iOS build, which is failing because they are using the newer Android SDK.  I can probably do the hack to the build.gradle file that allows it to work but I don't know how to hook into the build cycle to make the change.  I'm still working on that.

Thanks

**Comment by skirunman** [comment]
@scottburch If can install and use [Meteor v1.5.2-beta.8](https://github.com/meteor/meteor/tree/release/METEOR%401.5.2-beta.8) then you should be able to build with the latest versions of Android. Not sure when office 1.5.2 release will drop, but guessing soon.

**Comment by scottburch** [comment]
Yes, we did that and now we get the other error about the Manifest merge with SDK 26.

**Comment by skirunman** [comment]
We were experimenting with BuddyBuild and ran into some issues. However, we are able to build just fine on MacOS. Can you build you app on your local dev machine with 1.5.2-beta.8 and Android SDK tools v26.x.x?

**Comment by scottburch** [comment]
@skirunman We just got done working with BuddyBuild to get the build working with 1.5.2-beta.8.  We still have a little bit of work to do, as soon as we have verified the builds on the mobile devices I will update this thread with the patch that we have and how we used it.

**Comment by scottburch** [comment]
@skirunman Here is our buddybuild_postclone.sh file.  We had to include a patch for a known issue as well as the directions from the buddybuild instructions to build meteor.  

IMPORTANT: In addition, the BB guy had to set a flag to stop the BB build from doing the cordova step since meteor was doing that already which caused the build to fail.

buddybuild_postclone.sh
---------
curl https://install.meteor.com/ | sh
yarn (or npm install, we are using yarn)
meteor build $PLATFORM --server $SERVER

cat bbgradle.patch >> .meteor/local/cordova-build/platforms/android/build.gradle


bbgradle.patch
----------
configurations.all {
resolutionStrategy.eachDependency { DependencyResolveDetails details ->
def requested = details.requested
if (requested.group == 'com.android.support') {
if (!requested.name.startsWith("multidex")) {
details.useVersion '25.3.0'
}
}
}
}

**Comment by skirunman** [comment]
@scottburch  Thanks, we may give this a try again.

**Comment by derwaldgeist** [comment]
Ran into the same issue after upgrading my Android Studio installation for other reasons. I cannot upgrade to Meteor 1.5.1+, since it breaks my app due to #8950. Will the Cordova fix be downported to 1.5?

**Comment by narigondelsiglo** [comment]
@derwaldgeist I've got it working again with the updated Android Studio version by updating meteor to the next 1.5.2 version (in beta for now).
To update your local project you need to issue:
`
$ meteor update  --release 1.5.2-beta.8
$ meteor remove-platform android
$ meteor add-platform android
`

**Comment by derwaldgeist** [comment]
Unfortunately, I cannot update to 1.5.2 until #8950 has been fixed.
I solved this problem here by manually installing SDK 25.2.5 again.

**Comment by fcacheda** [comment]
Thanks @narigondelsiglo, it worked for me, with android-25.

**Comment by AprilMorone** [comment]
I came across this same issue when running Cordova Android and SDK on Ubuntu via Terminal. But, if I tried downloading Android Studio, instead, of non-zip linux file extension through the terminal - not the liinux zip file of Android Studio website - same issue upon trying to do Cordova build android command. However, when I'd downloaded then used the Android Studio linux zip file, I couldn't find the apk file. I'd have have to change where certain files are located before I could do the build.

**Comment by lesliechw** [comment]
meteor update --release 1.5.2-beta.8

Problem gone. So we can be assured that the next version of Meteor will fix this issue.

**Comment by skirunman** [comment]
@abernix Can we close this out along with the other 6 issues tagged with Milestone 1.5.2?

We are releasing a new version of our product and just want to confirm all these issues are in fact fixed in 1.5.2. Thanks!

**Comment by abernix** [comment]
I'll close this based on the comment above from @lesliechw (Thanks, Leslie!), but the other issues on the milestone are certainly not confirmed fixed unless you or someone can help test them!  If they are still on the milestone, they are things we didn't get to and will be moved to a new milestone once they've been evaluated.  Your help would be appreciated!

**Comment by climbonbelay** [comment]
@Atout-Agile thank you for the download link

**Comment by paulincai** [comment]
@abernix just FYI as I see this is closed now. I am on Meteor 1.5.2.1, did remove and add android platform and I am getting "✗ Android target: Please install Android target / API level: "android-25"." 
I am fulfilling the requirements:
You will require:
  1. "SDK Platform" for API level android-25
  2. "Android SDK Platform-tools (latest)
  3. "Android SDK Build-tools" (latest)

**Comment by AndreyVik** [comment]
Good afternoon, I'm new
I read the previous posts, but it did not help me. Please give clear step-by-step instructions on how to get rid of errors.

MacBook-Pro-Alexey:Enter av$ meteor add-platform android
Subproject Path: CordovaLib                  \
Subproject Path: CordovaLib                  \
android: added platform                       
                                              
Your system does not yet seem to fulfill all requirements to build
apps for Android.
                                              
Please follow the installation instructions in the mobile guide:
http://guide.meteor.com/mobile.html#installing-prerequisites
                                              
Status of the individual requirements:        
✓ Java JDK                                    
✓ Android SDK                                 
✗ Android target: avdmanager: Command failed with exit code 1 Error
  output:
  Exception in thread "main" java.lang.NoClassDefFoundError:
  javax/xml/bind/annotation/XmlSchema
  at
  com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
  at
  com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
  at
  com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
  at
  com.android.sdklib.tool.AvdManagerCli.run(AvdManagerCli.java:213)
  at
  com.android.sdklib.tool.AvdManagerCli.main(AvdManagerCli.java:200)
  Caused by: java.lang.ClassNotFoundException:
  javax.xml.bind.annotation.XmlSchema
  at
  java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
  at
  java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
  at
  java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
  ... 5 more
✓ Gradle                            

SDK
![image](https://user-images.githubusercontent.com/32749702/33483340-6b71e768-d6ae-11e7-8875-5a7ce37085a8.png)

**Comment by alp1396** [comment]
Hi all.
Same problem as @AndreyVik. And there is no ideas how to fix that.
Updated the project from 1.4 to 1.5 and then to 1.6 and Installed fresh Android Studio.
Guide from [https://guide.meteor.com/mobile.html#installing-prerequisites-android](https://guide.meteor.com/mobile.html#installing-prerequisites-android) seems to be outaded because Meteor 1.6 has a new (or another) Cordova module inside and it seems like Android SDK Tools v.25.2.x doesn't supported now.
Any Ideas? 
Win10, JDK 9.0.1, Meteor 1.6, Android Studio 3.0.1, Android SDK Tools v.26.1.1

![2017-12-02_18-57-22 2](https://user-images.githubusercontent.com/3808942/33516481-2f3dac72-d795-11e7-89b2-2985446ca446.png)

**Comment by alp1396** [comment]
Problem has gone after full reinstall meteor through Choco. And changing JDK from v9 to previous 1.8
Maybe someone will helps that)

**Comment by abtx** [comment]
Same problem here, JDK 1.8, Android Studio 3.0.1, Meteor 1.6, Tools 26.1.1 on OSX Sierra

**Comment by albertkai** [comment]
same.. after updating to 1.6 the build command still worked, but after removing and adding android platform getting:
Status of the individual requirements:        
✓ Java JDK                                    
✓ Android SDK                                 
✗ Android target: No android targets (SDKs) installed!
✓ Gradle

**Comment by Rinnion** [comment]
Are you using java9? 
Remove and install java8 its work for me.
Here identical trouble:
https://stackoverflow.com/questions/46402772/failed-to-install-android-sdk

**Comment by MaxShv** [comment]
Same issue JDK 1.8, Android Studio 3.0.1, Meteor 1.6

**Comment by abernix** [comment]
@MaxShv Could you clarify what "Same issue" is by providing detailed error messages and steps?  There are a number of errors reported in this rather large and old thread.  Also, please make sure you have Android SDK 26 installed (older versions should be okay as well but 27 will be problematic for the time being).

In fact, for the sanity and reduced noise of the 37+ participants in this issue who may have having different issues, I'll lock this issue and ask that this be taken up **in a new issue**.  We're currently analyzing and attempting to address Android/Cordova issues in preparation for 1.6.2, so please do take the time to open a new issue so we can look at it!

Thanks!
