### ISSUE TITLE
[Windows] Build process sometimes crashes

### ISSUE THREAD

**Issue by steph643** [meteor/meteor#8485]
I get this exception randomly (but quite often) when recompiling:

```text
C:\Users\steph\AppData\Local\.meteor\packages\coffeescript\1.12.3_1\plugin.compileCoffeescript.os\npm\node_modules\meteor\promise\node_modules\meteor-promise\promise_server.js:190
      throw error;
      ^

Error: EBUSY: resource busy or locked, symlink 'C:\Users\steph\AppData\Local\.meteor\packages\logging\1.1.17\npm\node_modules' -> 'C:\Users\steph\Travail\Meteor\myProject\.meteor\local\.build697476.build\programs\.build324432.server\npm\node_modules\meteor\logging\node_modules'
    at Error (native)
    at Object.fs.symlinkSync (fs.js:897:18)
    at Object.wrapper (C:\tools\fs\files.js:1535:35)
    at symlinkWithOverwrite (C:\tools\isobuild\builder.js:740:5)
    at walk (C:\tools\isobuild\builder.js:458:9)
    at Builder.copyDirectory (C:\tools\isobuild\builder.js:594:5)
    at C:\tools\isobuild\bundler.js:2050:17
    at Function._.each._.forEach (C:\Users\steph\AppData\Local\.meteor\packages\meteor-tool\1.4.3_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:87:22)
    at JsImage.write (C:\tools\isobuild\bundler.js:2009:7)
    at ServerTarget.write (C:\tools\isobuild\bundler.js:2278:13)
    at C:\tools\isobuild\bundler.js:2373:30
    at C:\tools\isobuild\bundler.js:2506:9
    at Array.forEach (native)
    at C:\tools\isobuild\bundler.js:2496:26
    at C:\tools\isobuild\bundler.js:2436:7
    at C:\tools\isobuild\bundler.js:2837:22
    at C:\tools\utils\buildmessage.js:271:13
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    ...
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at bundle (C:\tools\isobuild\bundler.js:2670:31)
    at C:\tools\isobuild\bundler.js:2617:32
    at Object.withCache (C:\tools\fs\files.js:1601:12)
    at Object.exports.bundle (C:\tools\isobuild\bundler.js:2617:16)
    at C:\tools\runners\run-app.js:574:36
    at Function.run (C:\tools\tool-env\profile.js:490:12)
    at bundleApp (C:\tools\runners\run-app.js:573:34)
    at [object Object]._.extend._runOnce (C:\tools\runners\run-app.js:617:35)
    at [object Object]._.extend._fiber (C:\tools\runners\run-app.js:876:28)
    at C:\tools\runners\run-app.js:403:12
```

Any idea what it is about? Did anyone experience the same?

Meteor version: 1.4.3.1
Environment: Windows 7
Target platform: browser, server
Packages: many (atmosphere + npm)

**Comment by steph643** [comment]
I have tried:
- Reinstalling meteor
- Running meteor in an Administrator console
- Running `meteor npm cache clean`
None of these worked. 

It makes meteor extremely painful to use on Windows.

**Comment by steph643** [comment]
There are several issues that look similar when googling `npm EBUSY Windows`.

**Comment by steph643** [comment]
After a clean Meteor re-install (see below),  I got no more crash for about 30 minutes of intensive dev. But then exceptions have come back.

Clean Meteor re-install under Windows:
1. Run `meteor reset` on your project
2. Uninstall Meteor through the Windows Control Panel
3. Delete folder `C:\Users\userName\AppData\Local\.meteor`. 
4. If you get an error message saying that the folder cannot be deleted because file paths are too large, use the technique described [here](https://answers.microsoft.com/en-us/windows/forum/windows_vista-files/the-source-file-names-are-larger-than-is-supported/438a20a7-a964-4325-b755-8b5d75ddd15b) and [here](http://www.itworld.com/article/2694895/how-to-map-a-local-folder-to-a-drive-letter-in-windows.html).
5. Re-install Meteor

**Comment by steph643** [comment]
It seems the issue relates to long paths (maybe similar to [this one](https://github.com/meteor/meteor/issues/5278)?). 
I have moved my meteor project's folder closer to the root and there is no crash so far.

**Comment by steph643** [comment]
From different tests I did, it seems meteor doesn't work properly under Windows except if the project folder is at the root. Changing the issue title to reflect this.

**Comment by vipinlahoti** [comment]
Not working though the path is small

E:\>meteor create demom
C:\Users\vipinl\AppData\Local\.meteor\packages\meteor-tool\1.4.3_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:190
      throw error;
      ^

SyntaxError: Unexpected token

E:\>

**Comment by abernix** [comment]
@vipinlahoti Are you reporting a completely different issue than the one reported in this issue?  Or are you having the exact same problem as originally reported?

**Comment by hwillson** [comment]
Hi @steph643 - if you have a chance, could you test with Meteor 1.4.4.1 to see if this issue is still occurring?

```
meteor update --release 1.4.4.1
```

Thanks!

**Comment by steph643** [comment]
Ok, I will check this.

Notice that `meteor update --release 1.4.4.1` gives the following error:
```
C:\Meteor\myproject>meteor update --release 1.4.4.1
{ [Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\Steph\AppData\Local\
Temp\mt-1wjru38\mt-os.windows.x86_32\dev_bundle\lib\node_modules\babel-helper-de
fine-map']
  errno: -4051,
  code: 'ENOTEMPTY',
  syscall: 'rmdir',
  path: 'C:\\Users\\Steph\\AppData\\Local\\Temp\\mt-1wjru38\\mt-os.windows.x86
_32\\dev_bundle\\lib\\node_modules\\babel-helper-define-map' }
{ [Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\Steph\AppData\Local\
Temp\mt-d2v0i\plugin.minifyStdJS.os\npm\node_modules\meteor\babel-compiler\node_
modules\mkdirp']
  errno: -4051,
  code: 'ENOTEMPTY',
  syscall: 'rmdir',
  path: 'C:\\Users\\Steph\\AppData\\Local\\Temp\\mt-d2v0i\\plugin.minifyStdJS.
os\\npm\\node_modules\\meteor\\babel-compiler\\node_modules\\mkdirp' }
C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1.4.4_1\mt-os.window
s.x86_32\isopackets\ddp\npm\node_modules\meteor\promise\node_modules\meteor-prom
ise\promise_server.js:190
      throw error;
      ^

Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\Steph\AppData\Local\Tem
p\.tmpbqwcqn\standard-minifier-js-2.0.0\plugin.minifyStdJS.os\npm\node_modules\m
eteor\babel-compiler\node_modules\babel-core\lib\transformation\file'
    at Error (native)
    at Object.fs.rmdirSync (fs.js:758:18)
    at rmkidsSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1
.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:332:11)

    at rmdirSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1.
4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:322:7)
    at rimrafSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1
.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:293:9)
    at C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1.4.4_1\mt-os
.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:330:5
    at Array.forEach (native)
    at rmkidsSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1
.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:329:26)

    at rmdirSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1.
4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:322:7)
    at rimrafSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1
.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:293:9)
    at C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1.4.4_1\mt-os
.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:330:5
    at Array.forEach (native)
    at rmkidsSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1
.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:329:26)

    at rmdirSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1.
4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:322:7)
    at rimrafSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1
.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:293:9)
    at C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1.4.4_1\mt-os
.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:330:5
    at Array.forEach (native)
    at rmkidsSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1
.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:329:26)

    at rmdirSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1.
4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:322:7)
    at rimrafSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1
.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:293:9)
    at C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1.4.4_1\mt-os
.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:330:5
    at Array.forEach (native)
    at rmkidsSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1
.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:329:26)

    at rmdirSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1.
4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:322:7)
    at rimrafSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1
.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:293:9)
    at C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1.4.4_1\mt-os
.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:330:5
    at Array.forEach (native)
    at rmkidsSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1
.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:329:26)

    at rmdirSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1.
4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:322:7)
    at rimrafSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1
.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:293:9)
    at C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1.4.4_1\mt-os
.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:330:5
    at Array.forEach (native)
    at rmkidsSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1
.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:329:26)

    at rmdirSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1.
4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:322:7)
    at rimrafSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1
.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:293:9)
    at C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1.4.4_1\mt-os
.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:330:5
    at Array.forEach (native)
    at rmkidsSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1
.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:329:26)

    at rmdirSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1.
4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:322:7)
    at rimrafSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1
.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:293:9)
    at C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1.4.4_1\mt-os
.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:330:5
    at Array.forEach (native)
    at rmkidsSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1
.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:329:26)

    at rmdirSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1.
4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:322:7)
    at rimrafSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1
.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:293:9)
    at C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1.4.4_1\mt-os
.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:330:5
    at Array.forEach (native)
    at rmkidsSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1
.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:329:26)

    at rmdirSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1.
4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:322:7)
    at rimrafSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1
.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:293:9)
    at C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1.4.4_1\mt-os
.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:330:5
    at Array.forEach (native)
    at rmkidsSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1
.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:329:26)

    at rmdirSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1.
4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:322:7)
    at Function.rimrafSync [as sync] (C:\Users\Steph\AppData\Local\.meteor\pac
kages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimra
f\rimraf.js:293:9)
    at Object.rm_recursive (C:\tools\fs\files.js:303:12)
    at Object.files.rename (C:\tools\fs\files.js:1735:13)
    at Object.files.extractTarGz (C:\tools\fs\files.js:767:9)
    at Object.exports._extractAndConvert (C:\tools\packaging\tropohouse.js:50:9)

    at C:\tools\packaging\tropohouse.js:505:42
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at C:\tools\packaging\tropohouse.js:502:24
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\Steph\AppData\Local\.meteor\package
s\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscor
e\underscore.js:79:11)
    at C:\tools\packaging\tropohouse.js:469:11
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at Object.download (C:\tools\packaging\tropohouse.js:427:20)
    at C:\tools\packaging\tropohouse.js:613:18
    at C:\tools\utils\buildmessage.js:572:21
    at C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1.4.4_1\mt-os
.windows.x86_32\isopackets\ddp\npm\node_modules\meteor\promise\node_modules\mete
or-promise\fiber_pool.js:32:39
 => awaited here:
    at Promise.await (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-too
l\1.4.4_1\mt-os.windows.x86_32\isopackets\ddp\npm\node_modules\meteor\promise\no
de_modules\meteor-promise\promise_server.js:39:12)
    at Object.forkJoin (C:\tools\utils\buildmessage.js:604:6)
    at [object Object]._.extend.downloadPackagesMissingFromMap (C:\tools\packagi
ng\tropohouse.js:609:18)
    at C:\tools\project-context.js:808:25
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at C:\tools\project-context.js:807:20
    at C:\tools\packaging\catalog\catalog.js:100:5
    at C:\tools\utils\buildmessage.js:271:13
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at C:\tools\utils\buildmessage.js:264:29
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at C:\tools\utils\buildmessage.js:262:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at C:\tools\utils\buildmessage.js:253:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (C:\tools\packaging\catalo
g\catalog.js:99:31)
    at ProjectContext._downloadMissingPackages (C:\tools\project-context.js:806:
13)
    at C:\tools\project-context.js:283:9
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at ProjectContext._.extend._completeStagesThrough (C:\tools\project-context.
js:273:18)
    at C:\tools\project-context.js:265:12
    at Function.run (C:\tools\tool-env\profile.js:490:12)
    at ProjectContext._.extend.prepareProjectForBuild (C:\tools\project-context.
js:264:13)
    at C:\tools\cli\commands-packages.js:1528:20
    at C:\tools\utils\buildmessage.js:271:13
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at C:\tools\utils\buildmessage.js:264:29
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at C:\tools\utils\buildmessage.js:262:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at C:\tools\utils\buildmessage.js:253:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at Object.main.captureAndExit (C:\tools\cli\main.js:273:29)
    at maybeUpdateRelease (C:\tools\cli\commands-packages.js:1527:8)
    at Command.func (C:\tools\cli\commands-packages.js:1601:29)
    at C:\tools\cli\main.js:1483:23
```
Running it a second time gives this:
```
C:\Meteor\myproject>meteor update --release 1.4.4.1
{ [Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\Steph\AppData\Local\
Temp\mt-1rohym\plugin.minifyStdJS.os\npm\node_modules\meteor\babel-compiler\node
_modules\mkdirp']
  errno: -4051,
  code: 'ENOTEMPTY',
  syscall: 'rmdir',
  path: 'C:\\Users\\Steph\\AppData\\Local\\Temp\\mt-1rohym\\plugin.minifyStdJS
.os\\npm\\node_modules\\meteor\\babel-compiler\\node_modules\\mkdirp' }

Changes to your project's package version selections from updating the
release:

minifier-js*           upgraded from 1.2.18 to 2.0.0
standard-minifier-js*  upgraded from 1.2.3 to 2.0.0


* These packages have been updated to new versions that are not
backwards
compatible.
myproject: updated to Meteor 1.4.4.1.
```
I will come back to you after a working session to confirm if the issue has gone.

**Comment by abernix** [comment]
@steph643 Sorry for the problem with upgrading to 1.4.4.1 – unfortunately, I think you're running into a problem which exists in Meteor 1.4.4 which was fixed with https://github.com/meteor/meteor/commit/6055b49f8deb4153d45cdb9048997ca2be0b3083.  Ultimately, this was the reason that Meteor 1.4.4.1 was the first officially recommended version of the 1.4.4.x-series as opposed to 1.4.4 (sans patch number).  Realistically, if your application has been updated to 1.4.4.1 you should no longer see this (that is, after you've run it a second time you should no longer see it anymore).

I'm hopeful that the problem you originally reported might be resolved too due to a number of improves in Windows in the 1.4.4.x series, assuming you can get past this hiccup.

**Comment by steph643** [comment]
Thanks @abernix.
The original issue seems to be fixed. I've got no error since upgrading to 1.4.4.1 and moving my project back to long folder path. Good job!

**Comment by abernix** [comment]
Glad to hear it.  Given that news, I'll close this – but absolutely happy to help further and re-open if necessary. :smile:

**Comment by steph643** [comment]
The issue is back, occurring rarely.

I get two errors alternately. I believe I got those two before, even though I reported only the second one.

**Error 1**
```
Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\Steph\Travail\Meteor\ut
opiaedit3\.meteor\local\build\programs\web.browser-garbage-iohvxw\packages\twbs_
bootstrap'
    at Error (native)
    at Object.fs.rmdirSync (fs.js:758:18)
    at rmkidsSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1
.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:332:11)
    at rmdirSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1.
4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:322:7)
    at rimrafSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1
.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:293:9)
    at C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1.4.4_1\mt-os
.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:330:5
    at Array.forEach (native)
    at rmkidsSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1
.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:329:26)
    at rmdirSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1.
4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:322:7)
    at rimrafSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1
.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:293:9)
    at C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1.4.4_1\mt-os
.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:330:5
    at Array.forEach (native)
    at rmkidsSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1
.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:329:26)
    at rmdirSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1.
4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:322:7)
    at Function.rimrafSync [as sync] (C:\Users\Steph\AppData\Local\.meteor\pac
kages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimra
f\rimraf.js:293:9)
    at Object.rm_recursive (C:\tools\fs\files.js:303:12)
    at Object.renameDirAlmostAtomically (C:\tools\fs\files.js:1041:13)
    at Builder.complete (C:\tools\isobuild\builder.js:690:13)
    at C:\tools\isobuild\bundler.js:2380:13
    at C:\tools\isobuild\bundler.js:2826:29
    at Function._.each._.forEach (C:\Users\Steph\AppData\Local\.meteor\package
s\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscor
e\underscore.js:87:22)
    at C:\tools\isobuild\bundler.js:2824:11
    at C:\tools\utils\buildmessage.js:271:13
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at C:\tools\utils\buildmessage.js:264:29
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at C:\tools\utils\buildmessage.js:262:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at C:\tools\utils\buildmessage.js:253:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at bundle (C:\tools\isobuild\bundler.js:2670:31)
    at C:\tools\isobuild\bundler.js:2617:32
    at Object.withCache (C:\tools\fs\files.js:1652:12)
    at Object.exports.bundle (C:\tools\isobuild\bundler.js:2617:16)
    at C:\tools\runners\run-app.js:588:36
    at Function.run (C:\tools\tool-env\profile.js:490:12)
    at bundleApp (C:\tools\runners\run-app.js:587:34)
    at [object Object]._.extend._runOnce (C:\tools\runners\run-app.js:828:35)
    at [object Object]._.extend._fiber (C:\tools\runners\run-app.js:890:28)
    at C:\tools\runners\run-app.js:417:12
```
**Error 2**
```
Error: EBUSY: resource busy or locked, symlink 'C:\Users\Steph\AppData\Local\.
meteor\packages\ddp-client\1.3.4\npm\node_modules' -> 'C:\Users\Steph\Travail\
Meteor\myProject\.meteor\local\.build158391.build\programs\.build46035.server\
npm\node_modules\meteor\ddp-client\node_modules'
    at Error (native)
    at Object.fs.symlinkSync (fs.js:897:18)
    at Object.wrapper (C:\tools\fs\files.js:1586:35)
    at symlinkWithOverwrite (C:\tools\isobuild\builder.js:740:5)
    at walk (C:\tools\isobuild\builder.js:458:9)
    at Builder.copyDirectory (C:\tools\isobuild\builder.js:594:5)
    at C:\tools\isobuild\bundler.js:2050:17
    at Function._.each._.forEach (C:\Users\Steph\AppData\Local\.meteor\package
s\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscor
e\underscore.js:87:22)
    at JsImage.write (C:\tools\isobuild\bundler.js:2009:7)
    at ServerTarget.write (C:\tools\isobuild\bundler.js:2278:13)
    at C:\tools\isobuild\bundler.js:2373:30
    at C:\tools\isobuild\bundler.js:2506:9
    at Array.forEach (native)
    at C:\tools\isobuild\bundler.js:2496:26
    at C:\tools\isobuild\bundler.js:2837:22
    at C:\tools\utils\buildmessage.js:271:13
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at C:\tools\utils\buildmessage.js:264:29
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at C:\tools\utils\buildmessage.js:262:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at C:\tools\utils\buildmessage.js:253:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at bundle (C:\tools\isobuild\bundler.js:2670:31)
    at C:\tools\isobuild\bundler.js:2617:32
    at Object.withCache (C:\tools\fs\files.js:1652:12)
    at Object.exports.bundle (C:\tools\isobuild\bundler.js:2617:16)
    at C:\tools\runners\run-app.js:588:36
    at Function.run (C:\tools\tool-env\profile.js:490:12)
    at bundleApp (C:\tools\runners\run-app.js:587:34)
    at [object Object]._.extend._runOnce (C:\tools\runners\run-app.js:631:35)
    at [object Object]._.extend._fiber (C:\tools\runners\run-app.js:890:28)
    at C:\tools\runners\run-app.js:417:12
```

**Comment by steph643** [comment]
@abernix, would you mind reopening this issue? Thanks.

**Comment by hounaine** [comment]
+1 I am having the same problem
>> I tried meteor update but it did not work...
(Windows)
C:\Users\Pc_user\AppData\Local\.meteor\packages\meteor-tool\1.4.3_2\mt-os.window
s.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:190
      throw error;
      ^

**Comment by hounaine** [comment]
C:\Users\Pc_user\AppData\Local\.meteor\packages\meteor-tool\1.4.4_2
s.x86_32\isopackets\ddp\npm\node_modules\meteor\promise\node_module
ise\promise_server.js:190
      throw error;
      ^

Error: No metadata files found for isopack at: /C/Users/Pc_user/App
eteor/packages/pbastowski_angular-babel/1.3.7
    at [object Object]._.extend._loadUnibuildsFromPath (C:\tools\is
k.js:900:13)
    at C:\tools\packaging\tropohouse.js:521:21
    at Function._.each._.forEach (C:\Users\Pc_user\node_modules\und
score.js:103:9)
    at C:\tools\packaging\tropohouse.js:520:13
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-hel
)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-hel
)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-hel
)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at C:\tools\packaging\tropohouse.js:515:22
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-hel
)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-hel
)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-hel
)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at Object.download (C:\tools\packaging\tropohouse.js:427:20)
    at C:\tools\packaging\tropohouse.js:600:22
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-hel
)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-hel
)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-hel
)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at [object Object]._.extend.downloadPackagesMissingFromMap (C:\
ng\tropohouse.js:597:20)
    at C:\tools\project-context.js:808:25
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-hel
)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-hel
)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-hel
)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at C:\tools\project-context.js:807:20
    at C:\tools\packaging\catalog\catalog.js:100:5
    at C:\tools\utils\buildmessage.js:271:13
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-hel
)
    at C:\tools\utils\buildmessage.js:264:29
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-hel
)
    at C:\tools\utils\buildmessage.js:262:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-hel
)
    at C:\tools\utils\buildmessage.js:253:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-hel
)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (C:\tools\pac
g\catalog.js:99:31)
    at ProjectContext._downloadMissingPackages (C:\tools\project-co
13)
    at C:\tools\project-context.js:283:9
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-hel
)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-hel
)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-hel
)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at ProjectContext._.extend._completeStagesThrough (C:\tools\pro
js:273:18)
    at C:\tools\project-context.js:265:12
    at Function.run (C:\tools\tool-env\profile.js:490:12)
    at ProjectContext._.extend.prepareProjectForBuild (C:\tools\pro
js:264:13)
    at C:\tools\cli\commands-packages.js:1528:20
    at C:\tools\utils\buildmessage.js:271:13
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-hel
)
    at C:\tools\utils\buildmessage.js:264:29
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-hel
)
    at C:\tools\utils\buildmessage.js:262:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-hel
)
    at C:\tools\utils\buildmessage.js:253:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-hel
)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at Object.main.captureAndExit (C:\tools\cli\main.js:273:29)
    at maybeUpdateRelease (C:\tools\cli\commands-packages.js:1527:8
    at Command.func (C:\tools\cli\commands-packages.js:1601:29)
    at C:\tools\cli\main.js:1483:23

**Comment by hounaine** [comment]
I have another meteor app that works perfectly>> updated to Meteor 1.4.4.2
Any suggestions to get out from that is welcomed...
Thanks

**Comment by steph643** [comment]
@hounaine: I created [here](https://github.com/meteor/meteor/issues/8663) another issue for the "update" problem. I suggest we remove from this thread (which is about the "long path" issue) our posts that relate to the "update" issue.

**Comment by hounaine** [comment]
@steph643: ok, i will move mine... Thanks..

**Comment by hwillson** [comment]
Hi @steph643 - it really sounds like something outside of Meteor is accessing your files/directories at the same time Meteor is trying to work with them. This could be a virus/malware scanner? If you're using one, could you try temporarily disabling it to see if that makes a difference?

**Comment by steph643** [comment]
Thanks for the hint. I will experiment more on this and let you know. I have reasons to suspect Visual Studio Code.

**Comment by martineboh** [comment]
@vipinlahoti I had the same issue, but it was fixed after running `meteor reset`

**Comment by steph643** [comment]
@hwillson, I have no virus/malware scanner running.
When you say "something outside of Meteor accessing your files/directories", do you mean something accessing my projects' source files (in my projects folders) or accessing Meteor core files in Meteor install folder?

**Comment by vipinlahoti** [comment]
@martineboh I fixed this issue with fully uninstall and reinstalling the meteor, no help with `meteor reset`

**Comment by steph643** [comment]
Here is a status:
* The error is *not* due to long paths: it occurs when the project folder is in the `c:\Users` hierarchy.
* I looked for any resident application that might lock files. I removed Visual Studio Code, my antivirus, my backup solution. The problem remains.
* The error is still there after a clean Meteor reinstall and project reset.

**Comment by steph643** [comment]
Issue might be caused by a corrupted hard drive.  Currently testing.

**Comment by Rhywden** [comment]
Naw, I'm running into the same thing. And it's definitely not the /users-folder at fault here. It's also happening when the folder is at root-level.

**Comment by steph643** [comment]
@Rhywden, you're right. For the first time this morning, I got the issue at root-level also.

**Comment by Rhywden** [comment]
I'm using the 1.5-branch, by the way. 1.5-beta.16 does **not** have this issue. 1.5-beta.18 and 1.5-rc.1 do show it *always*.

**Comment by Rhywden** [comment]
1.5-rc.3 still has the ENOTEMPTY issue. 

@abernix : That's a rather serious issue for Windows users as there's no workaround.

**Comment by Rhywden** [comment]
Okay, 1.5-beta.17 works as well. So it has to be something that was changed going from beta.17 to beta.18

**Comment by Rhywden** [comment]
This commit: https://github.com/meteor/meteor/commit/0fbb97432c9f5c9b4c5958e719ca32d32a3922f1 seems to have fixed the issue for 1.5-rc.6

**Comment by steph643** [comment]
Seems to be fixed in 1.5.

**Comment by steph643** [comment]
In 1.5, the ENOTEMPTY error seems to be gone.  The EBUSY error is still there.

**Comment by steph643** [comment]
Both the ENOTEMPTY and EBUSY errors are still there in 1.5.

**Comment by abernix** [comment]
I'd be very curious if you still experience this with the latest Meteor 1.5.1 beta release (which includes #8773, an attempt to fix this issue), which was just published last night.  You can try updating with:

    meteor update --release 1.5.1-beta.0

**Comment by steph643** [comment]
Sorry to be late on this, but I'm still fighting with the 1.5.1-beta update (because of https://github.com/meteor/meteor/issues/8663). I'll let you know.

**Comment by steph643** [comment]
Got no luck with the update so far. Is there a way to patch the rimraf dependency in my current meteor version?

**Comment by abernix** [comment]
@steph643 Yes, due to the nature of the problem, unfortunately it will take getting over that bump to fully test the success of it.  Hope it helps once that happens though!

**Comment by abernix** [comment]
@steph643 Sorry, I didn't see your question earlier when I responded (Had the window open for a while and GitHub didn't update!).

> Is there a way to patch the rimraf dependency in my current meteor version?

Hmm, you could try going to the following path:

> **Note:** Replace `YOUR_USER` and `YOUR_VERSION` appropriately.  `YOUR_VERSION` can be grabbed from the error message you're receiving.

    C:\Users\YOUR_USER\AppData\Local\.meteor\packages\meteor-tool\YOUR_VERSION\mt-os.windows.x86_32\dev_bundle\lib\node_modules

And then running:

    meteor npm install rimraf

This might work, but no guarantee (and untested. :wink:).  Worse case, it if messes things up you'll need to reinstall Meteor.

**Comment by steph643** [comment]
I had finally succeeded in updating to 1.5.1-beta, by shortening the path of my TEMP/TMP environment variables. I then worked for 2 hours without any crash. Looks good. I will try again later today.

**Comment by steph643** [comment]
Sadly, the EBUSY error still occurs (3 times in a 4 hours session, but frequency seems to increase).
The ENOTEMPTY error seems to be gone.

**Comment by santiagopuentep** [comment]
I'm getting the ENOTEMPTY: directory not empty, rmdir when I have Visual Studio Code opened and not when it's closed. Using meteor 1.5.0.

Maybe it helps.

**Comment by brucejo75** [comment]
ENOTEMPTY error is covered in #8801.

**Comment by steph643** [comment]
@brucejo75 , @santiagopuentep: 
It seems the ENOTEMPTY error has been fixed in 1.5.1 beta. Do you confirm?
(to install: `meteor update --release 1.5.1-beta.0`)

**Comment by santiagopuentep** [comment]
I can't install the beta, it hangs at extracting as it usually does when I try to update meteor.

Anyway, in this post the user bouchepat says it doesn't help installing 1.5.1-beta.0 (second to last comment as of now):
https://github.com/meteor/meteor/issues/8801#issuecomment-309506219

Adding the .meteor folder to the windows defender exceptions solves the issue it seems, as also does closing Visual Studio Code when compiling.

**Comment by steph643** [comment]
> I can't install the beta, it hangs at extracting as it usually does when I try to update meteor.

Try moving your project folder to a very short path (like `c:\p`). Worked for me.

**Comment by santiagopuentep** [comment]
@steph643 I tried that some time ago and it didn't work. The only way I could find is reinstalling meteor with the official installer when it's out...

My frustration issue posted here:
https://github.com/meteor/meteor/issues/8802

**Comment by tobeatiger** [comment]
I have similar issue, still not solution?

`
E:\simple-todos>meteor --version
Meteor 1.5

E:\simple-todos>meteor --verbose
[[[[[ ~\E\simple-todos ]]]]]

=> Started proxy.
Local package version is up-to-date: allow-deny@1.0.5
Local package version is up-to-date: autopublish@1.0.7
Local package version is up-to-date: autoupdate@1.3.12
Local package version is up-to-date: babel-compiler@6.19.1
Local package version is up-to-date: babel-runtime@1.0.1
Local package version is up-to-date: base64@1.0.10
Local package version is up-to-date: binary-heap@1.0.10
Local package version is up-to-date: blaze@2.3.2
Local package version is up-to-date: blaze-html-templates@1.1.2
Local package version is up-to-date: blaze-tools@1.0.10
Local package version is up-to-date: boilerplate-generator@1.1.0
Local package version is up-to-date: caching-compiler@1.1.9
Local package version is up-to-date: caching-html-compiler@1.1.2
Local package version is up-to-date: callback-hook@1.0.10
Local package version is up-to-date: check@1.2.5
Local package version is up-to-date: ddp@1.2.5
Local package version is up-to-date: ddp-client@1.3.4
Local package version is up-to-date: ddp-common@1.2.8
Local package version is up-to-date: ddp-server@1.3.14
Local package version is up-to-date: deps@1.0.12
Local package version is up-to-date: diff-sequence@1.0.7
Local package version is up-to-date: dynamic-import@0.1.0
Local package version is up-to-date: ecmascript@0.8.0
Local package version is up-to-date: ecmascript-runtime@0.4.1
Local package version is up-to-date: ecmascript-runtime-client@0.4.1
Local package version is up-to-date: ecmascript-runtime-server@0.4.1
Local package version is up-to-date: ejson@1.0.13
Local package version is up-to-date: es5-shim@4.6.15
Local package version is up-to-date: fastclick@1.0.13
Local package version is up-to-date: geojson-utils@1.0.10
Local package version is up-to-date: hot-code-push@1.0.4
Local package version is up-to-date: html-tools@1.0.11
Local package version is up-to-date: htmljs@1.0.11
Local package version is up-to-date: http@1.2.12
Local package version is up-to-date: id-map@1.0.9
Local package version is up-to-date: insecure@1.0.7
Local package version is up-to-date: jquery@1.11.10
Local package version is up-to-date: launch-screen@1.1.1
Local package version is up-to-date: livedata@1.0.18
Local package version is up-to-date: logging@1.1.17
Local package version is up-to-date: meteor@1.6.1
Local package version is up-to-date: meteor-base@1.1.0
Local package version is up-to-date: minifier-css@1.2.16
Local package version is up-to-date: minifier-js@2.1.0
Local package version is up-to-date: minimongo@1.2.0
Local package version is up-to-date: mobile-experience@1.0.4
Local package version is up-to-date: mobile-status-bar@1.0.14
Local package version is up-to-date: modules@0.9.0
Local package version is up-to-date: modules-runtime@0.8.0
Local package version is up-to-date: mongo@1.1.18
Local package version is up-to-date: mongo-id@1.0.6
Local package version is up-to-date: npm-mongo@2.2.24
Local package version is up-to-date: observe-sequence@1.0.16
Local package version is up-to-date: ordered-dict@1.0.9
Local package version is up-to-date: promise@0.8.9
Local package version is up-to-date: random@1.0.10
Local package version is up-to-date: reactive-var@1.0.11
Local package version is up-to-date: reload@1.1.11
Local package version is up-to-date: retry@1.0.9
Local package version is up-to-date: routepolicy@1.0.12
Local package version is up-to-date: shell-server@0.2.3
Local package version is up-to-date: spacebars@1.0.15
Local package version is up-to-date: spacebars-compiler@1.1.2
Local package version is up-to-date: standard-minifier-css@1.3.4
Local package version is up-to-date: standard-minifier-js@2.1.0
Local package version is up-to-date: templating@1.3.2
Local package version is up-to-date: templating-compiler@1.3.2
Local package version is up-to-date: templating-runtime@1.3.2
Local package version is up-to-date: templating-tools@1.1.2
Local package version is up-to-date: tracker@1.1.3
Local package version is up-to-date: ui@1.0.13
Local package version is up-to-date: underscore@1.0.10
Local package version is up-to-date: url@1.1.0
Local package version is up-to-date: webapp@1.3.16
Local package version is up-to-date: webapp-hashing@1.0.9
C:\Users\samsung\AppData\Local\.meteor\packages\templating-compiler\1.3.2\plugin.compileTemplatesBatch.os\npm\node_modul
es\meteor\promise\node_modules\meteor-promise\promise_server.js:190
      throw error;
      ^

Error: UNKNOWN: unknown error, symlink 'E:\simple-todos\node_modules\core-js' -> 'E:\simple-todos\.meteor\local\.build26
3190.build\programs\.build973225.server\npm\node_modules\core-js'
    at Error (native)
    at Object.fs.symlinkSync (fs.js:897:18)
    at Object.wrapper (C:\tools\fs\files.js:1586:35)
    at symlinkWithOverwrite (C:\tools\isobuild\builder.js:740:5)
    at walk (C:\tools\isobuild\builder.js:458:9)
    at C:\tools\isobuild\builder.js:556:11
    at Array.forEach (native)
    at walk (C:\tools\isobuild\builder.js:464:34)
    at Builder.copyDirectory (C:\tools\isobuild\builder.js:594:5)
    at C:\tools\isobuild\bundler.js:2216:17
    at Function._.each._.forEach (C:\Users\samsung\AppData\Local\.meteor\packages\meteor-tool\1.5.0\mt-os.windows.x86_32
\dev_bundle\lib\node_modules\underscore\underscore.js:87:22)
    at JsImage.write (C:\tools\isobuild\bundler.js:2175:7)
    at ServerTarget.write (C:\tools\isobuild\bundler.js:2444:13)
    at C:\tools\isobuild\bundler.js:2563:30
    at C:\tools\isobuild\bundler.js:2696:9
    at Array.forEach (native)
    at C:\tools\isobuild\bundler.js:2686:26
    at C:\tools\isobuild\bundler.js:3027:22
    at C:\tools\utils\buildmessage.js:271:13
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at bundle (C:\tools\isobuild\bundler.js:2860:31)
    at C:\tools\isobuild\bundler.js:2807:32
    at Object.withCache (C:\tools\fs\files.js:1652:12)
    at Object.exports.bundle (C:\tools\isobuild\bundler.js:2807:16)
    at C:\tools\runners\run-app.js:588:36
    at Function.run (C:\tools\tool-env\profile.js:490:12)
    at bundleApp (C:\tools\runners\run-app.js:587:34)
    at [object Object]._.extend._runOnce (C:\tools\runners\run-app.js:631:35)
    at [object Object]._.extend._fiber (C:\tools\runners\run-app.js:890:28)
    at C:\tools\runners\run-app.js:417:12

E:\simple-todos>`

**Comment by tobeatiger** [comment]
I create the project in C drive in win7, it works now. Seems it doesn't work in any other drive except C.

**Comment by steph643** [comment]
@brucejo75, @abernix , @hwillson , @santiagopuentep and others,

I think there is some confusion here, so I'll try to summarize.

Problems from a user perspective:
- Update/reset failure (U1)
- Build failure (U2)

Same problems from a technical perspective:
- ENOTEMPTY
- EBUSY
- EPERM

U1+ENOTEMPTY seems to be solved with https://github.com/meteor/meteor/issues/8663#issuecomment-315457703, which is a temporary hack that would require further investigation. @hwillson, I think  https://github.com/meteor/meteor/issues/8663 should be reopened, maybe with a different title ("[Windows] ENOTEMPTY error when updating/reseting a project"), so that we can track progress on this.

U2+ENOTEMPTY seems to be gone since v1.5.1-beta.0 (rimraf update). This issue has been discussed mainly in https://github.com/meteor/meteor/issues/8485 and https://github.com/meteor/meteor/issues/8801.

U1+EBUSY seems to never happen.

U2+EBUSY is still occurring and is a major annoyance. From the different threads, it seems this might be due to third-party apps watching files (antivirus, file sharing, backup system, text editor...). This has been discussed mainly in https://github.com/meteor/meteor/issues/8801.

U1+EPERM seems to be rare. From my experience, when an update fails this way, updating your project *again* works without error.

U2+EPERM seems to never happen.

Having each problem in a separate Github issue would be great. Oh, I didn't mention that https://github.com/meteor/meteor/issues/8801 also discusses build performance issues :-)

**Comment by hwillson** [comment]
Thanks for the great analysis/breakdown @steph643! Sounds good about #8663 - doing that now.

**Comment by steph643** [comment]
Closing this one.
Issue **Update fails with ENOTEMPTY** is discussed in https://github.com/meteor/meteor/issues/8663.
Issue **Build fails with EBUSY** is discussed in https://github.com/meteor/meteor/issues/8801.
