### ISSUE TITLE
Windows 7/10 - ENOTEMPTY, EBUSY, EPERM on launch and meteor reset with Meteor 1.5 - Visual Code

### ISSUE THREAD

**Issue by bouchepat** [meteor/meteor#8801]
Developing on Windows 7.
Recently updated to Meteor 1.5. Since then I keep getting the following error (rimraf.js seems to be the problem):

```
=> Started proxy.
=> Started MongoDB.
C:\Users\xxx\AppData\Local\.meteor\packages\templating-compiler\1.3.2\plugin
.compileTemplatesBatch.os\npm\node_modules\meteor\promise\node_modules\meteor-pr
omise\promise_server.js:190
      throw error;
      ^

Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\xxx\Meteor\zeteor-web
\.meteor\local\.build153140.build\programs\.build104129.server\assets\app\node_m
odules\node-pre-gyp\lib'
    at Error (native)
    at Object.fs.rmdirSync (fs.js:758:18)
    at rmkidsSync (C:\Users\xxx\AppData\Local\.meteor\packages\meteor-tool\1
.5.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:332:11)
    at rmdirSync (C:\Users\xxx\AppData\Local\.meteor\packages\meteor-tool\1.
5.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:322:7)
    at fixWinEPERMSync (C:\Users\xxx\AppData\Local\.meteor\packages\meteor-t
ool\1.5.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:202:
5)
    at rimrafSync (C:\Users\xxx\AppData\Local\.meteor\packages\meteor-tool\1
.5.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:300:28)
    at C:\Users\xxx\AppData\Local\.meteor\packages\meteor-tool\1.5.0\mt-os.w
indows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:330:5
    at Array.forEach (native)
    at rmkidsSync (C:\Users\xxx\AppData\Local\.meteor\packages\meteor-tool\1
.5.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:329:26)
    at rmdirSync (C:\Users\xxx\AppData\Local\.meteor\packages\meteor-tool\1.
5.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:322:7)
    at fixWinEPERMSync (C:\Users\xxx\AppData\Local\.meteor\packages\meteor-t
ool\1.5.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:202:
5)
    at rimrafSync (C:\Users\xxx\AppData\Local\.meteor\packages\meteor-tool\1
.5.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:300:28)
    at C:\Users\xxx\AppData\Local\.meteor\packages\meteor-tool\1.5.0\mt-os.w
indows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:330:5
    at Array.forEach (native)
    at rmkidsSync (C:\Users\xxx\AppData\Local\.meteor\packages\meteor-tool\1
.5.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:329:26)
    at rmdirSync (C:\Users\xxx\AppData\Local\.meteor\packages\meteor-tool\1.
5.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:322:7)
    at rimrafSync (C:\Users\xxx\AppData\Local\.meteor\packages\meteor-tool\1
.5.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:293:9)
    at C:\Users\xxx\AppData\Local\.meteor\packages\meteor-tool\1.5.0\mt-os.w
indows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:330:5
    at Array.forEach (native)
    at rmkidsSync (C:\Users\xxx\AppData\Local\.meteor\packages\meteor-tool\1
.5.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:329:26)
    at rmdirSync (C:\Users\xxx\AppData\Local\.meteor\packages\meteor-tool\1.
5.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:322:7)
    at rimrafSync (C:\Users\xxx\AppData\Local\.meteor\packages\meteor-tool\1
.5.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:293:9)
    at C:\Users\xxx\AppData\Local\.meteor\packages\meteor-tool\1.5.0\mt-os.w
indows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:330:5
    at Array.forEach (native)
    at rmkidsSync (C:\Users\xxx\AppData\Local\.meteor\packages\meteor-tool\1
.5.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:329:26)
    at rmdirSync (C:\Users\xxx\AppData\Local\.meteor\packages\meteor-tool\1.
5.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:322:7)
    at rimrafSync (C:\Users\xxx\AppData\Local\.meteor\packages\meteor-tool\1
.5.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:293:9)
    at C:\Users\xxx\AppData\Local\.meteor\packages\meteor-tool\1.5.0\mt-os.w
indows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:330:5
    at Array.forEach (native)
    at rmkidsSync (C:\Users\xxx\AppData\Local\.meteor\packages\meteor-tool\1
.5.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:329:26)
    at rmdirSync (C:\Users\xxx\AppData\Local\.meteor\packages\meteor-tool\1.
5.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:322:7)
    at rimrafSync (C:\Users\xxx\AppData\Local\.meteor\packages\meteor-tool\1
.5.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:293:9)
    at C:\Users\xxx\AppData\Local\.meteor\packages\meteor-tool\1.5.0\mt-os.w
indows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:330:5
    at Array.forEach (native)
    at rmkidsSync (C:\Users\xxx\AppData\Local\.meteor\packages\meteor-tool\1
.5.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:329:26)
    at rmdirSync (C:\Users\xxx\AppData\Local\.meteor\packages\meteor-tool\1.
5.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:322:7)
    at rimrafSync (C:\Users\xxx\AppData\Local\.meteor\packages\meteor-tool\1
.5.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:293:9)
    at C:\Users\xxx\AppData\Local\.meteor\packages\meteor-tool\1.5.0\mt-os.w
indows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:330:5
    at Array.forEach (native)
    at rmkidsSync (C:\Users\xxx\AppData\Local\.meteor\packages\meteor-tool\1
.5.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:329:26)
    at rmdirSync (C:\Users\xxx\AppData\Local\.meteor\packages\meteor-tool\1.
5.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:322:7)
    at Function.rimrafSync [as sync] (C:\Users\xxx\AppData\Local\.meteor\pac
kages\meteor-tool\1.5.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\
rimraf.js:293:9)
    at Object.rm_recursive (C:\tools\fs\files.js:303:12)
    at Builder.abort (C:\tools\isobuild\builder.js:696:11)
    at C:\tools\isobuild\bundler.js:2738:13
    at C:\tools\isobuild\bundler.js:3027:22
    at C:\tools\utils\buildmessage.js:271:13
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at C:\tools\utils\buildmessage.js:264:29
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at C:\tools\utils\buildmessage.js:262:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at C:\tools\utils\buildmessage.js:253:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at bundle (C:\tools\isobuild\bundler.js:2860:31)
    at C:\tools\isobuild\bundler.js:2807:32
    at Object.withCache (C:\tools\fs\files.js:1652:12)
    at Object.exports.bundle (C:\tools\isobuild\bundler.js:2807:16)
    at C:\tools\runners\run-app.js:588:36
    at Function.run (C:\tools\tool-env\profile.js:490:12)
    at bundleApp (C:\tools\runners\run-app.js:587:34)
    at [object Object]._.extend._runOnce (C:\tools\runners\run-app.js:631:35)
    at [object Object]._.extend._fiber (C:\tools\runners\run-app.js:890:28)
    at C:\tools\runners\run-app.js:417:12
`
At that time, I try to do a meteor reset, sometimes it works, sometimes I get similar error. I tried to delete manually the build folder but run into permission issues. Tried to delete folder as administrator but same permission issue.

I attempted to downgrade the meteor version to 1.4.4.3 but no luck. Also attempted to uninstall Meteor, delete .meteor folder in AppData/local and reinstall but same issue occurs.

I noticed after the meteor update to 1.5, rimraf@2.6.1 was flagged as extraneous. Did a npm prune or uninstall the package but it is still listed.

This is my meteor packages:

```
meteor-base@1.1.0             # Packages every Meteor app needs to have
mobile-experience@1.0.4       # Packages for a great mobile UX
mongo@1.1.18                   # The database Meteor supports right now
reactive-var@1.0.11            # Reactive variable for tracker
jquery@1.11.10                  # Helpful client-side library
tracker@1.1.3                 # Meteor's client-side reactive programming library

standard-minifier-css@1.3.4   # CSS minifier run for production mode
es5-shim@4.6.15                # ECMAScript 5 compatibility for older browsers.

xolvio:cleaner
hwillson:stub-collections
shell-server@0.2.3
angular2-compilers
orgztion:meteor-global-tether
fortawesome:fontawesome
babel-runtime@1.0.1
alanning:roles
msavin:mongol
jalik:ufs-gridfs
jalik:ufs-local
dburles:mongo-collection-instances
accounts-password@1.3.6
service-configuration@1.0.11
poorvavyas:es6-shim
jalik:ufs
dynamic-import@0.1.0
reywood:publish-composite
http@1.2.12
abernix:standard-minifier-js
`
This is my package.json
`
"dependencies": {
    "angular/animations": "^4.2.1",
    "angular/common": "^4.2.1",
    "angular/compiler": "^4.2.2",
    "angular/core": "^4.2.2",
    "angular/forms": "^4.2.2",
    "angular/http": "^4.2.2",
    "angular/platform-browser": "^4.2.2",
    "angular/platform-browser-dynamic": "^4.2.2",
    "angular/router": "^4.2.2",
    "ng-bootstrap/ng-bootstrap": "^1.0.0-alpha.26",
    "nglibs/meta": "^0.4.0-rc.1",
    "types/meteor-publish-composite": "0.0.32",
    "types/node": "^7.0.31",
    "angular2-file-drop": "^0.2.0",
    "angular2-meteor-polyfills": "^0.2.0",
    "angular2-meteor-tests-polyfills": "0.0.2",
    "babel-runtime": "^6.23.0",
    "bcrypt": "^1.0.2",
    "bootstrap": "^4.0.0-alpha.6",
    "cheerio": "^0.22.0",
    "dragula": "^3.7.2",
    "g": "^2.0.1",
    "gm": "^1.23.0",
    "lodash": "^4.17.4",
    "meteor-node-stubs": "^0.2.11",
    "meteor-rxjs": "^0.4.7",
    "ng2-auto-complete": "^0.12.0",
    "ng2-dragula": "^1.5.0",
    "papaparse": "^4.3.3",
    "prerender-node": "^2.7.1",
    "reflect-metadata": "^0.1.10",
    "rxjs": "^5.4.0",
    "spawn-sync": "^1.0.15",
    "systemjs": "^0.20.14",
    "tether": "^1.4.0",
    "toastr": "^2.1.2",
    "try-thread-sleep": "^1.0.2",
    "tslib": "^1.7.1",
    "zone.js": "^0.8.12"
  }
`

Development has come to a stall, any help would be appreciated.

Thanks

**Comment by brucejo75** [comment]
_Note_: @bouchepat, if you enclose your console output in "```" (triple "`") then everything enclosed will be code formatted so it is easier to read.

### ENOTEMPTY error
This is happening to me a lot too.

### Environment
- Windows: v10 `1607 (OS build 14393.1358)`
- Meteor: 1.5

### Observations
* I will get the `ENOTEMPTY` during builds and on executing `meteor reset`.  I have been wiping out the `.meteor/local` directory when it does not clear up on its own.  Sometimes I just rerun and it works out.
* Granted, I do stop builds often hitting `^C` and I think that is what tends to happen before the problem appears.
* My v1.5 builds are taking much longer now.  I have noticed that the Microsoft Anti-malware process is taking up a lot of CPU.  I assume v1.5 emits a lot more files that 1.4.4.3 used to?
* SSD drives reduce the number of build issues.  I recently updated to an SSD for my meteor projects.  I immediately noticed that the builds became much more reliable and with less issues.

_Suggestion_: On Windows test the build with Defender running and building on a hard drive volume.  These 2 things may exacerbate timing issues in the build.  Also, if random `^C`'s can be built into the tests that may uncover some issues as well.

### Console Output
```
E:\mroot\meris>meteor reset
As a precaution, meteor reset only clears the local database that is provided by meteor run for development.
The database specified with MONGO_URL will NOT be reset.
C:\Users\Bruce\AppData\Local\.meteor\packages\meteor-tool\1.5.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:218
      throw error;
      ^

Error: ENOTEMPTY: directory not empty, rmdir 'E:\mroot\meris\.meteor\local\build-garbage-13v2yzf\programs\server\npm\node_modules'
    at Error (native)
    at Object.fs.rmdirSync (fs.js:758:18)
    at rmkidsSync (C:\Users\Bruce\AppData\Local\.meteor\packages\meteor-tool\1.5.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:332:11)
    at rmdirSync (C:\Users\Bruce\AppData\Local\.meteor\packages\meteor-tool\1.5.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:322:7)
    at rimrafSync (C:\Users\Bruce\AppData\Local\.meteor\packages\meteor-tool\1.5.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:293:9)
    at C:\Users\Bruce\AppData\Local\.meteor\packages\meteor-tool\1.5.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:330:5
    at Array.forEach (native)
    at rmkidsSync (C:\Users\Bruce\AppData\Local\.meteor\packages\meteor-tool\1.5.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:329:26)
    at rmdirSync (C:\Users\Bruce\AppData\Local\.meteor\packages\meteor-tool\1.5.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:322:7)
    at rimrafSync (C:\Users\Bruce\AppData\Local\.meteor\packages\meteor-tool\1.5.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:293:9)
    at C:\Users\Bruce\AppData\Local\.meteor\packages\meteor-tool\1.5.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:330:5
    at Array.forEach (native)
    at rmkidsSync (C:\Users\Bruce\AppData\Local\.meteor\packages\meteor-tool\1.5.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:329:26)
    at rmdirSync (C:\Users\Bruce\AppData\Local\.meteor\packages\meteor-tool\1.5.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:322:7)
    at rimrafSync (C:\Users\Bruce\AppData\Local\.meteor\packages\meteor-tool\1.5.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:293:9)
    at C:\Users\Bruce\AppData\Local\.meteor\packages\meteor-tool\1.5.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:330:5
    at Array.forEach (native)
    at rmkidsSync (C:\Users\Bruce\AppData\Local\.meteor\packages\meteor-tool\1.5.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:329:26)
    at rmdirSync (C:\Users\Bruce\AppData\Local\.meteor\packages\meteor-tool\1.5.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:322:7)
    at rimrafSync (C:\Users\Bruce\AppData\Local\.meteor\packages\meteor-tool\1.5.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:293:9)
    at C:\Users\Bruce\AppData\Local\.meteor\packages\meteor-tool\1.5.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:330:5
    at Array.forEach (native)
    at rmkidsSync (C:\Users\Bruce\AppData\Local\.meteor\packages\meteor-tool\1.5.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:329:26)
    at rmdirSync (C:\Users\Bruce\AppData\Local\.meteor\packages\meteor-tool\1.5.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:322:7)
    at rimrafSync (C:\Users\Bruce\AppData\Local\.meteor\packages\meteor-tool\1.5.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:293:9)
    at C:\Users\Bruce\AppData\Local\.meteor\packages\meteor-tool\1.5.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:330:5
    at Array.forEach (native)
    at rmkidsSync (C:\Users\Bruce\AppData\Local\.meteor\packages\meteor-tool\1.5.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:329:26)
    at rmdirSync (C:\Users\Bruce\AppData\Local\.meteor\packages\meteor-tool\1.5.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:322:7)
    at Function.rimrafSync [as sync] (C:\Users\Bruce\AppData\Local\.meteor\packages\meteor-tool\1.5.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:293:9)
    at Object.rm_recursive (C:\tools\fs\files.js:303:12)
    at Command.func (C:\tools\cli\commands.js:1262:9)
    at C:\tools\cli\main.js:1483:23
```

**Comment by bouchepat** [comment]
Thanks @brucejo75, I reformatted as suggested. I develop on both Windows 7 and Windows 10; the issue seems to occur more frequently on Windwos 7. It did happen with previous meteor versions but since 1.5 it happens way more often.

**Comment by brucejo75** [comment]
Turns out there are a few issues filed on this:
#8614, #8485.

2 things:
1. Windows Defender can [exclude folders](https://support.microsoft.com/en-us/instantanswers/64495205-6ddb-4da1-8534-1aeaf64c0af8/add-an-exclusion-to-windows-defender) from running the real time protection.  You must be running as administrator to access it.
2. Meteor 1.5.1 has a [fix](https://github.com/meteor/meteor/pull/8773) on the way.  Running the latest 1.5.1 beta will pull that fix in.

**Comment by bouchepat** [comment]
I did install version 1.5.1 beta but it did not help on the issues ENOTEMPTY or EPERM.

However, I noticed visual code process was spiking during the build process and tried the following, which seems to help on Windows 7 (haven't tried on Win10 yet):

When error EPERM occurs on meteor reset:
- close visual code
- delete .meteor/local folder
- run meteor reset

When error ENOTEMPTY occurs on launch:
- close visual code
- try again
- when app is running reopen visual code

Adding .meteor to the files.exclude settings on Visual Code did help, only closing Visual Code seems to be helping.

Maybe someone can try and see if they notice a difference.

**Comment by brucejo75** [comment]
Interesting!  Yes, excluding .meteor from visual code or any other editor that scans the directory tree is key.  That would definitely disrupt the build process.

I already had my visual code ignoring .meteor.  So there must be something else too.  I have not see an issue since I excluded my projects from Defender scanning.

**Comment by santiagopuentep** [comment]
Closing VisualStudo Code while meteor is compiling never gives me issues, but keeping it open sometimes does, randomly.

If I make a change, save and right after that close VS Code it always runs fine.

Adding .meteor to the excludes does not help at all here.

**Comment by santiagopuentep** [comment]
Excluding the folder from defender scanning solves the issue for me too.

**Comment by brucejo75** [comment]
**Note**: I just excluded `node.exe`, `code.exe` and `codehelper.exe` processes from Windows Defender and now I get no CPU devoted to `Windows antimalware...`.

I updated my [instructions](https://github.com/meteor/meteor/issues/8801#issuecomment-309480283) with that piece.

**Comment by bouchepat** [comment]
I created an issue on Visual Code (see above), it seems that even with files and folders added to the settings: "files.exclude", there is still a watcher running and possibly responsible for the errors. 
For those with long building times, I noticed the time went from minutes to seconds since I started closing VS code. Hopefully this can help others.

**Comment by brucejo75** [comment]
Thanks @bouchepat!!

I added that [suggestion ](https://github.com/meteor/meteor/issues/8801#issuecomment-310094351)to my [instructions](https://github.com/meteor/meteor/issues/8801#issuecomment-309480283).

**Comment by brucejo75** [comment]
Bouchepat's vscode issue: https://github.com/Microsoft/vscode/issues/29132

**Comment by brucejo75** [comment]
OK, after more experimentation I discovered that the exclusion directories need to be `.meteor` not `.meteor/local`.  Not sure why, I had been going back and forth on it but the exclusion of `.meteor` really knocks the CPU usage (and I assume file opening) down.  So I updated my [instructions ](https://github.com/meteor/meteor/issues/8801#issuecomment-309480283)to reflect that.

**Comment by s-devaney** [comment]
Here are some of my observations:

- I only seem to experience this issue when using the built in terminal in VSCode
- I upgraded to Meteor 1.5 on release day and have been using it since with no issues
- I upgraded to the latest version of VSCode a few days ago, and that's when this issue started
- I have completely uninstalled/reinstalled Meteor, downgraded to 1.4.4.3 and back up to 1.5 and have the issue in both versions

So I suspect it's either a Windows update or a VSCode update which is causing this issue

**Comment by steph643** [comment]
As explained in https://github.com/meteor/meteor/issues/8485#issuecomment-315533298, the two remaining issues are:
- **Update fails with ENOTEMPTY**:  see https://github.com/meteor/meteor/issues/8663 for a temporary workaround and a (hopefully) coming fix
- **Build fails with EBUSY**: let's discuss this issue here. Maybe the title could be changed to "[Windows] Build fails with EBUSY".

**Comment by steph643** [comment]
I'm still fighting against the "Build fails with EBUSY" issue (under Meteor 1.5.1.).

I've removed all third-party apps: antivirus, anti-malware, backup system, Dropbox, etc.

If I close my text editor, it seems the issue never occurs.
When I use Notepad++ on a project's file, the issue occurs very frequently.
When I use Visual Studio Code, the issue occurs quite often, even with the settings from https://github.com/meteor/meteor/issues/8801#issuecomment-309480283.

Also, if I move my project folder from `C:\Users\Steph\Work\Meteor` to `C:\Meteor`, the issue occurs far less frequently.

Any idea?

**Comment by brucejo75** [comment]
I noticed that when I changed my settings that it worked perfectly for a while.  And then something would happen and VS Code would go back to monitoring the `.meteor/build` files.  I think it may have reoccurred after I did a GIT commit, but I have not had a chance to go back and investigate it fully yet.

Did you get the latest VS Code release?  mjbvc [comment](https://github.com/Microsoft/vscode/issues/29132#issuecomment-313813113) points to some changes that they made and are now in the 1.14 release.

I have been using that release with much better results, but I have been mostly working client side and that does not seem to be as much of a problem as server side changes.

**Comment by steph643** [comment]
Yes, I use VS Code  1.14. And I've too noticed that changing server side code seems to get you more errors.

**Comment by brucejo75** [comment]
With VS Code 1.14.2 it looks like a final [issue](https://github.com/Microsoft/vscode/issues/30723) was put to rest.  Now the builds are working great with very little interference from VS Code processes.

@steph643, did you put all the [exclusions](https://github.com/meteor/meteor/issues/8801#issuecomment-309480283) in?

@bouchepat, I think this can be closed?

**Comment by bouchepat** [comment]
Yes this is resolved on my side, no longer have ENOTEMPTY, EBUSY, EPERM errors. Closing this.
Maybe unrelated, development on Windows 10 is still quite painful as any changes take a long time to refresh in browser. But is better on Windows 7.

**Comment by brucejo75** [comment]
@bouchepat, I run on Windows 10 with all my issues resolved.  Very fast builds now.  Do you have another process that may be monitoring files?  Did you configure the exclusions for Defender?

**Comment by bouchepat** [comment]
The build is not the issue and I don't see any process monitoring any files. Somehow it takes Chrome forever to reload the app (about 2 minutes). 
When I run it on Windows 7 it's much faster but again the machine performs a bit better. Need to do more investigation.

**Comment by brucejo75** [comment]
Oh, OK.  I have not seen this.

You mean 2 minutes before automatic reload?  Or when you refresh it can take 2 minutes?

**Comment by steph643** [comment]
EBUSY issue still occurs under Meteor 1.6.0.1 (Chocolatey based install).

**Comment by brucejo75** [comment]
@steph643, did you put all the [exclusions](https://github.com/meteor/meteor/issues/8801#issuecomment-309480283) in?

**Comment by steph643** [comment]
Yep, I did.

**Comment by brucejo75** [comment]
Is your project hosted in a directory on a HDD?  Do you have an SSD installed somewhere?  Can you try running the project on an SSD drive?  This might narrow it down...

**Comment by steph643** [comment]
My project is on a SSD (my dev machine has no HDD).

**Comment by steph643** [comment]
EBUSY issue still occurs (during build) under Meteor 1.7.0.1.

**Comment by brucejo75** [comment]
Hi @steph643, I don't know how to help you.

Basically, I took a look at all the processes running during a build and went through each one and make sure they made sense.  That is how I originally found that Defender and VSCode were monitoring everything and causing the file system to slow down enough that the timeouts would fail in the build.

Maybe you have something else monitoring the files?  Are you running another Virus scanner?

I have moved on to using UBUNTU via Windows Subsystem for Linux (WSL) on Windows 10.  Which has it's own quirks, but the benefit of using Ubuntu is worth it.
