### ISSUE TITLE
Internet Explorer IE11 blank page

### ISSUE THREAD

**Issue by mi-k4** [meteor/meteor#9056]
Hello, I develop a website with Meteor, it works perfectly on chrome, chromium, Firefox and Edge but on the Internet explore 11 I have a blank page. I had opened a issue in the repository of meteor-files because I thought that my problem was bound to it package, but I think that the problem is the use  the strict mode in javascript files.

https://github.com/VeliovGroup/Meteor-Files/issues/483

Console errors:
![29654117-30eb2ff0-88ac-11e7-8c81-493244fe701f](https://user-images.githubusercontent.com/3338681/30020097-00d5cd88-9163-11e7-9907-23c557de980d.png)

![29654117-30eb2ff0-88ac-11e7-8c81-493244fe701f](https://user-images.githubusercontent.com/3338681/30020144-20695084-9163-11e7-8f91-7d7c3f99a8d4.png)

My meteor/.versions file :

```
accounts-base@1.3.1
accounts-password@1.4.0
alanning:roles@1.2.16
aldeed:collection2-core@2.0.1
aldeed:schema-deny@2.0.0
aldeed:schema-index@2.0.0
aldeed:simple-schema@1.5.3
aldeed:template-extension@4.1.0
allow-deny@1.0.6
arillo:flow-router-helpers@0.5.2
audit-argument-checks@1.0.7
autoupdate@1.3.12
babel-compiler@6.19.4
babel-runtime@1.0.1
base64@1.0.10
binary-heap@1.0.10
blaze@2.3.2
blaze-html-templates@1.1.2
blaze-tools@1.0.10
boilerplate-generator@1.1.1
caching-compiler@1.1.9
caching-html-compiler@1.1.2
callback-hook@1.0.10
cfs:http-methods@0.0.32
check@1.2.5
coffeescript@1.12.7_1
coffeescript-compiler@1.12.7_1
dburles:google-maps@1.1.5
ddp@1.3.0
ddp-client@2.0.0
ddp-common@1.2.9
ddp-rate-limiter@1.0.7
ddp-server@2.0.0
deps@1.0.12
diff-sequence@1.0.7
dynamic-import@0.1.1
ecmascript@0.8.2
ecmascript-runtime@0.4.1
ecmascript-runtime-client@0.4.3
ecmascript-runtime-server@0.4.1
ejson@1.0.13
email@1.2.3
es5-shim@4.6.15
fastclick@1.0.13
froatsnook:request@2.74.0
geojson-utils@1.0.10
hot-code-push@1.0.4
html-tools@1.0.11
htmljs@1.0.11
http@1.2.12
id-map@1.0.9
isotope:isotope@2.1.0_1
jeremy:geocomplete@1.8.0
jquery@1.11.10
kadira:blaze-layout@2.3.0
kadira:flow-router@2.12.1
launch-screen@1.1.1
livedata@1.0.18
localstorage@1.1.1
logging@1.1.17
mdg:validated-method@1.1.0
mdg:validation-error@0.5.1
meteor@1.7.1  # <=========================================== here
meteor-base@1.1.0
meteorhacks:async@1.0.0
meteorspark:util@0.2.0
mikowals:batch-insert@1.1.14
minifier-css@1.2.16
minifier-js@2.1.1
minimongo@1.2.1
mobile-experience@1.0.4
mobile-status-bar@1.0.14
modules@0.9.4
modules-runtime@0.8.0
momentjs:moment@2.18.1
mongo@1.1.22
mongo-id@1.0.6
mrt:jquery-imagesloaded@0.0.2
nefiltari:yaki@0.1.81
npm-bcrypt@0.9.3
npm-mongo@2.2.30
observe-sequence@1.0.16
ordered-dict@1.0.9
ostrio:cookies@2.2.2
ostrio:files@1.8.2
percolate:momentum@0.7.2
percolate:velocityjs@1.2.1_1
practicalmeteor:chai@2.1.0_1
practicalmeteor:loglevel@1.2.0_2
practicalmeteor:mocha@2.4.5_6
practicalmeteor:mocha-core@1.0.1
practicalmeteor:sinon@1.14.1_2
promise@0.8.9
raix:eventemitter@0.1.3
random@1.0.10
rate-limit@1.0.8
reactive-dict@1.1.9
reactive-var@1.0.11
reload@1.1.11
retry@1.0.9
routepolicy@1.0.12
service-configuration@1.0.11
session@1.1.7
sha@1.0.9
shell-server@0.2.4
simple:json-routes@2.1.0
simple:reactive-method@1.0.2
softwarerero:accounts-t9n@1.3.11
spacebars@1.0.15
spacebars-compiler@1.1.3
srp@1.0.10
standard-minifier-css@1.3.4
standard-minifier-js@2.1.1
tap:i18n@1.8.2
templating@1.3.2
templating-compiler@1.3.2
templating-runtime@1.3.2
templating-tools@1.1.2
tmeasday:check-npm-versions@0.3.1
tmeasday:test-reporter-helpers@0.2.1
tracker@1.1.3
ui@1.0.13
underscore@1.0.10
url@1.1.0
useraccounts:core@1.14.2
useraccounts:flow-routing@1.14.2
useraccounts:unstyled@1.14.2
webapp@1.3.17
webapp-hashing@1.0.9
wizonesolutions:underscore-string@1.0.0
zimme:active-route@2.3.2

```

The error exists on the Internet explorer only and the error exist in development and in production mode. The server work with debian stretch (9).

I did not manage to reproduce the error with a version relieved by the code and without giving all the source code, sorry.

Thanks you for all and good day

**Comment by mi-k4** [comment]
Hello, I have the same error with the new version of meteor. I managed to reproduce a similar error with this repository:

https://github.com/mi-k4/meteor-project-error

the error :

![capture d ecran_2017-09-12_08-14-33](https://user-images.githubusercontent.com/3338681/30311315-f441736e-9794-11e7-9172-a881ecb4103e.png)

**Comment by mi-k4** [comment]
Hello, the problem is solved,

I had install babel-polyfill to correct a bug for meteor simpl-schema and the problem came from there. I updated to the last version of simpl-schema to benefit of this PR :
aldeed/node-simple-schema@8362691
and to remove babel-polyfill and now that works.

Thank you very much

**Comment by etyp** [comment]
@mi-k4 we're using original Meteor SimpleSchema package but running into the same issue on a new machine. Any idea what the issue might be? We tried updating our Meteor babel preset to the latest version (6.26.1) and still have the issue.

Any insight/ideas would be awesome. It's not happening on machines that have had our project running for some time, so I'm assuming something is cached/installed that prevents the issue.

**Comment by mi-k4** [comment]
Hello @etyp,

I have no other idea than the solution which I gave in my previous answers. I completely remove babel-pollyfill and used the version "simpl-schema": "^0.3.2" in my package.json.

Do you have exactly the same versions of packages from a machine to the other one? Do you have the same version of nodejs?

To find the problem, I simplified at the most the project and remove dependencies one after the other until that it works.

Good lucks

**Comment by Remeus** [comment]
I had the same issue:
+ My app was working fine except on IE
+ On IE, I had a first issue related to Symbol which was not defined:
> Object doesn't support this property or method "for"
+ I solved this issues by adding babel browser-polyfill in the `<head>` of my page, but doing so I ran into a second issue related to ostrio-file:
> Match error: Expected plain object

**To solve it:**
I removed babel browser-polyfill in `<head>` and replaced it with symbol-es6:
`<script src="https://cdn.jsdelivr.net/npm/symbol-es6@0.1.2/dist/symbol-es6.min.js"></script>`

**Comment by dr-dimitru** [comment]
Hello @Remeus ,

Could you please create an issue at [`meteor-files` repository](https://github.com/VeliovGroup/Meteor-Files/issues), please follow [our issue template](https://github.com/VeliovGroup/Meteor-Files/blob/master/.github/ISSUE_TEMPLATE).
