### ISSUE TITLE
Const declarations are not supported in strict mode

### ISSUE THREAD

**Issue by nelson-uruworks** [meteor/meteor#9291]
Hi all,

We are using METEOR@1.5.2.2-rc.0 on our production app, and we are encountering issues when using Safari. The app doesn't load and the error on the console says:

> [Error] SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode.
> (anonymous function) (modules.js, line 73083)

Followed by many other errors like:
> [Error] TypeError: undefined is not an object (evaluating 'Package.modules.meteorInstall')

From what we could find, there should be a npm package that is using `'use strict'` and later on using a `const` variable declaration. Unfortunatelly we couldn't find the package, but looking at the modules.js file the context is the following:

> "lib": {
>     "node": {
>         "index.js": function(require, exports, module) {
> 
>     /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
>     //                                                                                                                     //
>     // node_modules/superagent/lib/node/index.js                                                                           //
>     //                                                                                                                     //
>     /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
>     //
>     'use strict'; // 1
>     // 2
>     /**                                                                                                                    // 3
>      * Module dependencies.                                                                                                // 4
>      */
>         // 5
>         // 6
>     const debug = require('debug')('superagent'); // 7
>     const formidable = require('formidable'); // 8
>     const FormData = require('form-data'); // 9
>     const Response = require('./response'); // 10
>     const parse = require('url').parse; // 11
>     const format = require('url').format; // 12
>     const resolve = require('url').resolve; // 13
>     let methods = require('methods'); // 14
>     const Stream = require('stream'); // 15
>     const utils = require('../utils'); // 16
>     const unzip = require('./unzip').unzip; // 17
>     const extend = require('extend'); // 18
>     const mime = require('mime'); // 19
>     const https = require('https'); // 20
>     const http = require('http'); // 21
>     const fs = require('fs'); // 22
>     const qs = require('qs'); // 23
>     const zlib = require('zlib'); // 24
>     const util = require('util'); // 25
>     const pkg = require('../../package.json'); // 26
>     const RequestBase = require('../request-base'); // 27

We assumed it was the superagent package, but taking a look at it, the `const` declarations are actually `var` declaration in the index.js file. Is there anything that could be replacing this declarations when the app is built?

Thank you,
Nelson

**Comment by benjamn** [comment]
This is a symptom of https://github.com/meteor/meteor-feature-requests/issues/6, which I consider a top priority for Meteor 1.6.1.

**Comment by benjamn** [comment]
I think this should follow https://github.com/meteor/meteor/pull/9439, since we need to compile `const` declarations only for the `web.browser.legacy` platform. However, since #9439 is coming in Meteor 1.6.2, I've moved this to the 1.6.2 milestone for now.

**Comment by jehartzog** [comment]
@nelson-uruworks I'm getting a similar error and I found the module causing it, [accounts-facebook](https://github.com/meteor/meteor/blob/02cfd0fab1cdf11cc9582017556b0362416d53e6/packages/accounts-facebook/facebook.js#L4). I see this error on Safari (WebKit) - 9.1.1  Mac OS - 10.11.5.

As a core Meteor package, this const declaration is supposed to be transpiled, yet this is what the code looks like when running locally as dev:
```
(function(){

/////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                     //
// packages/accounts-facebook/facebook.js                                                              //
//                                                                                                     //
/////////////////////////////////////////////////////////////////////////////////////////////////////////
                                                                                                       //
Accounts.oauth.registerService('facebook');                                                            // 1
                                                                                                       // 2
if (Meteor.isClient) {                                                                                 // 3
  const loginWithFacebook = function(options, callback) {                                              // 4
    // support a callback without options                                                              // 5
...
```
The production code also includes the `const` declaration, harder to read in minified code but it's there.
```
!function(){var e=Package.meteor.Meteor,o=Package.meteor.global,a=Package.meteor.meteorEnv,c=Package["accounts-base"].Accounts,n=Package["facebook-oauth"].Facebook;(function(){!Package["accounts-ui"]||Package["service-configuration"]||Package.hasOwnProperty("facebook-config-ui")||console.warn("Note: You're using accounts-ui and accounts-facebook,\nbut didn't install the configuration UI for the Facebook\nOAuth. You can install it with:\n\n    meteor add facebook-config-ui\n")}).call(this),function(){if(c.oauth.registerService("facebook"),e.isClient){const o=function(e,o){o||"function"!=typeof e||(o=e,e=null);var a=c.oauth.credentialRequestCompleteHandler(o);n.requestCredential(e,a)};c.registerClientLoginFunction("facebook",o),e.loginWithFacebook=function(){return c.applyLoginFunction("facebook",arguments)}}else c.addAutopublishFields({forLoggedInUser:["services.facebook"],forOtherUsers:["services.facebook.id","services.facebook.username","services.facebook.gender"]})}.call(this),"undefined"==typeof Package&&(Package={}),Package["accounts-facebook"]={}}();
```

**Comment by hwillson** [comment]
@jehartzog This was fixed in https://github.com/meteor/meteor/pull/9507 and the updated `accounts-*` packages have been published. Please try updating to the most recent version of `accounts-facebook`.

**Comment by jehartzog** [comment]
Thanks, sorry for not catching that PR before I posted. I updated Meteor and all my packages just a few weeks ago, so in my mind I thought I was running current versions. I'll check for updated versions of packages before posting next time!

**Comment by benjamn** [comment]
This is the solution we're recommending in Meteor 1.7: https://github.com/meteor/meteor/pull/9826#issuecomment-392541768

If the symbolic linking strategy doesn't work for everyone, we could consider adding additional configuration options to the `"meteor"` section of `package.json` to enable compilation for specific npm packages in `node_modules`, though in general we prefer to avoid solving problems with centralized configuration as much as possible.

**Comment by alanning** [comment]
We are still seeing this error with Meteor 1.7.0.3 and Safari 9.1.1 but the strange thing is that Safari seems to be indicating the issue is coming from code that is in a Meteor Package rather than `node_modules`.  The package in question is a local one and does not have any npm dependencies (i.e. no n`ode_modules` directory).

SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode.

Safari Version 9.1.1 (10601.6.17)
OSX Yosemite 10.10.5 (14F1808)

Safari points to the first line of this code when reporting the error:
```
!function() {
   var e = Package.meteor.Meteor, t = Package.meteor.global, i = Package.meteor.meteorEnv, a = Package.underscore._, r;
   (function() {
       "use strict";
       const e=!1;
       function t(e, t) {
           return Math.floor(Math.random() * (t - e)) + e
       }
       function i(e) {
           const t = typeof e.query;
           return "function" === t ? e.query() : "object" === t ? e.query : null
       }
       r = function(e) {
           this.reset(), this.collection = e.collection, this.defaultFilterName = e.defaultFilterName || "", this.activeFilterDep = new Deps.Dependency, this.name = e.name || "FilteredCollection-" + t(1, 1e3), e.template && (this.template = e.template)
       }, a.extend(r.prototype, {
           reset: function() {
               this.data = {}
           },
```

This looks like code that Meteor is creating itself so my guess is that it is incorrectly targeting Safari 9.1.1 with the "evergreen" modern browsers when perhaps it should be considered a "legacy" browser with polyfills?
