### ISSUE TITLE
Cannot run meteor test-packages anymore on a package

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#9695]
I have a CI running on all my packages. It installs Meteor and runs mostly just:

```
meteor test-packages ./
```

But this does not work anymore. For example, [for this package](https://github.com/peerlibrary/meteor-blaze-common-component), if I run the above command I get:

```
=> Errors prevented startup:                  
   
   While selecting package versions:
   error: Conflict: Constraint babel-compiler@6.13.0 is not satisfied by babel-compiler 7.0.5.
   Constraints on package "babel-compiler":
   * babel-compiler@~7.0.0 <- top level
   * babel-compiler@7.0.0 <- ecmascript 0.10.5 <- allow-deny 1.1.0 <- mongo 1.4.4 <- autoupdate 1.4.0
   * babel-compiler@7.0.0 <- ecmascript 0.10.5 <- autoupdate 1.4.0
   * babel-compiler@6.13.0 <- coffeescript 1.11.1_4 <- local-test:peerlibrary:blaze-common-component 0.4.3
```

If I run:

```
meteor --release 1.6.0.1 test-packages ./
```

Then I get:

```
=> Errors prevented startup:                  
   
   While loading plugin `basicFileTypes` from package `meteor`:
   packages/basicFileTypes_plugin.js:39:9: Package._define is not a function
   at packages/basicFileTypes_plugin.js:39:9
   at packages/basicFileTypes_plugin.js:41:3
```

Running `meteor --release 1.4.4.5 test-packages ./` works.

Does this mean now we have a fixed `--release` when testing packages?

**Comment by nathan-muir** [comment]
Also had the same issue doing something as basic as - 

```
$ meteor --release 1.6.0.1 create --bare test-app
$ meteor --port 3005
[[[[[ ~/tmp/test-app ]]]]]                        

=> Started proxy.                             
=> Errors prevented startup:                  
   
   While loading plugin `basicFileTypes` from package `meteor`:
   packages/basicFileTypes_plugin.js:39:9: Package._define is not a function
   at packages/basicFileTypes_plugin.js:39:9
   at packages/basicFileTypes_plugin.js:41:3
   
   
=> Your application has errors. Waiting for file change.
=> Meteor 1.6.1 is available. Update this project with 'meteor update'.
=> Started MongoDB.
```

I was able to work around the issue by adding a strict constraint `meteor@=1.8.0`

```
$ cat >> .meteor/packages <<EOM
meteor@=1.8.0
EOM
$ meteor --port 3005
[[[[[ ~/tmp/test-app ]]]]]                        

=> Started proxy.                             
=> Meteor 1.6.1 is available. Update this project with 'meteor update'.
=> Started MongoDB.                           
                                                                                   
Changes to your project's package version selections:
                                              
meteor  downgraded from 1.8.3 to 1.8.0        

=> Started your app.                          

=> App running at: http://localhost:3005/

```

**Comment by hwillson** [comment]
Hi all - please try updating your `meteor` package to the latest version (1.8.4)

```
meteor update meteor
```

and let us know if that helps. Thanks!

**Comment by mitar** [comment]
I think this will help with `meteor --release 1.6.0.1 test-packages ./`, but not with `meteor test-packages ./`.

**Comment by mitar** [comment]
Yes, `meteor --release 1.6.0.1 test-packages ./` now works because it pulls newer mongo package.

**Comment by hwillson** [comment]
The original issue here lists 2 separate issues. The second issue (and the one that I have a feeling most people are 👍'ing) has been resolved. If anyone here is getting a `Package._define` error, please run a `meteor update meteor` to fix the issue.

Regarding the first issue @mitar:

```
=> Errors prevented startup:                  
   
   While selecting package versions:
   error: Conflict: Constraint babel-compiler@6.13.0 is not satisfied by babel-compiler 7.0.5.
   Constraints on package "babel-compiler":
   * babel-compiler@~7.0.0 <- top level
   * babel-compiler@7.0.0 <- ecmascript 0.10.5 <- allow-deny 1.1.0 <- mongo 1.4.4 <- autoupdate 1.4.0
   * babel-compiler@7.0.0 <- ecmascript 0.10.5 <- autoupdate 1.4.0
   * babel-compiler@6.13.0 <- coffeescript 1.11.1_4 <- local-test:peerlibrary:blaze-common-component 0.4.3
```

Meteor 1.6.1 requires `babel-compiler` 7.0.x. When you're calling `meteor test-packages ./`, you're using Meteor 1.6.1 to create a dummy test app behind the scenes, that then loads your package for testing. This dummy test app requires `babel-compiler` 7.0.x (since it was created with Meteor 1.6.1). In your package however, you're making a `api.versionsFrom('1.4.0.1')` call, so you're requesting to use a version of `coffeescript` that's compatible with the `coffeescript` dependency included when Meteor 1.4.0.1 was released. Because of the `api.versionsFrom('1.4.0.1')` call, the constraint solver is deciding that the appropriate version of `coffescript` to use with your package is 1.11.1_4, which ultimately requires `babel-compiler` 6.13.0, which is obviously not patch compatible with Meteor 1.6.1's `babel-compiler` 7.0.x (hence the error).

There are 2 ways to fix this:

1. Use an earlier release when running your tests, so you don't bring in the new mandatory `babel-compiler` 7.0.x requirement. E.g. `meteor --release 1.6.0.1 test-packages ./`

2. Update your `api.versionsFrom('1.4.0.1')` call to something more recent, that allows the constraint solver to find a compatible version of `coffeescript` that works with both Meteor 1.6.1 and your package. You don't have to increase it much - using `api.versionsFrom('1.4.3.1')` should work. This is because `coffeescript` was moved into `non-core` in release 1.4.3.1, which means as of 1.4.3.1 the version of `coffeescript` used is no longer constrained by the Meteor release. If your package (and it's dependent packages) are switched to use `api.versionsFrom('1.4.3.1')` (and you aren't using an explicit 1.x `coffeescript` version anywhere), then `meteor test-packages ./` will use `coffeescript@2.2.1_1` (which is the most recent version, and is compatible with Meteor 1.6.1).

**Comment by hwillson** [comment]
See https://github.com/meteor/meteor/issues/9695#issuecomment-370192987 for the resolution to this issue. Closing - thanks!

**Comment by latifs** [comment]
Hey guys,

Trying to upgrade meteor.
Here's what I did:
* in .meteor/release, I've modified `METEOR@1.5.2.2` to `METEOR@1.6.1.1`
* I've deleted .meteor/version
* I've used `npx babel-upgrade --write --install` to get the newest babel packages

But I'm still having this issue,
even when trying to run `meteor update meteor`
or when modifying `api.versionsFrom('1.4.3.1')` to something more recent

Any Ideas?

Here is what I get:

> => Errors prevented startup:
> 
>  While selecting package versions:
>    error: Conflict: Constraint babel-compiler@6.18.2 is not satisfied
>    by babel-compiler 7.0.8.
>    Constraints on package "babel-compiler":
>    * babel-compiler@~7.0.6 <- top level
>    * babel-compiler@7.0.0 <- ecmascript 0.10.8
>    * babel-compiler@6.18.2 <- ssrwpo:minifierjs 2.0.0 <-
>    ssrwpo:uglifyjs2 0.6.0
> 
> => Your application has errors. Waiting for file change.

**Comment by koyanoa** [comment]
@latifs: I had the same problem, and just got it solved. I just had to update the submodules:
`git submodule sync
  git submodule update --init
`
The reason was that we had customized the minifierjs for sourcemaps, and then you need to sync the submodules manually. Hope that helps you too!
