### ISSUE TITLE
[1.6.2-beta.12] The Mongo server and the Meteor query disagree on how many documents match your query

### ISSUE THREAD

**Issue by sebakerckhof** [meteor/meteor#9780]
I'm seeing this error while testing 1.6.2-beta.12:
```
Exception in defer callback: Error: The Mongo server and the Meteor query disagree on how many documents match your query. Maybe it is hitting a Mongo edge case? The query is: {"meetingId":"FwBgXEWuvKBdx8wPR"}
I20180329-18:10:41.525(2)?     at packages/mongo/oplog_observe_driver.js:881:15
I20180329-18:10:41.526(2)?     at Object.Meteor._noYieldsAllowed (packages/meteor.js:733:12)
I20180329-18:10:41.526(2)?     at OplogObserveDriver._publishNewResults (packages/mongo/oplog_observe_driver.js:851:12)
I20180329-18:10:41.526(2)?     at OplogObserveDriver._runQuery (packages/mongo/oplog_observe_driver.js:758:10)
I20180329-18:10:41.526(2)?     at OplogObserveDriver._runInitialQuery (packages/mongo/oplog_observe_driver.js:658:10)
I20180329-18:10:41.526(2)?     at packages/mongo/oplog_observe_driver.js:191:10
I20180329-18:10:41.526(2)?     at packages/mongo/oplog_observe_driver.js:15:9
I20180329-18:10:41.526(2)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1189:26)
I20180329-18:10:41.526(2)?     at packages/meteor.js:505:25
I20180329-18:10:41.527(2)?     at runWithEnvironment (packages/meteor.js:1241:24)
```

This has been observed before: https://github.com/meteor/meteor/issues/9619. Then it was caused by an undefined field in the query, and fixed by: https://github.com/meteor/meteor/pull/9671 , but this seems like a different issue.

I got it consistently when loading a certain part of my app

The weird thing is, after I triggered a rebuild (by just adding a blank line somewhere) and Meteor rebuilds, the error disappeared.

**Comment by carlosbaraza** [comment]
This issue can be reproduced checking out the code in this PR: https://github.com/meteor/todos/pull/258

Tested the PR with the release version `1.6.2-beta.15` and it still crashes:

```
I20180331-16:38:44.197(1)? Exception in defer callback: Error: The Mongo server and the Meteor query disagree on how many documents match your query. Maybe it is hitting a Mongo edge case? The query is: {"_id":"cNNQ3hLh22ggre9fr","$or":[{"userId":{"$exists":false}},{}]}
I20180331-16:38:44.197(1)?     at packages/mongo/oplog_observe_driver.js:881:15
I20180331-16:38:44.197(1)?     at Object.Meteor._noYieldsAllowed (packages/meteor.js:733:12)
I20180331-16:38:44.197(1)?     at OplogObserveDriver._publishNewResults (packages/mongo/oplog_observe_driver.js:851:12)
I20180331-16:38:44.198(1)?     at OplogObserveDriver._runQuery (packages/mongo/oplog_observe_driver.js:758:10)
I20180331-16:38:44.198(1)?     at OplogObserveDriver._runInitialQuery (packages/mongo/oplog_observe_driver.js:658:10)
I20180331-16:38:44.198(1)?     at packages/mongo/oplog_observe_driver.js:191:10
I20180331-16:38:44.198(1)?     at packages/mongo/oplog_observe_driver.js:15:9
I20180331-16:38:44.198(1)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1189:12)
I20180331-16:38:44.199(1)?     at packages/meteor.js:505:25
I20180331-16:38:44.199(1)?     at runWithEnvironment (packages/meteor.js:1241:24)
        1) sends no todos for a private list when not logged in
```

**Comment by hwillson** [comment]
Hi all - while this issue was originally fixed by https://github.com/meteor/meteor/pull/9671, we decided to revert that PR's commits. It was decided that a better solution to the problem would be to throw loudly and clearly when anyone attempts to use `undefined` with Mongo/Minimongo (see https://github.com/meteor/meteor/pull/9671#issuecomment-369622897). The work to do this hasn't been completed yet, so in the meantime this issue can still occur. 

Since this issue isn't being tracked in any other open issue, I'll keep this one open and mark it as `pull-requests-encouraged` (if anyone is interested in working on it, please let us know!). See the above linked to comment, as well as https://github.com/meteor/meteor/pull/9671#issuecomment-369637644, for implementation details. Thanks!

**Comment by sebakerckhof** [comment]
@hwillson thanks for the context, I can create a PR for this. I see 2 options:
1. Check every query for undefined values.

Could be a oneliner by leveraging JSON.stringify:
```js
JSON.stringify(query, (key, value) => { if(value === undefined) { throw new Error(`${key} is undefined`); } return value; });
```

However, I would definitely not do it in minimongo since values can be dynamically bound there and initially undefined.
E.g. Our angular-meteor application has a lot of these:
```js
this.autorun(() => {
  this.foo = Foos.findOne({ _id: this.getReactively('selectedFooId') });
});
```
But 'selectedFooId' is initially undefined.

2. Just change the error message here:

https://github.com/meteor/meteor/blob/devel/packages/mongo/oplog_observe_driver.js#L882
This also means there's no extra work to be done for every query. But are we sure this only happens when there's an undefined?

**Comment by msaelices** [comment]
@sebakerckhof I upgraded the React Todos app to Meteor 1.8.1 and It seems the error is gone. I've created this PR with the upgrading: https://github.com/meteor/todos/pull/278

So I guess this is a piece of good news and maybe this issue is already fixed.

**Comment by msaelices** [comment]
@sebakerckhof bad news, the Blaze version is still failing:

<img width="1678" alt="Screenshot 2019-11-07 at 12 42 18" src="https://user-images.githubusercontent.com/136875/68386345-21912200-015c-11ea-8f5f-c51b27b9aead.png">
